### ISSUE TITLE
salmon quant is failing

### ISSUE THREAD

**Issue by sagnikbanerjee15** [COMBINE-lab/salmon#113]
I have single ended reads in a fastq file which I aligned with bowtie against the transcriptome. Now I am running the following command:
./bin/salmon quant -t ../Data/DRR029379.fq -p 6 -l A -a ../Data/DRR029379_after_bowtie.bam -o ../Data/DRR029379_after_salmon
and this the error I am getting

Version Info: This is the most recent version of Salmon.
# salmon (alignment-based) v0.7.2
# [ program ] => salmon
# [ command ] => quant
# [ targets ] => { ../Data/DRR029379.fq }
# [ threads ] => { 6 }
# [ libType ] => { A }
# [ alignments ] => { ../Data/DRR029379_after_bowtie.bam }
# [ output ] => { ../Data/DRR029379_after_salmon }
Error: @RG lines are at odds with binary encoded reference data
============
Exception : [ERROR: Failed to open file ../Data/DRR029379_after_bowtie.bam, exiting!
]
============
./bin/salmon alignment-quant was invoked improperly.
For usage information, try ./bin/salmon quant --help-alignments
Exiting.

I cannot figure out anything from this message. Please help.

Thank you

**Comment by rob-p** [comment]
Hi @sagnikbanerjee15,

  It looks like you are providing the `-t` flag with the *reads* rather than the target transcriptome (i.e. set of reference transcripts).  The error is saying that the target file does not contain the reference sequences listed in the bam file.  The argument to the `-t` flag should be a FASA file that contains the sequence of the reference transcripts, and the names and lengths of those reference transcripts should match the names and lengths encoded in the BAM file.

--Rob

**Comment by sagnikbanerjee15** [comment]
Ok then with which flag shall I provide the file of reads?

**Comment by rob-p** [comment]
Salmon has two modes; alignment-based and quasi-mapping based.  When you are using the alignment-based mode (i.e. feeding it a BAM file of aligned reads), you don't need to provide it with the raw reads.  This is because all of the relevant information is already contained within the BAM file.  

On the other hand, in quasi-mapping mode, you index the set of reference transcripts (using `salmon index`) and then provide salmon with the location of the index and the raw reads (i.e. the FASTQ file).  In this case, it performs quasi-mapping (a lightweight stand in for alignment), and so it is not necessary to provide the BAM file.  Please refer to quasi-mapping based mode and alignment-based mode in [the documentation](http://salmon.readthedocs.io/en/latest/salmon.html#quasi-mapping-based-mode-including-lightweight-alignment) for more details.

**Comment by sagnikbanerjee15** [comment]
I just provided the list of transcripts in fasta format with the -t flag but its still giving me the same error.

**Comment by rob-p** [comment]
Are the names consistent between the BAM file and the reference you are providing?  What do you get from `samtools view -H ../Data/DRR029379_after_bowtie.bam` versus looking at the reference transcript FASTA file?  Also, this error:

```
Exception : [ERROR: Failed to open file ../Data/DRR029379_after_bowtie.bam, exiting!]
```

suggests that the BAM file itself could not be opened.  Are you certain the relative path to the file is correct from the current working directory?

**Comment by sagnikbanerjee15** [comment]
I checked, the file is in fact present in that path. I also checked the names that you are referring to and I found that the first part of the names match but for the entries in the bam file the lines end with "LN:xxx" . This the output from the command you suggested.
@HD     VN:1.0  SO:unsorted
@SQ     SN:NC_003070.9:0-30427671       LN:30427671
@SQ     SN:NC_003070.9:3630-5899        LN:2269
@SQ     SN:NC_003070.9:3630-5899        LN:2269
@SQ     SN:NC_003070.9:3630-3913        LN:283
@SQ     SN:NC_003070.9:3995-4276        LN:281
@SQ     SN:NC_003070.9:4485-4605        LN:120
@SQ     SN:NC_003070.9:4705-5095        LN:390
@SQ     SN:NC_003070.9:5173-5326        LN:153
@SQ     SN:NC_003070.9:5438-5899        LN:461

and the headers in the fasta file are somethig like this:

>NC_003070.9:12107542-12107677
>NC_003070.9:12106952-12107084
>NC_003070.9:12106547-12106703
>NC_003070.9:12106201-12106435
>NC_003070.9:12105744-12105911
>NC_003070.9:12105547-12105662
>NC_003070.9:12105328-12105409
>NC_003070.9:12104890-12105118
>NC_003070.9:12104783-12109336
>NC_003070.9:12109037-12109336
>NC_003070.9:12108864-12108936
>NC_003070.9:12108592-12108794
>NC_003070.9:12108343-12108474
>NC_003070.9:12107766-12108159
>NC_003070.9:12107542-12107677
>NC_003070.9:12106952-12107084
>NC_003070.9:12106547-12106703
>NC_003070.9:12106201-12106435
>NC_003070.9:12105744-12105911
>NC_003070.9:12105547-12105662

**Comment by rob-p** [comment]
The error you're seeing is a result of the BAM parser (libstaden) finding an inconsistency in the BAM file.  Specifically, this line of code seems to be triggering the error that is printed (https://github.com/svn2github/staden-io_lib/blob/master/trunk/io_lib/bam.c#L300).  This suggests something is awry with the BAM file / header.  While I can't see anything immediately problematic from the snippet of the header you posted above, I do see some curious things even in this short region of the header.  Specifically, the first transcript `NC_003070.9:0-30427671`, appears to be > 30 million nucleotides long --- this is a very suspicious length for a transcript.  Second, the second and third transcripts appear to be exact duplicates.  Though that is not an inconsistency itself, there is no benefit to having a transcript present multiple times and it can adversely affect quantification estimates.  Are there any details about how the reference was obtained (or the BAM file created) that might shed light on why the BAM parser finds such an inconsistency?

**Comment by rob-p** [comment]
Hi @sagnikbanerjee15, do you have any updates on this?

**Comment by rob-p** [comment]
I'm going to close this for now, since it seems there are no updates.  If there are any more details, we can reopen.
