### ISSUE TITLE
Usage of fldMean and fldSd

### ISSUE THREAD

**Issue by ECuris** [COMBINE-lab/salmon#127]
Asked from a colleague claiming it was better to use "correct" values (ie, given by the RNASeq platform) for fragment length distribution, I tried to use this option. However, I did not understood a few thing about them in the documentation, and could not figure out the answer from the code...
The documentation states that these options give the mean and standard deviation of a truncated normal variable used to model the distribution. However, it is not clear if they correspond of the (µ, sigma) parameters of the Gaussian that _will_ be truncated (as is usually given) or _after_ truncation, as is easy to estimate by sample mean and sample standard deviation. These values may be quite different, I guess, if truncation is indeed important.
From the code, I found that the values are stored in the fragLenDistMean and fragLenDistPriorSD slots of the SalmonOpts, and that their default values are 200 and 80. However, I could not find any place where these slots were used again (a grep on all .cpp files in src did not found any result except the lines in SalmonQuantify.cpp and SalmonQuantifyAlignments.cpp that seem to parse the command line options:
`    (
     "fldMean",
     po::value<size_t>(&(sopt.fragLenDistPriorMean))->default_value(200),
     "The mean used in the fragment length distribution prior")
    (
     "fldSD",
     po::value<size_t>(&(sopt.fragLenDistPriorSD))->default_value(80),
     "The standard deviation used in the fragment length distribution "
     "prior")
`
However, I do not use C++ so I may have missed something in the role of the `po` namespace.
Could you give any hint of where these values are used, so I can understand what is there exact meaning?
Thanks in advance

**Comment by ECuris** [comment]
Edit: I've found finally where the slots are used, it's in the templates in the include folder, right? The comments only speak of a Gaussian, so I guess the values to give are for the Gaussian before any truncation, right?

**Comment by rob-p** [comment]
Hi @ECuris,

  Yes, the values you give are used to form a normal distribution, which is then truncated on the left at 0.  So, the parameters you provide are the mean and standard deviation of the distribution *prior* to truncation.  However, I'll note that the values are such that 0 is usually sufficiently far (in terms of standard deviations from the mean) that the mean and standard deviation of the fragment length distribution are very similar before and after the 0 truncation.  Finally, I'll mention that, if you have paired-end reads, Salmon will *always* learn the empirical fragment length distribution (since the experiment, itself, is the best estimator of the true distribution), but the `--fldMean` and `--fldSD` parameters define the prior distribution that is updated with observed fragment lengths.

**Comment by ECuris** [comment]
Thanks. I have single-end reads.
For instance, with the default values in Salmon, µ=200 and sigma=80, after truncation at 0 the real experimental mean would be (if I computed correctly) µ*  ~ 201 and the real experimental standard deviation would be sigma* ~ 78, so indeed the difference would probably not matter.

Since it is a prior, do you have any idea of the importance of giving these values on the posterior distribution and hence the final results? What would be the consequences of giving a (too false) prior ? From which value may we expect really different results than the ones obtained with the defaults?
Thanks,

**Comment by rob-p** [comment]
@ECuris --- For single-end reads the prior *is* the posterior.  It is only possible to reliably estimate fragment lengths when one has paired-end reads, since with single-end reads one only has a single mapping fragment end, and hence cannot estimate the implied fragment size.  So, with paired-end reads, the prior values are largely unimportant (the data overwhelm them quickly), but with single-end reads, having a reasonable estimate of the fragment length mean and standard deviation is important, because the effective lengths of the transcripts will be derived from these values.

**Comment by ECuris** [comment]
Hi,
Still investigating around fragment length distributioin, I've noticed a potential discordance between code and doc: in code, in SalmonQuantify.cpp, default values are suggested to be 200 for mean and 80 for standard deviation:
`(
     "fldMean",
     po::value<size_t>(&(sopt.fragLenDistPriorMean))->default_value(200),
     "The mean used in the fragment length distribution prior")
    (
     "fldSD",
     po::value<size_t>(&(sopt.fragLenDistPriorSD))->default_value(80),
     "The standard deviation used in the fragment length distribution "
     "prior")`
However, when calling salmon's help with salmon quant --help-reads, it says
`  --fldMean arg (=250)                  The mean used in the fragment length distribution prior
  --fldSD arg (=25)                     The standard deviation used in the fragment length distribution prior`
which suggests different defaults — or something I did not understood in the code, which is quite possible also.
In fact, a `grep 250 */*` in the salmon source directory does not retrieve any meaningful answer (250 only seems to appear as a set of digits in floating point numbers), and a `grep 25 */*` does not seem to give either a significant result (but where are a lot of 255, 256… so I may have missed it).
Could you confirm what are the true default values and how they are obtained, if there is any trick I missed?
Thank you very much in advance, and sorry for the slow understanding…

**Comment by rob-p** [comment]
Hi @ECuris,

  Indeed, this seems to be a case where the code evolved and the documentation has yet to catch up.  The defaults are `fldMean` = 250 and `fldSD` = 25.  The relevant code is here (https://github.com/COMBINE-lab/salmon/blob/master/src/SalmonQuantify.cpp#L2260).  This defines how default values are set for these parameters.  I'll make a note to update the documentation to be consistent with these changes (which were made to be more in line with modern protocols, though there's still no good universal parameters for things that can vary so widely between experiments).

**Comment by ECuris** [comment]
Hi,
Thanks. Indeed, it is a very recent change in the code, and I was on the old code.
By the way, it does not seem to change very much the results. I'm quite new on RNA-Seq, but is it expected to have huge effects and be really important, or to have only side effects that are difficult to distinguish from all other kinds of uncertainties in the method itself?

**Comment by Tima-Ze** [comment]
Hi all,
What if I have a single-end RNA-seq data without any information about fragment length. Is there any way to use salmon to quantify these reads?  Is --fldMean and --fldSD options vital for running salmon in both alignment-base and mapping-based mode?

**Comment by rob-p** [comment]
Hi @Tima-Ze,

  Yes, salmon can be used to quantify these reads, but the results will depend (somewhat) on the `--fldMean` and `--fldSD` flags that are used.  It's important to note that this is not a unique characteristic of salmon, and any transcript-level quantification tool using a probabilistic model (e.g. RSEM, eXpress, BitSeq, etc.) have the same requirement.  That is, the fragment length distribution should be known so that _effective_ transcript lengths can be estimated, which have an effect on fragment assignment probabilities.  If the wrong fragment length distribution is specified, then the _effective_ transcript lengths will be off and this can affect the assignment of some fragments.  This is only a requirement with single-end reads, since with paired-end reads the fragment length distribution is learned from the data.  Further, the inference procedure is somewhat robust to these choices (small changes in fld mean and sd don't generally lead to drastically different results).  If you have access to the BioAnalyzer results for the sequencing run, those can give information about the fragment length distribution (even in a single end experiment).  If not, you can proceed with the default values.  Even if they don't exactly match the true distribution in the single-end sample, at least the same values will be applied in all samples and so, ideally, most results of misspecification will wash out in subsequent differential analysis.  

Finally, it's worth noting that the same restriction holds in both alignment-based and mapping-based modes.  This is because in neither mode do single-end fragments provide sufficient information to estimate the fragment length distribution from the data.  We only know where one end of a fragment mapped and cannot infer where the other end would be.  This is not an alignment versus mapping (versus selective-alignment) issue, but rather is fundamental to having only observed one side of the entire fragment generated during fragmentation and prior to sequencing.  You cannot know the length of a fragment given only a read from one of its ends.

Best,
Rob

**Comment by Tima-Ze** [comment]
Thanks @rob-p for a quick and complete reply. I got your point :) Actually, I downloaded fastq files from ENA so I do not have access to BioAnalyzer results. From literature review it could be concluded that Alignment-free tools like Salmon or kallisto yield more accurate quantifications, that's why I went to apply salmon on my data (my aim is differential gene expression at the end). Now, my main issue is: without an accurate estimation of  fragment length for running salmon, would it  end up with less accurate quantification result? If yes, then it is more rational to me to use traditional methods such as featureCounts. Do you have any idea that sheds more light on this ambiguity.
Best,
Tima

**Comment by rob-p** [comment]
Hi @Tima-Ze,

  I’m glad to hear you’re actually thinking of these considerations.  It’s good to think about how data processing choices may affect your results and you are being thoughtful here.

  I wouldn’t say that, generally, alignment-free tools are more accurate than alignment-based ones.  For example, you might look at our recent paper on how [alignment and mapping methodology can influence abundance estimation even when holding the quantification approach fixed](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02151-8), or [this paper on the corner cases of alignment-free methodology](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4869-5) (note the second paper pre-dates the first, and the new selective-alignment methodology in salmon should largely address the issues raised in that paper).  However, the bigger and more meaningful distinction is between methods that attempt to properly quantify abundance (generally using a generative statistical model) — including methods like RSEM, BitSeq, salmon, etc., and those that try to simply count aligned reads — including methods like HTSeq and featureCounts.  Generally, the former type of methods are more accurate than the latter at both the gene level and the former can also offer transcript-level estimates if desired (counting based methods generally cannot).

  Finally, to your question more directly, I don’t believe that model misspecification that may result due to not knowing the fragment length distribution will generally have enough of a deleterious effect on the probabilistic quantification methods to degrade their performance to the level of counting based methods.  I would still argue to prefer probabilistic quantification (i.e. salmon) to read counting, even if you don’t know the fragment length distribution.  As I mentioned above, it may change the maximum likelihood estimates a bit, but should do so across all samples, hopefully minimizing the downstream effects on differential analysis.  Good luck with your analysis!

Best,
Rob

**Comment by Tima-Ze** [comment]
I really appreciate your help, I have been struggling with this over last few weeks and I really felt stuck :)) I have read some other papers but I should take a look at above mentioned ones.
Thank you and Merry Christmas :) 
Tima
