### ISSUE TITLE
Errors when installing from source

### ISSUE THREAD

**Issue by mmccarthy781** [COMBINE-lab/salmon#139]
Hey all,

I'm currently attempting to install Salmon from source on a machine running Ubuntu 16.04.  I'm following along with the installation instructions (http://salmon.readthedocs.io/en/latest/building.html#installation); however, I am running into errors when running cmake:

    michael@thinkpad:/opt/salmon/salmon-0.8.2/build$ cmake -DFETCH_BOOST=TRUE
    CMake Error: The source directory "/opt/salmon/salmon-0.8.2/build" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.

I tried to fix the issue by moving CMakeLists.rxt from the parent directory into the build directory, but I was met with even more errors, I've attached the created CMakeError.log and CMakeOutput.log file

[CMakeOutput.txt](https://github.com/COMBINE-lab/salmon/files/1109023/CMakeOutput.txt)
[CMakeError.txt](https://github.com/COMBINE-lab/salmon/files/1109022/CMakeError.txt)

I'm thinking that this may be a simple issue that I've overlooked as I'm new to Linux, and installation using CMake is new to me.

**Comment by rob-p** [comment]
From within the build directory, the command would be 

```
cmake -DFETCH_BOOST=TRUE ..
```

The command you posted is missing the `..`.

**Comment by mmccarthy781** [comment]
Thanks for the assistance, that was the issue!  I knew it was a small problem.

**Comment by RoebideBruijn** [comment]
I have the same issue. But doing 'cmake -DFETCH_BOOST=TRUE ..' or 'cmake ..' gives the same error message 'does not appear to contain CMakeLists.txt'. I downloaded version 'salmon-0.12.0_linux_x86_64'.

**Comment by RoebideBruijn** [comment]
Hi Rob,

I'm running from the empty directory 'build'. The cmake file and folder are not there. 

I downloaded here https://github.com/COMBINE-lab/salmon/releases: salmon-0.12.0_linux_x86_64.tar.gz. Unpacked it. Went into directory 'salmon-0.12.0_linux_x86_6'. Created new dir build/ (same level as bin and lib). Installed cmake with sudo apt-get. Attempted to run cmake from build/. 

If I just type 'cmake':
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

So it looks installed I would think.

**Comment by RoebideBruijn** [comment]
@hiraksarkar: it says 'CMake Error: The source directory "<>/salmon-0.12.0_linux_x86_64" does not appear to contain CMakeLists.txt. Specify --help for usage, or press the help button on the CMake GUI.'

**Comment by rob-p** [comment]
Hi @RoebideBruijn,

  It looks as though you downloaded the file that contains the pre-compiled release (https://github.com/COMBINE-lab/salmon/releases/download/v0.12.0/salmon-0.12.0_linux_x86_64.tar.gz), rather than the source code (https://github.com/COMBINE-lab/salmon/archive/v0.12.0.tar.gz).  In that case, you need not (and can't) compile the already compiled binary.  There is an executable named `salmon` in the `bin` subdirectory that you should be able to run directly (assuming you are in Linux).

**Comment by rob-p** [comment]
Hi @RoebideBruijn,

  It looks as though you downloaded the file that contains the pre-compiled release (https://github.com/COMBINE-lab/salmon/releases/download/v0.12.0/salmon-0.12.0_linux_x86_64.tar.gz), rather than the source code (https://github.com/COMBINE-lab/salmon/archive/v0.12.0.tar.gz).  In that case, you need not (and can't) compile the already compiled binary.  There is an executable named `salmon` in the `bin` subdirectory that you should be able to run directly (assuming you are in Linux).

**Comment by RoebideBruijn** [comment]
Thanks! Using that works.

**Comment by rob-p** [comment]
Great; thanks for letting us know :) .
