### ISSUE TITLE
More standard --version output please

### ISSUE THREAD

**Issue by tseemann** [COMBINE-lab/salmon#148]
Current:
```
% salmon -v
version : 0.8.2
```
Desired GNU-like behavior:
```
% salmon -v
salmon 0.8.2
```

ie. NAME - SPACE - VERSION

**Comment by rob-p** [comment]
This is resolved in develop and will make it into the next release.

**Comment by Miserlou** [comment]
Related to this: `--version` output goes to standard err, rather than standard out, which is confusing during scripting. Other than `javac` and `python2.7` (fixed in 3.4+), I don't know of any other programs which print `--version` to `stderr` rather than `stdout`.

**Comment by tseemann** [comment]
Yes I agree, `--help` and `--version` should go to `stdout` as the user requested them.

Having packaged >200 tools into Homebrew, I can tell you that it's roughly 70% don't have --version, 15% go to stdout, and 15% go to stderr !

**Comment by rob-p** [comment]
I've addressed this in a recent [commit](https://github.com/COMBINE-lab/salmon/commit/05859ef8412687be14de5084f3b1e0e688fb3e76).  Now, `version`, `help`, `cite` and `swim` will print to stdout, while other normal logging messages will print to stderr.  Basically, if it was specifically requested by the user, send it to stdout; otherwise send it to stderr.

**Comment by tseemann** [comment]
Thanks @rob-p  
This pedant will exit now :)
