### ISSUE TITLE
excessive output of "couldn't dequeue read chunk"

### ISSUE THREAD

**Issue by alexvpickering** [COMBINE-lab/salmon#152]
I was running some quantification on Google Compute Engine and a particular study repeatedly printed "couldn't dequeue read chunk" for 2.5 days. By the time I discovered it, over 300GB of Egress traffic (sending the message to my local computer) had accumulated. Cost me close to $100 between Google's egress charges and my ISPs bandwidth overage charges.

It would be nice if the message didn't print so much. I'm now running Salmon commands with `timeout 1h`  prefix to prevent this but might run into an issue with 1 hour not being long enough for all quantification runs.

**Comment by rob-p** [comment]
Holy cloud-computing charges!  I'm sorry to hear about this.  We can certainly rate-limit this message.  I'll work on fixing this upstream.  Sorry for the trouble.

**Comment by alexvpickering** [comment]
Thanks Rob - not a worry.

**Comment by rob-p** [comment]
These messages have been removed in 0.9.0.  Also, the read parser has had a considerable overhaul to avoid simply busy waiting in a situation like this where the processing is much slower than the disk.  Let me know if this problem is resolved on your end.

**Comment by alexvpickering** [comment]
Thanks Rob - haven't had the message pop up in the last few days. All seems to be running smoothly. Thanks again!

**Comment by rob-p** [comment]
You're very welcome!  Sorry for the console spam in the first place; I wasn't anticipating usage scenarios with that type of imbalance between producers and consumers.  My guess is that the newest version of Salmon will also consume slightly less user-time as well, since now the parsing thread will backoff rather than busy wait when it wants to produce more reads for consumption.
