### ISSUE TITLE
Shuffling of reads still needed?

### ISSUE THREAD

**Issue by tobi-te** [COMBINE-lab/salmon#155]
Hi,
in your documentation, you clearly state that salmon expects a "random" order of reads and you suggest to shuffle the read files.
In my experiments, I created a set of unshuffled and shuffled .bam files (using samtools bamshuf). The resulting quant.sf files always were exactly identical.

Is shuffling not longer needed (or probably never was for .bam files)? Or has salmon a built-in shuffling function?

Cheers,
Tobi

**Comment by k3yavi** [comment]
Hi @tobi-te ,
Salmon is a two-phase algorithm i.e. online and offline. The first phase i.e. online-phase learns various parameters before starting the offline-phase (order doesn't matter). Like most online learning algorithm Salmon also expects the input to be randomized enough to avoid bias or in the case of Salmon *possibly* nudge the offline-phase towards a local-minima, which can vary according to the data (not always). I think in your case even though the learnt online parameters are biased (because of non-random order) the estimated abundances at the end are corrected by the offline-phase pretty well and you are observing the similar results.

**Comment by rob-p** [comment]
Hi @tobi-te,

  Just to add to @k3yavi's answer --- the only time the shuffling of the BAM file would be required is if the alignments are sorted by location.  In that case, you will bias the online phase (just as @k3yavi  suggests because of the order in which you observe reads mapping to certain transcripts).  However, if you started with regular FASTQ files (which generally have reads in a random order), and aligned those reads without sorting the output alignments by position, then your .BAM file will already have alignments in a random order (and will already be compatible with Salmon's alignment-based mode).
