### ISSUE TITLE
Discrepancies in the transcript quantification results with -g flag?

### ISSUE THREAD

**Issue by mukarram-ak** [COMBINE-lab/salmon#169]
Hello,

I'm trying to quantify the expression of both genes and transcripts using Salmon. The fasta file was generated by `gffread` tool using flag `-w` (spliced). 

Everything is running fine, except I notice some differences in the transcript quantification (quant.sf) between using `-g` option and not using it (the fasta file was generated from the same gtf provided to `-g`). Is this normal (I guess this is somehow expected as some reads can map to the introns when `-g` option is provided)? If I want to quantify both genes and transcripts, for the transcript quantification, which one I should use?

Thanks,
Kadir

**Comment by rob-p** [comment]
Hi Kadir,

  How significant are the differences?  There is a stochastic component to the algorithm, so one would not generally expect identical results between runs.  However, differences should be small.  The use of the `-g` flag should not affect transcript level inference, since the aggregation to gene-level abundances is done post-facto (i.e. after all transcript-level abundances have been estimated).  Nonetheless, [tximport](https://bioconductor.org/packages/release/bioc/html/tximport.html) is the recommended way to aggregate transcript-level inferences to the gene level.  The `-g` option predates the existence of that package and exists mostly for backward compatibility.

**Comment by mukarram-ak** [comment]
Hi Rob,

Thanks for your prompt answer. My bad, it was because one of the runs was having `--fldMean 200 --fldSD 20` flags, hence the discrepancies. You were right, the differences are really small with the same exact commands. 

About tximport, would the result differ from having `-g` flag with Salmon? I have indeed read that tximport is more recommended way to quantify genes, but I assume `-g` flag should be doing the same thing?

**Comment by rob-p** [comment]
Hi Kadir,

  So, the short answer is that on a _single sample_ the `-g` flag and `tximport` do something very similar.  However, the real benefit of `tximport` is that it has access to _all_ of the samples when doing transcript to gene-level aggregation.  

So, while Salmon with the `-g` flag will estimate the average expressed gene length in each sample, `tximport` will also have knowledge of how the average gene length varies across all samples.  Also, `tximport` provides a few different options for how, exactly, you wish to aggregate.  Generally, the `-g` option is completely reasonable, but `tximport` is the same in the simple case and better in the general case.

**Comment by mukarram-ak** [comment]
Hi Rob,

Many thanks for your answer! Good to know that the results of `-g` should be more or less the same with `tximport`. I will give `tximport` a shot then.
