### ISSUE TITLE
Installing Salmon

### ISSUE THREAD

**Issue by RK489** [COMBINE-lab/salmon#172]
Hi, 

I'm new to RNA seq and trying to use Salmon to analyse my dataset. However, it gives an error when I try to run it after downloading the package: 

` ~/Downloads/Salmon-0.8.2_macOX_10.12/bin/salmon`

It gves the following error: 

`dyld: Library not loaded: @rpath/libtbbmalloc_proxy.dylib
  Referenced from: /Users/rishika/Downloads/Salmon-0.8.2_macOX_10.12/bin/./salmon
  Reason: image not found
Abort trap: 6`

I would be grateful for your help. Thanks!

**Comment by rob-p** [comment]
Hi @RK489,

  It seems it cannot find the library it wants.  The easiest solution is to install salmon on OS X [using bioconda](https://anaconda.org/bioconda/salmon).  Otherwise, you can also try to explicitly make sure that path is being searched via e.g.:

`DYLD_FALLBACK_LIBRARY_PATH=/Users/rishika/Downloads/Salmon-0.8.2_macOX_10.12/lib ~/Downloads/Salmon-0.8.2_macOX_10.12/bin/salmon -h`

Please let me know if either of these solutions works for you.

Best,
Rob

**Comment by RK489** [comment]
Hi Rob,

The command worked for me, thanks a lot!

Best,
Rishika
