### ISSUE TITLE
libtype SF interpreted as unstranded

### ISSUE THREAD

**Issue by wdecoster** [COMBINE-lab/salmon#177]
I'm quantifying reads from a Lexogen QuantSeq experiment, using `-l SF and --noLengthCorrection`. I just downloaded the latest release 0.9.0.

Full command (using nu parallel)
`salmon quant -i path_to_index -r {} -l SF --noLengthCorrection  -o {.} -p 5`

Which gives the following settings information:
```
Version Info: This is the most recent version of Salmon.
### salmon (mapping-based) v0.9.0
### [ program ] => salmon 
### [ command ] => quant 
### [ index ] => { /home/wdecoster/databases/Homo_sapiens/hg38/transcriptome/GRCh38-full-transcriptome-index }
### [ unmatedReads ] => { pt_d10046-11.fastq.gz }
### [ libType ] => { SF }
### [ noLengthCorrection ] => { }
### [ output ] => { pt_d10046-11.fastq }
### [ threads ] => { 5 }
```

But I get the following warning for each sample:
`Detected a *potential* strand bias > 1% in an unstranded protocol check the file: samplename/lib_format_counts.json for details`

That file looks as below:

```
{
    "read_files": "pt_d10040-14.fastq.gz",
    "expected_format": "U",
    "compatible_fragment_ratio": 1.0,
    "num_compatible_fragments": 2836170,
    "num_assigned_fragments": 2836170,
    "num_consistent_mappings": 10375916,
    "num_inconsistent_mappings": 0,
    "strand_mapping_bias": 0.9229587055253724,
    "MSF": 0,
    "OSF": 0,
    "ISF": 0,
    "MSR": 0,
    "OSR": 0,
    "ISR": 0,
    "SF": 9576542,
    "SR": 799374,
    "MU": 0,
    "OU": 0,
    "IU": 0,
    "U": 0
}
```

This suggests my libType SF is ignored?

(Less important: If you could make --libtype an alias for --libType that would be great, random internal capitalization is quite annoying imho)

**Comment by rob-p** [comment]
Hi @wdecoster,

  Thanks for reporting this.  One restriction that needs to be better documented (actually, I have to make sure it is properly documented at all!) is that the library type should come _before_ the reads they describe.  That is, you should consider passing `-l SF -r {}` rather than `-r {} -l SF`.  The reason for this is that the `-r` and `-1,-2` parameters are repeatable so you could, conceivably, pass multiple reads of different library types.  However, this is a feature that nobody uses and frankly doesn't make too much sense (so I'll consider removing it in the future to simplify library type parsing).  For the time being, I'll also consider printing a warning message when a read file is encountered without an explicitly pre-defined library type (in that case, the behavior, as you saw,  is to assume an unstranded library).  Could you let me know if passing `-l` before `-r` resolves the issue for you.

  As to your other suggestion.  The internal capitalization rules follow those for camel-case naming of variables (as opposed to separating words with`_`).  However, I realize this is somewhat esoteric and even among those who are familiar with such conventions, an arbitrary preference.  I'll look into aliasing this flag (and maybe others) to be usable with different names as well.  I just have to check how to do this (and if it is possible) with boost's program options.

**Comment by wdecoster** [comment]
Hi @rob-p,

Thanks for the quick reply. Passing -l before -r indeed solves the issue.

Checking the manual again it turns out that there is indeed a note about the order of the arguments, but having read the manual months ago I conveniently skipped the text and went straight to what I needed... Oops! I guess a warning could save some confusion for now. 

Cheers,  
Wouter
