### ISSUE TITLE
Exception : [Failed to read 8 bytes from input stream! Read 0] salmon quant was invoked improperly

### ISSUE THREAD

**Issue by NLSVTN** [COMBINE-lab/salmon#180]
I am having a real trouble running salmon on a cluster. Here the issue is documented:

https://bioinformatics.stackexchange.com/questions/3061/exception-failed-to-read-8-bytes-from-input-stream-read-0-salmon-quant-was

**Comment by rob-p** [comment]
Hi @NLSVTN,

  I've been following the discussion of this problem over on the [bioinformatics stack exchange](https://bioinformatics.stackexchange.com/questions/3061/exception-failed-to-read-8-bytes-from-input-stream-read-0-salmon-quant-was).  It looks like this issue is resolved.  Does the new issue you are facing involve Salmon?

Thanks,
Rob

**Comment by NLSVTN** [comment]
That is fine and the issue should be closed.

Thank you!

**Comment by rob-p** [comment]
Great; thanks for the quick response!
