### ISSUE TITLE
Gene quantification does not work with Ensembl v.91 human GTF file

### ISSUE THREAD

**Issue by amaer** [COMBINE-lab/salmon#198]
I ran salmon quant -p 6 -i refs/Homo_sapiens_GRCh38_91_quasi_index -l ISF -1 <(zcat RD1_R1_001.fastq.gz) -2 <(zcat RD1_R2_001.fastq.gz)  -o test_salmon_quant -g refs/Homo_sapiens.GRCh38.91.gtf
(...)
I am getting a bunch of warnings like:
 [warning] couldn't find transcript named [ENST00000619185.1] in transcript <-> gene map; returning transcript as it's own gene

And in the end, there isn't a single ENSGxxxx Ensembl gene id in the quant.gene.sf file.
The gtf file was downloaded from Ensembl ftp site ftp://ftp.ensembl.org/pub/release-91/gtf/homo_sapiens.  

I noticed the format of the gtf files from Ensembl v.75 and 91 are different; they have added gene_version  between gene_id and transcript_id, and transcript_version.

Homo_sapiens.GRCh37.75.gtf:8	protein_coding	transcript	26247878	26268564	.	+	.	gene_id "ENSG00000104765"; transcript_id "ENST00000518611"; gene_name "BNIP3L"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "BNIP3L-004"; transcript_source "ensembl_havana";

Homo_sapiens.GRCh38.91.gtf:8	havana	transcript	26390362	26411048	.	+	.	gene_id "ENSG00000104765"; gene_version "15"; transcript_id "ENST00000518611"; transcript_version "5"; gene_name "BNIP3L"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "BNIP3L-202"; transcript_source "havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS83267"; tag "basic"; transcript_support_level "2";

**Comment by rob-p** [comment]
Hi @amaer,

  The warning suggests that the gff parser cannot even find a transcript with the given name (in the example you provided `ENST00000619185.1`).  Does such a transcript exist?  Can you grep for it.  The string must match exactly (version number and all).  The gff-based parser to do the transcript to gene mapping is quite picky, as gff & gtf files are often quite ill-formed.  My top suggestion would be to do transcript -> gene abundance aggregation using [tximport](https://bioconductor.org/packages/release/bioc/html/tximport.html).  The other option is to provide Salmon with a TSV mapping the transcripts to genes, as this eliminates all of the parsing problems (at the cost of pawning them off on the user, who must parse the questionable gtf file).  However, tximport is the recommended strategy, since it can perform average gene length normalization across multiple samples (rather than just per-sample), which is useful for downstream DE.

**Comment by amaer** [comment]
Hi Rob,

I checked the cdna.fa files I downloaded from Ensembl and indeed there is a difference.  In Ensembl v.75 the version number was not included in the fasta header, in v.91 it is.
e.g. 

grep ENST00000518611 *cdna.ncrna.fa
Homo_sapiens.GRCh37.75.cdna.ncrna.fa:>ENST00000518611 cdna:novel chromosome:GRCh37:8:26247878:26268564:1 gene:ENSG00000104765 gene_biotype:protein_coding transcript_biotype:protein_coding
Homo_sapiens.GRCh38.91.cdna.ncrna.fa:>**ENST00000518611.5** cdna chromosome:GRCh38:8:26390362:26411048:1 gene:ENSG00000104765.15 gene_biotype:protein_coding transcript_biotype:protein_coding gene_symbol:BNIP3L description:BCL2 interacting protein 3 like [Source:HGNC Symbol;Acc:HGNC:1085]

while in the gtf file the transcript_id is still ENST00000518611 and version transcript is indicated separately.

The gtf file does not have transcript_id  ENST00000518611.5. just ENST00000518611.

I don't mind parsing the gtf file to a tsv mapping. If I want to use a tsv file, what should be its format - just 2 columns - first one with transcript ID (just as it appears in the fasta file - in this case ENST00000518611.5) , second one with the gene ID?

Thanks!

**Comment by rob-p** [comment]
Hi @amaer ,

  Yes, exactly.  The input is a simple TSV where the first column is transcript names and the second column is the gene names (note, that the keys in column 1 are unique, but that many transcripts can map to the same gene).  This is the same type of input accepted by tximport to do the transcript => gene mapping.

Best,
Rob
