### ISSUE TITLE
Using gcBias and seqBias options takes much longer than a couple minutes

### ISSUE THREAD

**Issue by amaer** [COMBINE-lab/salmon#201]
Hi Rob,

I have run salmon quant without any bias corrections and it ran like in a minute (-p 20, 17 million pairs 150-bp  ISF library) against Ensembl human transcriptome. Amazing!
However, when I added --seqBias --gcBias the run time increased dramatically to about 15', which is much more than I expected. Is this expected behavior? Can it be sped up ? Compromise? Any recommendations?
I would like to be able to correct for (most) of the biases and run this in a batch mode, with many samples so time is important. 

Thank you very much,
Andrea

**Comment by rob-p** [comment]
Hi Andrea,

  The bias correction time depends on the number of expressed transcripts.  There is a flag to speed it up `--biasSpeedSamp`.  It takes a value by which to downsample the fragment length pmf for bias modeling.  The larger this number, the faster bias correction will become.  The default is 1, and is super conservative (we are probably going to make the default 5 in the next release because it is much faster with no real difference in modeling quality).  In fact, values up to at least 10 seem to work quite well with respect to the baseline.  So, I'd recommend testing this parameter on a sample until you are happy with the speed, and then using that on all samples.  Let me know how it goes, and if my description makes sense.

Best,
Rob

**Comment by amaer** [comment]
Thank you very much Rob, that was a great improvement, to less than 5' run time with --biasSpeedSamp 5! Yes it definitely made sense.

**Comment by mikelove** [comment]
Can confirm, just did a sensitivity analysis and the value of 5 is just as accurate a bias correction as 1. Makes sense to switch the default to 5.
