### ISSUE TITLE
Error generating index.

### ISSUE THREAD

**Issue by ogreyesp** [COMBINE-lab/salmon#224]
Hello, I'm trying to generate an index from a transcriptome, that was generated by StringTie, with salmon, but I'm getting the following error.  What could be the problem?

# salmon index -t /home/...out.gtf -i /home/...salmon-index

Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
[2018-05-23 10:37:53.715] [jLog] [info] building index
RapMap Indexer

[Step 1 of 4] : counting k-mers
Elapsed time: 0.0602932s

Replaced 0 non-ATCG nucleotides
Clipped poly-A tails from 0 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 3.7924e-05s
Writing sequence data to file . . . done
Elapsed time: 1.7461e-05s
[info] Building 32-bit suffix array (length of generalized text is 0)
Building suffix array . . . FAILURE: return code from libdivsufsort() was -1

**Comment by rob-p** [comment]
Hi @ogreyesp,

  The problem is that you cannot provide a gtf directly to salmon for indexing.  Salmon accepts a FASTA file of the transcriptome.  To extract the StringTie assembled transcripts from the genome, you need to use the GTF file you have and the genome FASTA, along with a tool like `gffread`  or `rsem-prepare-reference`.  These tools both take a genome FASTA file and a GTF file, and extract a transcriptome FASTA from them.  Once you have the transcriptome FASTA file, you can index that with salmon.

**Comment by ogreyesp** [comment]
Thanks a lot for your help.!
