### ISSUE TITLE
2 questions: Salmon binary + QC (tool/script)

### ISSUE THREAD

**Issue by guidohooiveld** [COMBINE-lab/salmon#252]
Hi,
I don't want to report a bug, but rather have 2 (unrelated) questions:
Because we don't generate that many RNA-seq data sets, I am using Salmon every now and then. I really like the program (speed!) and the obtained results.

- Since I don't use Salmon on a daily basis, I usually have (would like) to update Salmon to its latest release. For these the binaries you (used to) provide are very convenient. I noticed that these are not explicitly linked to anymore on the page `https://github.com/COMBINE-lab/salmon/releases`, although these still are available through [this link](https://github.com/COMBINE-lab/salmon/files/2099291/salmon-latest_linux_x86_64.tar.gz) that is regularly posted on this Github 'forum'. Please note that I learned you favor the Bioconda route for keeping Salmon up to date. Nevertheless, provided it doesn't take too much effort, I would appreciate it very much if you could still make the binaries available.

- My 2nd question has to do with some basic QC-ing: I am currently analyzing a set of 96 mouse samples. While running Salmon, I noticed most samples do have a nice percentage of mapped reads (>80%), but I also noticed that for samples this percentage was much lower (<50%).
Q: Is there an easy way of obtaining these numbers ("percent_mapped") for all samples that were mapped in a Salmon run (without manually reviewing all 96 samples the 'meta_info.json' file)? In other words, how to obtain an 'overall log file'?

Thanks,
Guido

**Comment by rob-p** [comment]
Hi @guidohooiveld,  

Regarding your questions:

  (1) The motivation behind asking users to use Bioconda to install the binary is to limit the number of variables we may encounter when someone is reporting a bug --- i.e. if there are fewer distribution channels there is less maintenance overhead.  Nonetheless, as you can see, I've had to make the binary available anyway, because it was the only way some people could easily get the program.  Therefore, I think I'll start attaching binaries to releases again.

  (2) Yes, though this functionality is not part of Salmon itself.  I *highly* recommend the [MultiQC](http://multiqc.info/) tool.  MultiQC has a salmon module, which will parse all of the salmon log files in an experiment directory and produce a report.  This report will contain the mapping percentages for all of the samples extracted from the salmon logs (and will color them nicely).  It will also produce other QC information from the salmon runs.  We are currently working on an improved multi-QC module, which will also provide summaries for things like GC / seq bias by analyzing the models that salmon learns, but this module isn't yet complete.

Best,
Rob

**Comment by guidohooiveld** [comment]
Thanks Rob!
For both providing the binary download again, and pointing me to MultiQC (meanwhile got a informative QC report). :)
Guido
