### ISSUE TITLE
Compilation issues salmon 0-11-1

### ISSUE THREAD

**Issue by juugii** [COMBINE-lab/salmon#263]
Hello,

Compilation bug
Trying to compile latest source code of salmon 0.11.1 (git fetched) on CentOS 7

With:
CXX=/usr/bin/clang++
CC=/usr/bin/clang
/usr/bin/clang --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix

/path/to/cmake/cmake-3.11.4/cmake-3.11.4-Linux-x86_64/bin/cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBoost_NO_BOOST_CMAKE=BOOL:ON -DBOOST_LIBRARYDIR=/path/to/.local/boost/boost-1.67.0/lib -DBOOST_INCLUDEDIR=/path/to/.local/boost/boost-1.67.0/include -DCMAKE_INSTALL_PREFIX=/path/to/.local/salmon/salmon-0.11.1 ..

boost 1.67 containing all default 113 libraries

Error:
Many warnings and fatal errors, including
warning: unknown warning option '-Wno-unused-local-typedefs' [-Wunknown-warning-option]
In file included from /path/to/downloads/salmon/src/edlib.cpp:4:
/path/to/downloads/salmon/include/edlib.h:4:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
warning: unknown warning option '-Wno-unused-local-typedefs' [-Wunknown-warning-option]
In file included from /path/to/downloads/salmon/src/AlevinUtils.cpp:1:
/path/to/downloads/salmon/include/AlevinUtils.hpp:4:10: fatal error: 'algorithm' file not found
#include <algorithm>
warning: unknown warning option '-Wno-unused-local-typedefs' [-Wunknown-warning-option]
In file included from /path/to/downloads/salmon/src/jellyfish/mer_dna.cc:18:
/path/to/downloads/salmon/include/jellyfish/mer_dna.hpp:27:10: fatal error: 'iostream' file not found
#include <iostream>
/path/to/downloads/salmon/include/eigen3/Eigen/Core:66:12: fatal error: 'new'In file included from  file /path/to/downloads/salmon/src/LibraryFormat.cpp not :found
1:
/path/to/downloads/salmon/include/LibraryFormat.hpp:  #include <new>4:10:

Best,
juugii

**Comment by rob-p** [comment]
Hi,

  Juugii,  the problem seems to be stemming from the fact that, although you are using clang, you don't have lib++, or the development headers it provides installed.  Thus, clang is failing to find the basic c++ library includes that it needs.  The easiest way to get salmon is to install the latest version for Linux via Bioconda, or to use the docker image of the latest release (from dockethub) `combinelab/salmon:latest`, or, to download the pre-compiled Linux binary from the release page.  If you really wish to compile from source, you could try installing libc++ and the development directories or, perhaps more easily, switching your compiler to GCC.

**Comment by juugii** [comment]
Hi rob,
Thanks for the very fast and detailed answer. It is not trivial to use a recent GCC on CentOS 7, I was trying to work around with clang. I'll try to add libc++.
I have some issues with salmon-0.11.1 on both precompiled binaries or bionconda install, that's why I. I'll post as a separate issue.
