### ISSUE TITLE
Calculation of Alignment rates per cell

### ISSUE THREAD

**Issue by pophipi** [COMBINE-lab/salmon#274]
Hi, 
I am trying to calculate the alignment rate of each cellular barcode in the final expression matrix for downstream filtering. What is the best way to accomplish this with Alevin data? 

I am currently using the _filtered_cb_frequency.txt_ file from _--dumpBfh_ and dividing the sum of each cell barcode's row in the gene expression matrix by the corresponding value in _filtered_cb_frequency.txt._ I assumed that that file lists the number of filtered reads that alignment was attempted on for each cellular barcode.

Thanks!

**Comment by k3yavi** [comment]
Hi @pophipi ,
We are in process of documenting the details of these files generated by using flag `--dumpFeatures`.
However, for your use case of getting alignment rate, there are two ways to get it in Alevin system.

First you have to run Aleivn with the flag `--dumpFeatures` but since you have the file `filtered_cb_frequency.txt` I think you already have specified this flag in your run of the dataset. The relevant files you need for generating alignment rate would be following:

1. *filtered_cb_frequency.txt*: A *tsv* file with the first column as the Cellular Barcode(CB) id and the second column has the frequency of the CB after sequence correction.
2. *MappedUmi.txt*:  A *tsv* file with the first column as the Cellular Barcode(CB) id and the second column has the number of reads confidently mapped to the provided reference transcriptome.

Both the file should have same number of rows (i.e. CB), although the order can be different. To get the Alignment rate you might have to divide the value of each CB in the second file by the value in the first file i.e. the Number of mapped reads over total number of available reads for that CB.

The second and more easier way is (although version bounded i.e. if you have latest version of Salmon (v11.2)), then if you run alevin with `--dumpFeatures` flag it will also generate a file called `featureDump.txt`. This file has multiple feature entries although the relevant one (the alignment rate) in case of yours would be the first one.

Hope that helps. Let us know if you need more help.

**Comment by pophipi** [comment]
@k3yavi Thank you!
