### ISSUE TITLE
jemalloc version

### ISSUE THREAD

**Issue by outpaddling** [COMBINE-lab/salmon#288]
Why is salmon using a fork of jemalloc instead of the official release from the jemalloc project?

From CMakeLists.txt:
```
DOWNLOAD_COMMAND curl -k -L https://github.com/COMBINE-lab/jemalloc/arch
ive/5.1.0.tar.gz -o jemalloc-5.1.0.tar.gz
```
This seems to potentially conflict with
   ` find_package(Jemalloc)`
which might locate an installation from a different build.
I want to ensure a consistent installation across all of our systems, whether or not jemalloc has been installed separately.
Thanks,
    Jason

**Comment by rob-p** [comment]
Hi @outpaddling,

  The only point of pulling from the fork of jemalloc is only to ensure the stability of the URL / release tag.  That is, no modifications are made to the corresponding point release of jemalloc.  This is not necessarily true for _all forks_ (e.g. we used to rely on some files of a fork from BWA where some things were heavily modified, though that whole fork is no longer part of the build process).

Best,
Rob

**Comment by outpaddling** [comment]
Interesting...  So you're concerned that
[https://github.com/jemalloc/jemalloc/archive/5.1.0.tar.gz](https://github.com/jemalloc/jemalloc/archive/5.1.0.tar.gz)
could change at some point?  I'm not an expert on Github internals, but I would assume there are some  safeguards against changes to release distfiles.
Thanks,
   Jason

**Comment by rob-p** [comment]
While I definitely trust the jemalloc devs, I do know that such things are possible, as a release is simply associated with a tagged commit, which _can_ be changed via a forced update to the tags.  I know because, in my early days using git + GitHub, I did such a foolish thing.  So, while I'm sure that the jemalloc devs wouldn't change the file associated with a tag, and while there are safeguards (e.g. check that the file we get matches the SHA of what we expect), simply pulling from a fork is a convenient way to handle this "generally" (for packages not as production-quality as jemalloc, or where the developers might not have tagged a release corresponding to what we need).

I completely understand that you don't want to link against a standard jemalloc if we compile some strange version with custom modifications.  However, here, we simply want to use the vanilla jemalloc.  In fact, when salmon is built under bioconda, this is exactly what we do (we link against the conda jemalloc >= 5.1.0).

**Comment by outpaddling** [comment]
Thanks, I was good with linking against external jemalloc after your first reply.  Mainly interested in knowing the details of your concern, so thanks for elaborating.  We use pkgsrc for most of our CentOS installs, and now I feel safe using devel/jemalloc as a dependency.  We also use FreeBSD, and in this case, I just patched out the dependency altogether, since jemalloc is FreeBSD's default allocator.  Cheers!

**Comment by rob-p** [comment]
Great; thanks for taking the time to explain, and for understanding our (sometimes quirky) decisions.
