### ISSUE TITLE
Alevin: Incomplete gene-transcript mapping 

### ISSUE THREAD

**Issue by sarahhcarl** [COMBINE-lab/salmon#336]
Hi all,

I'm working on setting up alevin as part of a single-cell RNA-seq analysis pipeline, and I'm running into problems with the gene-transcript mapping. 

The issue is basically the same as in a previous thread [here](https://github.com/COMBINE-lab/salmon/issues/122#issuecomment-283473242), in which the Ensembl cDNA fasta file contains some noncoding transcripts that are not present in the corresponding GTF file. I am using Ensembl release 95 (ftp://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz and ftp://ftp.ensembl.org/pub/release-95/gtf/homo_sapiens/Homo_sapiens.GRCh38.95.gtf.gz).

In the case of Salmon it was suggested to just filter the gene-level quantification file after the fact; however, this isn't possible with Alevin, because it appears to enforce a complete mapping and to crash if it is incomplete. The only solution I can come up with is to manually identify which transcripts are not present in the GTF and filter them out of the fasta file before indexing, but this is really a pain and not a very reproducible solution (it would have to be re-done for every new version, etc.). I would suggest enabling the option to just not include transcripts that don't have a gene-level mapping; however, I'm also open to other suggestions.

Thanks for your help and for working on such a great tool!
Sarah

**Comment by k3yavi** [comment]
Thanks for reporting this @sarahhcarl . 
I do see the problem with the ensemble reference, but I feel the resolution is not very straightforward.
Basically, alevin works in two phases, mapping and quantification. If a transcript is present in mapping and we start to drop transcripts in quantification it might bias the end estimates. The problem would be in the upstream indexing, i.e. salmon has already indexed the transcript if given in the reference fasta, and would map reads to it. Our mapping algorithm can give different results based on the transcript in the reference, due to various filters applied in extracting good quality alignments. 

One solution is to remove the transcripts at all from the salmon indexing which we don't have gene mapping for, although it might bias the analysis in opposite direction that is allowing reads to pass through with uniquely mapped evidence instead when the reads should be multimapped based on the transcripts which are thrown away.

Hope this makes sense, I'll let you know if you come up with a better solution.

**Comment by sarahhcarl** [comment]
Hi @k3yavi ,

Thanks for the reply. In the meantime I am using the Homo_sapiens.GRCh38.95.chr_patch_hapl_scaff.gtf.gz annotation, which does contain all of the transcripts in the fasta file, as well as more noncoding transcripts - so the situation is actually reversed (more transcripts in the annotation than in the index), but it doesn't seem to complain. I do see the potential issue with biasing the quantification phase. I'm still not sure what is the best solution (besides having perfectly matching files, but Ensembl apparently doesn't do that! :/ ).

Cheers,
Sarah

**Comment by alexvpickering** [comment]
This issue is not only the case for ensembl, but also for gencode v29. Following the [tutorial](https://gist.github.com/k3yavi/c501705ed2d29b12b0d10cf78b3ed001), building an index from *ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.pc_transcripts.fa.gz* and *txp2gene.tsv* from *ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz* results in *ERROR: Txp to Gene Map not found for 98665 transcripts. ExitingNULL*

A suggested solution: have an option during building the index so that it will only include transcripts also present in a pre-generated txp2gene.tsv (what @sarahhcarl did manually).

**Comment by k3yavi** [comment]
Hey @alexvpickering ,
I agree, it does makes sense to index the transcript and gene relationship while creating the salmon indexing but I don't see how it solves this problem i.e. if the idea is to ignore the transcripts which doesn't having transcript to gene mapping then it may bias the analysis as we are considering lesser number of transcripts than known; having said that an argument about unknown splice junction can still be made.

regarding the link for `gencode_29`, may I ask what version of salmon you are using ? Because I just tried to run alevin with the links you forwarded and it works fine for me. If possible forwarding the log will help too.

**Comment by alexvpickering** [comment]
Hey @k3yavi,
salmon version is 0.13.1. I don't have the logs at the moment as I am trying the ensembl-based solution suggested by @sarahhcarl using Homo_sapiens.GRCh38.94.chr_patch_hapl_scaff.gtf.gz and equivalent ensembl version for cdna index.

What about instead of filtering the index based on txp2gene, having some way of padding missing transcripts in txp2gene (e.g. just mapping from the indexes ENST to the same ENST)? I don't understand the algorithm enough to know the best solution - this just seems like an internal detail that the end user should not have to resolve/abandon alevin as a result of.

A seperate issue for the [tutorial](https://combine-lab.github.io/alevin-tutorial/2018/setting-up-resources/) that doesn't apply to the accompanying [gist](https://gist.github.com/k3yavi/c501705ed2d29b12b0d10cf78b3ed001): the transcript is generated using gencode.**v28**.pc_transcripts.fa.gz and the txp2gene.tsv is generated using gencode.**v26**.primary_assembly.annotation.gtf.

Perhaps I generated the txp2gene.tsv incorrectly? The bioawk instructions from the tutorial had to be altered (I'm guessing because of version differences).

```bash
bioawk --version
awk version 20110810

# command from tutorial
bioawk -c gff '$feature=="transcript" {print $group}' <(gunzip -c gencode.v29.annotation.gtf.gz) | awk -F ' ' '{print substr($4,2,length($4)-3) "\t" substr($2,2,length($2)-3)}'  - > txp2gene.tsv

bioawk: illegal field $(), name "group"
input record number 7, file /dev/fd/63
 source line number 1

# how I modified it
bioawk -c gff '$feature=="transcript" {print $attribute}' <(gunzip -c gencode.v29.annotation.gtf.gz) | awk -F ' ' '{print substr($4,2,length($4)-3) "\t" substr($2,2,length($2)-3)}' - > txp2gene.tsv

cat txp2gene.tsv | head -n 5
ENST00000456328.2       ENSG00000223972.5
ENST00000450305.2       ENSG00000223972.5
ENST00000488147.1       ENSG00000227232.5
ENST00000619216.1       ENSG00000278267.1
ENST00000473358.1       ENSG00000243485.5
```

**Comment by alexvpickering** [comment]
I tried using Homo_sapiens.GRCh38.94.chr_patch_hapl_scaff.gtf.gz for the annotation file and ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz to build the index but got a similar error. Here are the logs (I modified the salmon log a bit because it didn't have the error message that printed to stdout).

[alevin.log](https://github.com/COMBINE-lab/salmon/files/3224429/alevin.log)
[salmon_quant.log](https://github.com/COMBINE-lab/salmon/files/3224440/salmon_quant.log)

One curious thing that I noticed:

```
Index contained 175,775 targets
...
ERROR: Txp to Gene Map not found for 175775 transcripts
```
It seems to not be finding any of the transcripts? This was also the case for the gencode attempt that I made previously.

**Comment by k3yavi** [comment]
Can you check if the names of the txps in the reference is the same as in the transcript to gene file?
Possible causes we have seen before are:
* Not using `--gencode` while salmon indexing, which doesn't clips off the long names used by gencode as those are not the same in the gtf.
* Ensemble GTF sometimes doesn't have the subversion of the transcript names i.e. Y in `ENSTXX.Y`. If the reference transcriptome has the full name while GTF does not then alevin will complain about it.

**Comment by alexvpickering** [comment]
The ensembl files do seem to be inconsistent about subversion. Here is the cdna file for the index and the GTF:
```bash
zcat Homo_sapiens.GRCh38.cdna.all.fa.gz | awk 'NR % 2 {print $1 "\t" $4}' | head -n 5
>ENST00000632684.1      gene:ENSG00000282431.1
>ENST00000434970.2      gene:ENSG00000237235.2
>ENST00000448914.1      gene:ENSG00000228985.1
>ENST00000415118.1      gene:ENSG00000223997.1
>ENST00000631435.1      gene:ENSG00000282253.1

bioawk -c gff '$feature=="transcript" {print $attribute}' <(gunzip -c Homo_sapiens.GRCh38.94.gtf.gz) | awk -F ' ' '{print substr($6,2,length($6)-3) "\t" substr($2,2,length($2)-3)}' | head -n 5
ENST00000456328 ENSG00000223972
ENST00000450305 ENSG00000223972
ENST00000488147 ENSG00000227232
ENST00000619216 ENSG00000278267
ENST00000473358 ENSG00000243485
```

For the gencode index and GTF

```bash
bioawk -c gff '$feature=="transcript" {print $attribute}' <(gunzip -c gencode.v29.annotation.gtf.gz) | awk -F ' ' '{print substr($4,2,length($4)-3) "\t" substr($2,2,length($2)-3)}' | head -n 5
ENST00000456328.2       ENSG00000223972.5
ENST00000450305.2       ENSG00000223972.5
ENST00000488147.1       ENSG00000227232.5
ENST00000619216.1       ENSG00000278267.1
ENST00000473358.1       ENSG00000243485.5

awk -F '|' '/ENST/ {print $1 "\t" $2}' <(gunzip -c gencode.v29.pc_transcripts.fa.gz) | head -n 10
>ENST00000641515.2      ENSG00000186092.6
>ENST00000335137.4      ENSG00000186092.6
>ENST00000426406.3      ENSG00000284733.1
>ENST00000332831.4      ENSG00000284662.1
>ENST00000420190.6      ENSG00000187634.11
>ENST00000437963.5      ENSG00000187634.11
>ENST00000342066.7      ENSG00000187634.11
>ENST00000618181.4      ENSG00000187634.11
>ENST00000622503.4      ENSG00000187634.11
>ENST00000618323.4      ENSG00000187634.11
```

**Comment by k3yavi** [comment]
Glad to hear that. Yes, I agree we can put some sort of filter while indexing to make the pipeline less painful in case of a failure. Regarding the transcript to gene map file parsing before the CB correction, we plan to make that into the next release which we plan to merge soon. I'll update you once we have the new version ready.

**Comment by alexvpickering** [comment]
Great I will open a separate issue to check for gencode while indexing.

**Comment by k3yavi** [comment]
Hi @alexvpickering ,

With the latest release we have moved the pipeline failure with `txp2gene` file before parsing the CB .

**Comment by k3yavi** [comment]
I think the issue is resolved here. Please feel free to reopen if still face any problems.

**Comment by millerh1** [comment]
Hi @k3yavi Is there any way that an option can be added to ignore missing transcripts? I had to modify the gencode v30 transcriptome fasta and GTF to include fusion transcripts... but this seems to have created an issue:
```
ERROR: Txp to Gene Map not found for 9 transcripts. Exiting
```
I don't think ignoring 9 transcripts should be a big deal. Is there any way to accomplish that? Or any other workaround? 

Thank you,
Henry

**Comment by pinin4fjords** [comment]
@k3yavi this is also still creating issues for us, since the issue remains in current versions. We have a [script](https://github.com/ebi-gene-expression-group/atlas-gene-annotation-manipulation)that we use to filter cDNAs by a GTF, but it makes it very hard to maintain genome assets centrally if we have to have a special cDNA file for Alevin, would be much easier if it just ignored the handful of problem transcripts.

**Comment by blade2344** [comment]
[2025-06-16 13:57:46.045] [alevinLog] [error] ERROR: Can't find gene mapping for : KI270593.1 w/ index 395593
[2025-06-16 13:57:46.045] [alevinLog] [error] ERROR: Txp to Gene Map not found for 194 transcripts. Exiting  this ids are only foun in the genome not transcriptome . 
My error is similar, however my txp files has the same id as my transcriptome files. another thing is that the 194 transcript number matches the number of id in my decoy file could that be a coincedence or related to the error
