### ISSUE TITLE
totalCount_ is not initialized in Transcript constructors

### ISSUE THREAD

**Issue by come-raczy** [COMBINE-lab/salmon#355]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
Affects salmon (bulk mode) for sure. I don't know alevin.

**Describe the bug**
totalCount_ is not initialized in Transcript constructors. In the vast majority of the cases it doesn't matter because the memory is initialized to 0 anyway, but for a very small fraction of the transcripts the totalCount gest initialized to some random value, which can lead to missed invocations of projectToPolytope in normalizeAlphas and writeAbundances

**To Reproduce**

Systematic. Effect might be more difficult to detect as you'd need a truth set. Dumping a trace of the totalCount_ might be easier.

Specifically, please provide at least the following information:

  * Which version of salmon was used?

0.11.3 ans 0.13.1

  * How was salmon installed (compiled, downloaded executable, through bioconda)?

N/A. compiled from scratch

  * Which reference (e.g. transcriptome) was used?

  * Which read files were used?

BAM input, generated by STAR, from proprietary data produced with Illumina instruments.

  * Which which program options were used?

--no-version-check --threads 1 --dumpEq --useEM --noErrorModel --noRichEqClasses --gcBias  -l isr

**Expected behavior**

Accurate values for totalCount for all transcripts.

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10, CentOs 7.5.1804

**Additional context**

Attached patch for 0.13.1:

[Transcript.hpp.patch-0.13.1.txt](https://github.com/COMBINE-lab/salmon/files/3044728/Transcript.hpp.patch-0.13.1.txt)

**Comment by rob-p** [comment]
Hi @come-raczy,

  Thanks for reporting this, it is addressed now in commit efe26b1ca2ced305256357e3b2e95f0e51e3376d.  While the function that returns this value is called in two places `normalizeAlphas()` and `writeAbundances()`, the latter of these is actually deprecated and so is not used (we should clean up that code).  So, while this value should clearly be initialized, the only potential effect here is through `normalizeAlphas()`, is called before the optimization, and which modifies the alphas that will be used for setting the _initial conditions_ of the VBEM.  Therefore, the effect is likely to be limited since, even if the value of `totalCount_` was incorrectly initialized, it should only affect the initialization condition of the optimization.  Thank you again for the detailed bug report, and the patch!  This is now fixed in develop and will be in the next release.
