### ISSUE TITLE
Decoy creation with a genome with alt alleles

### ISSUE THREAD

**Issue by roryk** [COMBINE-lab/salmon#371]
Hi everyone,

I have two questions. Some motiviation: I'm working on figuring out how to support hg38 with the alt alleles for using transcriptome alignments or the SA method. I'd prefer to just use the whole genome alignments since we generate those for QC purposes anyway. STAR doesn't work with the alt alleles so we can't use it for hg38 and have to use hisat2 for hg38 with alts, but hisat2 doesn't have the genome-to-transcriptome shifter built in. I'm reluctant to use the ubu sam-xlate tool to do genome to transcriptome mappings since that project looks abandoned and I'm not super clear on what Salmon is expecting the format to be for the shifted file. So my current plan is to use the SA method and provide decoys. I have two questions:

1) Am I going to need to ignore the alt alleles when creating the decoys file? My version of the decoys for hg38 with the alt-alleles has about twice as many decoy regions as the one calculated on just the toplevel chromosomes.

2) What is the minimal format that Salmon is expecting the transcriptome mapped file to look like? Do I need to just report which transcript and which position for every transcript a read overlaps, or do I need to fix the CIGAR string too?

**Comment by laraib85** [comment]
Hi,
Thank you for the detailed explanation. 
For the first question, ideally you should include the alternate alleles. But they should be part of the transcriptome, instead of the genome. We expect the size of the decoys to double if alt alleles are included in the genome. This is because the decoys are simply regions of high sequence identity between a transcript and the genome. Hence, with alleles as part of the genome, each transcript will map almost equally well to alleles.
If you're running salmon in the alignment mode, the input bam/sam file should include the CIGAR string as well. There is a flag,  `--noErrorModel`, to ignore the CIGAR but that is not recommended, since salmon uses the information for scoring the alignments. 
I hope that answers your concerns.

**Comment by roryk** [comment]
Thanks so much, that totally answers my questions!
