### ISSUE TITLE
barcodes not found in final whitelist

### ISSUE THREAD

**Issue by Ryan-Zhu** [COMBINE-lab/salmon#374]
Hello,

I am running Alevin in Salmon 0.14.0 on Drop-seq data. I used the following options:
```
salmon alevin -l ISR \
-1 fastq/L001_R1_001.fastq.gz fastq/L002_R1_001.fastq.gz \
-2 fastq/L001_R2_001.fastq.gz fastq/L002_R2_001.fastq.gz \
--dropseq -i index -p 80 -o alevin_output --tgMap txp2gene.tsv --dumpFeatures --dumpMtx
```
This generated a .mtx file with **1602** CB. However, in the final whitelist generated after run (alevin_output/alevin/whitelist.txt), I see **647** CB. When intersecting the these CB (**1602** vs. **647**), only **501** were in common.

Why weren't all 647 CBs found in the output whitelist? I'd like to subset the .mtx file to get all cells in the final whitelist. Thank you.

**Comment by k3yavi** [comment]
Hi @Ryan-Zhu ,
Can you please share the logs ?

**Comment by Ryan-Zhu** [comment]
Please see all my output files except `raw_cb_frequency.txt` (large file) and my genelist `quants_mat_cols.txt`. Thanks.
[alevin_out.zip](https://github.com/COMBINE-lab/salmon/files/3287720/alevin_out.zip)

**Comment by k3yavi** [comment]
Thanks @Ryan-Zhu ,

A couple of thoughts.
To me the data seem a little noisy as a lot of CB/reads are thrown away due to "knee" thresholding.
Check https://github.com/COMBINE-lab/salmon/issues/362 if you wanna play with how to customize alevin for user-define whitelisting.

Having said that this is how you can parse the  data from alevin.
Alevin use 1277 CB after its knee thresholding + 638 low confidence Barcode for downstream whitelisting = total 1915 CBs.
If you check the warning in the log it says :

```
[2019-06-12 15:07:08.152] [alevinLog] [warning] Skipped 313 barcodes due to No mapped read
```
Basically it means out of 1915, 313 didn't had any read mapped to them, so alevin doesn't report them in the output matrix. Alevin reports 1915 - 313 = 1602 CBs both in `.mtx` and `quants_mat.gz` file. You can check the order of the CB in the `quants_mat_rows.txt` file, which has 1602 rows/CBs.

If you don't provide alevin with external whitelist alevin tries to do post whitelisting of it's own. Basically out of the 1277 high confidence CBs alevin initially find out through knee it assigns 647 CBs as final whitelisted CB as found in the `whitelist.txt` file. If you wan't to subsample these CBs you have to extract the information from the `.mtx` or `quants_mat.gz` file.

You can check a simple python parse of the `quants_mat.gz` file [here](https://github.com/k3yavi/vpolo/blob/master/vpolo/alevin/parser.py#L187-L230).

**Comment by Ryan-Zhu** [comment]
Thanks for the detailed explanation. Now I understand how whitelisting much better. 

You wrote:
> Basically out of the 1277 high confidence CBs ...  it assigns 647 CBs as final whitelisted CB as found in the `whitelist.txt` file.

Now 1602 is the final CBs in the output `.mat` or `_mat.gz` files.
My question is shouldn't alevin assigns the final 647 from the 1602 CBs, therefore 1602 CBs **∩** 647 CBs = 647? Now I am seeing 1602 CBs **∩** 647 CBs = 501 which is still confusing to me. Thank you.

**Comment by k3yavi** [comment]
That's correct @Ryan-Zhu . It seems there might be a bug in the final whitelisting.
Is it possible for you to share a subset of fastq from which i can replicate and correct this ?

Thanks for reporting this.

**Comment by Ryan-Zhu** [comment]
[test_fastq.zip](https://github.com/COMBINE-lab/salmon/files/3288299/test_fastq.zip)
@k3yavi I randomly subsampled 10000 R1/R2 pairs. Note alevin reported 18.55% fraction reads in cells so you should expect similar number.

Thank you for troubleshooting!

**Comment by k3yavi** [comment]
Hi @Ryan-Zhu ,

Thanks a lot for bringing this to our attention.
We have fixed this in the latest commit of the develop branch https://github.com/COMBINE-lab/salmon/commit/e93d6cee19c46d56d603e75097dbe17ab18e6811 and will merge in the next release . Usually the number of skipped Barcodes due to no mapped reads are relatively few that's why this corner case slipped from our testing. If it's possible for you to compile salmon from source you can use the develop branch to generate the new binary otherwise let us know we can provide a temporary linux binary until the next release.

**Comment by Ryan-Zhu** [comment]
Corner cases are hard to catch. The drop-seq dataset I was probing was from 2-3 years ago and it appeared very noisy. When I tried Alevin with a morden 10x V2 dataset there was no issue at all. 
Anyway, thank you for the quick fix. I tested it and it worked well.

**Comment by k3yavi** [comment]
Thanks @Ryan-Zhu  for the confirmation.
Closing the issue.
