### ISSUE TITLE
Output pseudobams?

### ISSUE THREAD

**Issue by roryk** [COMBINE-lab/salmon#38]
Would it be possible to output a pseudobam file, similar to kallisto?

We'd use the pseudobam file to clean PCR duplicates by using unique molecular identifiers (UMI), often used when doing single-cell RNA-seq. The way we are currently doing it is by sticking the UMI for each read in the read name, aligning and then cleaning the BAM file by keeping only alignments with unique (UMI, mapping position) pairs.

I was imagining running salmon twice, feeding back in a UMI-cleaned pseudobam file to do the final quantification.

kallisto doesn't exactly do what we want because the read name is lost in the pseudobam, but there isn't any reason it could be kept or stuck in the INFO field as a tag.

**Comment by rob-p** [comment]
Hi @roryk,

  Salmon doesn't currently have the ability to output a pseudobam, but that is definitely possible (and not too difficult).  We have a related feature planned; perhaps you could tell me if it suits your use case.  However, first, I should mention that if you'd simply like a pseudobam for *all* the mapping locations of the reads, you can use [RapMap](https://github.com/COMBINE-lab/RapMap).  RapMap implements the quasi-mapping algorithm upon which Salmon and Sailfish are based (and RapMap is used as a library in the Salmon and Sailfish codebases).  Given an index and set of reads, RapMap will report all of the multi-mapping locations that Salmon and Sailfish would consider during quantification.

  The other feature we have in the works is to have Salmon optionally output a `.bam` file (with actual alignments) post-quantification.  It turns out that, given the quasi-mapping information and the quantification results, taking the extra step from quasi-mapping to an actual *alignment* can be done fairly efficiently.  In this mode, Salmon would make one more pass over the reads and, considering the estimated abundances, sample a single alignment for each multi-mapping read proportional to the relative abundance of the different multi-mapping targets (i.e. it would perform a sampling over the multi-mapping locations that would, in expectation, give the same abundances as the *soft* assignments computed by the optimization algorithm).  This feature will be very useful for [transrate](https://github.com/Blahah/transrate).  However, given that your goal is to use outside information to perform the filtering yourself, this option may not be ideal for you.

**Comment by vals** [comment]
Is removing the read name a new thing in Kallisto? I counted UMI's with Kallisto pseudobams a while ago. Here's one in that pseudobam:

    SRR1545849.1:CELL_A12:UMI_CTGGCA	0	ERCC-00002	1	255	8S33M	*	0	0	GGGAATTCTCCAGATTACTTCCATTTCCGCCCAAGCTGCTC	ggcccccbccccbbcbcccccbbcdd]__a_ccc_^bb`b_	NH:i:1

Regarding what you want to do, you should look at RapMap: https://github.com/COMBINE-lab/RapMap

It's the pseudoalignment part of Salmon without the quantification. I'm using it in my single cell processing: https://github.com/vals/umis 

Are you using something which put's UMI's cDNA fragments? Because Salmon or Kallisto assumes coverage over full transcript.

**Comment by roryk** [comment]
Hi Valentine,

You're totally right about kallisto, I was looking at the wrong FASTQ file when comparing the names. Thanks for the RapMap tip and pointing to your repo, maybe we can roll that into bcbio-nextgen.

Rob, it sounds like what you are suggesting would be great. Having an actual alignment would be so useful.

**Comment by rob-p** [comment]
The implementation to output mapping information from within salmon (not yet full alignments) is almost complete.  The feature needs some testing, but it will definitely make it into the next release.

**Comment by rob-p** [comment]
Ok, SAM output of the mapping information is available in 0.7.2 :).

**Comment by InesdeSantiago** [comment]
@rob-p hi,
any chance of making them BAM output for future releases? In some cases (e.g. TCGA files) the SAM output can be really huge...

**Comment by mdshw5** [comment]
You can just add a pipe to samtools to your existing command: `--writeMappings | samtools view -Sb - | samtools sort -T sort.tmp -o -  > out.bam`

**Comment by rbenel** [comment]
@mdshw5, did that work for you? I am trying to pipe samtools to my current salmon quant command, and it is not successful. 
`salmonCommand="${salmon} quant -i $index -l SF -r ${sample1} -p 8 -o ${output_folder}/${basename_sample}_quant --writeMappings | samtools view -Sb - | samtools sort -T sort.tmp -o - > ${output_folder}/${basename_sample}_quant/${basename_sample}.bam"`

**Comment by rob-p** [comment]
@rbenel,

  If you are using a version prior to 0.14.0, you will also have to pass `--no-version-check` to avoid contamination of stdout by the versioning message.

**Comment by mdshw5** [comment]
That makes sense. I’ve always been disabling the version check.

**Comment by rbenel** [comment]
@rob-p 
Thanks for the quick response! For this specific run I am running an older version.
However, even with the `--no-version-check` flag I can't seem to pipe `writeMappings` to samtools (same command as above).
``` (mapping-based mode) Exception : [unrecognised option '-b'].
Please be sure you are passing correct options, and that you are running in the intended mode.
alignment-based mode is detected and enabled via the '-a' flag. Exiting.```
On the other hand, `--writeMappings=output.sam` works fine.
