### ISSUE TITLE
Can SA method work with gff files

### ISSUE THREAD

**Issue by tamuanand** [COMBINE-lab/salmon#384]
I have a question during the ```generateDecoyTranscriptome.sh``` script - can it be made to work with a gff file instead of a gtf.

Thanks in advance

**Comment by k3yavi** [comment]
Hi @tamuanand ,

We use the gtf to extract the exonic position in the genomic coordinates. If you can make a bed file with the name `exons.bed` which contains all the exon's start and end position like the following:

```
chr1    140075  140339
chr1    139790  139847
chr1    146386  149707
chr1    141474  143011
chr1    146642  146831
```

Then you can comment the line https://github.com/COMBINE-lab/SalmonTools/blob/master/scripts/generateDecoyTranscriptome.sh#L97 and run the script as usual.

**Comment by tamuanand** [comment]
Hi @k3yavi 

Thanks for your input. 

If I do it the way you suggest, do I need a command line option to reference this exons.bed file instead of the gtf file - for which I need to modify the getopts block

Probably, it would be a good idea to also have this option enabled as a command line flag (i.e. use of exons.bed instead of gtf)

**Comment by rob-p** [comment]
Hi @tamuanand & @k3yavi,

  Actually, I think the `makefasta` bedtools command we use accepts a gff file directly (https://bedtools.readthedocs.io/en/latest/content/tools/maskfasta.html).  So, it might make sense to have a flag (or automatically detect, but that can be error prone), and only run the line Avi links above if we have a GTF.  If we have a BED or GFF file, we can just pass it directly to bedtools.

**Comment by tamuanand** [comment]
Hey @rob-p ,

Thanks for your response.

I agree with your suggestion - to have a flag for gff/bed and run either GTF or a BED/GFF file depending on what the end user has. In my case, I have mostly gff files and I need to do some reformatting if I have to use the current shell script.

**Comment by doubtfulresearch** [comment]
Looking at the script, its only using fields 1, 3, 4, and 5 of the GTF to make exons.bed. Since these are identical (seqname, feature, start, and end) wouldn't the script produce an exons.bed file when given a gff just like it would when given a gtf? Assuming 'exon' is used as a feature in the GFF.

**Comment by k3yavi** [comment]
With the release of `v1.0` we don't need the gtf/gff any more. Closing this issue.

**Comment by tamuanand** [comment]
@rob-p @k3yavi 
IMO, There is something missing in all the relevant documentation associated with salmon/v1.0

https://salmon.readthedocs.io/en/latest/salmon.html#preparing-transcriptome-indices-mapping-based-mode points to this https://github.com/COMBINE-lab/SalmonTools/blob/master/README.md which still states the use of gtf/gff

also, the usage statement in  generateDecoyTranscriptome.sh script [here](https://github.com/COMBINE-lab/SalmonTools/blob/master/scripts/generateDecoyTranscriptome.sh)  still states the use of gtf files

The link to the preprint paper within salmon_readthedocs stills points to the June 2019 version - https://www.biorxiv.org/content/10.1101/657874v1  

Isn't there a newer version of this preprint which got released couple of days back..

Am I missing something?

**Comment by k3yavi** [comment]
Hi @tamuanand ,

Thanks for pointing this out. You are right, we missed to update the salmon doc with this details. You can find the latest preprint [here](https://www.biorxiv.org/content/10.1101/657874v2). The new version don't require the GTF because now we don't generate the decoys explicitly i.e. you don't have to run mashmap. With the latest version salmon, it can consume the full genome and transcriptome without the explicit need of annotation. It's much more efficient and takes significantly less memory to align/quantify  compared to other genome based method. Please checkout the preprint for more details and [this](https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/) tutorial for how to index the gentrome (genome + transcriptome) index. We will update the salmon docs too, to reflect the same.
