### ISSUE TITLE
Building index failed [std::bad_alloc]

### ISSUE THREAD

**Issue by tharvesh** [COMBINE-lab/salmon#39]
Hi,

I have been trying to build an index for transcripts, it is composed of GENCODE and several unannotated transcripts from different sources(~95k, non-overlapping). Used following command

   salmon index -t cgm_annotation.fa -i cgm_index --type quasi

Version Info: This is the most recent version of Salmon.
[2016-01-29 13:44:08.001] [jointLog] [info] building index
RapMap Indexer

[Step 1 of 4] : counting k-mers
counted k-mers for 90000 transcriptsElapsed time: 27.9634s

Replaced 4303414 non-ATCG nucleotides
Clipped poly-A tails from 226 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 0.243976s
Writing sequence data to file . . . done
Elapsed time: 10.3463s
[info] Building 64-bit suffix array (length of generalized text is 2398906742 )
Elapsed time: 0.000125994s
Exception : [std::bad_alloc]
salmon index was invoked improperly.
For usage information, try salmon index --help
Exiting.

**Comment by rob-p** [comment]
Hi @tharvesh — The error suggests that memory allocation failed when trying to build the suffix array.  I'm guessing from what I can tell from the log (e.g. the fact that the 64-bit index is being invoked, suggesting the input contains > 2^31 nucleotides), that you actually tried to build an index on the GENCODE **genome** plus a set of extra transcripts.  Salmon (unlike Cufflinks, but like RSEM, TIGAR, eXpress, etc.) should be used with the **transcriptome**, not the **genome** of the target organism.  That is, if you want to use GENCODE (say, in human), you should be indexing either (ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_24/gencode.v24.transcripts.fa.gz) or (ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_24/gencode.v24.pc_transcripts.fa.gz), not e.g. (ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_24/GRCh38.primary_assembly.genome.fa.gz).

**Comment by tharvesh** [comment]
Hi @rob-p ,

I got your point. I can understand the issue now.

I was trying a different approach.
It's not a complete genome, instead using co-ordinates from .gtf file of GENCODE and extras (gene model), I extracted sequences using an other tool to make transcripts.fa from genome.

Any suggestions?

**Comment by rob-p** [comment]
Well,  one can certainly use a tool (like gffread or rsem-prepare-reference) to take a genome and a (possibly custom/augmented) GTF to extract a set of target transcripts.  Above, it looks like you were only processing between 90 and 100k transcripts.  Given the overall size of the overall reference — ~2.4 billion nucleotides — my guess would be that some of these transcripts may be exceedingly long (and perhaps extracted incorrectly from the underlying tool).  I should note that an index can be built on large references (which is why we support 64-bit index construction), but it's a very rare use-case as most transcriptomes (even large *de novo* transcriptomes) rarely cross the 2^31 barrier, and I would expect it to consume quite a bit of memory.  The default `quasi` indexer of Salmon is optimized to be very fast for typical sized transcriptomes (usually a few hundred mega-bases) at the cost of using more memory.  The alternative `fmd` index can be made more memory efficient, by setting a larger sampling factor, but the resulting mapping will be slower (though still much faster than standard alignment).

I would first check to see if the transcripts.fa file contains what you were expecting (i.e. the normal transcriptome + the auxiliary transcripts you were interested in quantifying), and that you actually have close to 2.4Gb of non-redundant transcriptome sequence that you want to quantify.  If this is the case, the options are to try and build the quasi-index on a large memory machine (building the index requires more memory than mapping with the constructed index), or using the fmd-index with a large sampling factor.

Best,
Rob

**Comment by tharvesh** [comment]
Thank you for your helpful suggestion.

I have to check for transcripts that are very large and what so awkward about that.

If it is fine I would go with fmd indexing.
