### ISSUE TITLE
Throw error if reads are less than k-mer size

### ISSUE THREAD

**Issue by kieranrcampbell** [COMBINE-lab/salmon#41]
If the read length in the FASTQ input files to Salmon are less than the k-mer size used when building the index then no error is produced but a mapping rate of 0% is reported. It would be useful for Salmon to throw an error telling the user that the mapping will surely fail for this reason (as opposed to others such as wrong reference transcriptome or wrong library type), and suggest rebuilding the index using a smaller k-mer size.

**Comment by rob-p** [comment]
Hi @kieranrcampbell,

  Indeed, such reads will be un-mappable.  The only tricky question here is at which point we should (1) do nothing (2) issue a warning (3) issue an error.  Since the reads may not all be of the same size (perhaps the user has quality-trimmed the reads first and not opted to discard the short ones), it's possible we may see some reads too short to consider, but others would not be.  We could choose arbitrary cutoffs (warning if greater than 1,000 such reads and an error if greater than 1,000,000), but this will, of course, depend on how large the input data set is.  Anyway, I agree that we should notify the user of this and will be happy to add it; do you have any suggestions on the default behavior?

**Comment by mdshw5** [comment]
Since you'll issue a warning at the end of the run, maybe a rate makes more sense. Something like >10% or input reads were smaller than the kmer size.

**Comment by kieranrcampbell** [comment]
My preference would be to throw a warning if any reads are shorter than the
kmer length and throw an error if all are. So if any reads are less then
k-mer length report "Warning: x% of reads were found to be less than k used
to build index. Consider rebuilding index with smaller k. Minimum read size
found was [min read size]" and then halt execution if x% is 100%. Would
that sound reasonable?

Thanks,

Kieran

**Comment by rob-p** [comment]
Yup, this sounds like a reasonable way to handle the issue.  Of course, you wouldn't know that 100% of the fragments are too short until the run has completed, but c' est la vie.  I'll go with this strategy since I can't really think of anything more effective.

**Comment by rob-p** [comment]
This has been implemented in commit 590b880.  Currently, these stats are reported at the end of mapping, but before the offline EM algorithm runs.
