### ISSUE TITLE
Hamming distance for UMI collapse

### ISSUE THREAD

**Issue by knokknok** [COMBINE-lab/salmon#430]
Would it be possible to increase the authorised Hamming distance in the UMI collapsing step?

**Comment by k3yavi** [comment]
Hi @knokknok ,

Thanks for your question.
Unfortunately, we don't have a command line option to do that in the released version.
However, you can potentially change [this](https://github.com/COMBINE-lab/salmon/blob/master/src/Graph.cpp#L52) from `oneHamming` to `kHamming` with your required distance, and compile salmon from source, alevin can potentially use higher distance UMIs. One thing to note here would be, since we are checking for more distant UMIs the overall running time can increase.

Hope it helps.

**Comment by rob-p** [comment]
To add to @k3yavi's answer.  It would be possible, I think, to add a command line flag for this, with the runtime caveat that Avi mentions.  Should we give it a try, Avi?

**Comment by k3yavi** [comment]
Yep, already added, will push to develop with the changes in the inference .

**Comment by knokknok** [comment]
Thanks @k3yavi !

I don't fully understand how ```k1``` and ```k2``` are generated but doesn't https://github.com/COMBINE-lab/salmon/blob/179191a0ed8e9e41dbf5aac37bd7c1f07093ab18/src/Graph.cpp#L39 imply that the UMI is at most 10 bases long?
If so, shouldn't it be "dynamic" based on ```umiLength``` (or at least be ```i<64``` to cover the highest compatible case)?

**Comment by k3yavi** [comment]
Hi @knokknok,

Nice catch ! K1 bad k2 are just two bit encoding of the UMI sequences, it passed my unit test because I was testing it with 10x data but you are right it should be dynamic based on the umi length. I'll make the changes to reflect that in the develop branch. Thanks !

**Comment by k3yavi** [comment]
Hi @knokknok ,

The latest commit on develop branch https://github.com/COMBINE-lab/salmon/commit/94eab5dae04da4ca02b8da8b630e0750bc15e010 , should fix it. However, there are other major changes in develop branch which can change things from last stable release. I'd recommend, if you can, then please wait for some time before we make the official release of `1.0`.  If it's urgent, then try grep(ping) for the changes related to `umiLength` from the above commit and making them into your local salmon code. Hope this helps !

**Comment by k3yavi** [comment]
It's now available in latest stable release, closing the issue but feel free to reopen if you have any issues.
