### ISSUE TITLE
bootstrap results

### ISSUE THREAD

**Issue by s6juncheng** [COMBINE-lab/salmon#47]
Hi,

I used the flag --numBootstraps 100, but I don't get bootstrap results in my output folder. There is a aux/bootstrap folder with two gz files, but they do not look like to be the results. 

My command:
{
    "salmon_version": "0.6.0",
    "index": "index_salmon_quasi",
    "libType": "ISF",
    "mates1": "R1.fastq",
    "mates2": "R2.fastq",
    "output": "K562",
    "numBootstraps": "100",
    "threads": "10"
}

**Comment by rob-p** [comment]
Hi @s6juncheng,

  What do you mean "they do not look at the results"?  Because bootstrap values can be large, they are stored in a compressed binary format.  Can you tell me what files are in your aux/bootstrap folder?  If you are interested in observing the bootstrap values manually, I can help you with a script that converts them to a text format.

--Rob

**Comment by s6juncheng** [comment]
Hi @rob-p ,
sorry for the typo. Because the file bootstraps.gz is binary, and I saw from http://robpatro.com/blog/?p=291 that, there should be a text file named quant_bootstraps.sf. 

Yes, if you have a script for conversion, I would like to have. 

I used Kalisto on my data before, but because kalisto do not support strand specific data, I switched to salmon. Does strand specific information helps a lot?

Thanks,
Jun

**Comment by rob-p** [comment]
Hi @s6juncheng,

  Ahh --- yes, we've since updated the data format so that output sizes stay small even when the number of bootstraps grows large.  Thanks for pointing out the inconsistency with respect to the blog; I'll update that.  I'll put together a script to convert the bootstrap values to a text format so that you can view them.

Regarding strand specific information: Yes, if you have considerably antisense transcription, then the strand information can be quite helpful.  It can make a significant difference in terms of quantification results.

--Rob

**Comment by rob-p** [comment]
Hi @s6juncheng,

  I've written [this script](https://github.com/COMBINE-lab/salmon/blob/master/scripts/ConvertBootstrapsToTSV.py) which will convert the binary bootstrap samples into a text format.  The text format is as follows:

  * The first line is a tab-separated list of transcript names.
  * Each subsequent line is a tab-separated bootstrap sample.
      * The number of entries in each of these lines is the same as the number of transcripts
      * The number of such lines is equal to the number of boot strap samples.

Thus, you can view this as a column-oriented file, where each column contains all of the bootstrap samples for a single transcript.

**Comment by rob-p** [comment]
I've also updated the blog post to refer to the new format.  I'm going to close this issue for now, but please feel free to comment on it or re-open if you run into any more trouble.

**Comment by tmmse** [comment]
Hello @rob-p 

I tried running your script for converting binary bootstrap samples into a text format. I gave back following error:

Traceback (most recent call last):
  File "./ConvertBootstrapsToTSV.py", line 98, in <module>
    main(args)
  File "./ConvertBootstrapsToTSV.py", line 45, in main
    txpNames = nf.read().strip().split('\t')
TypeError: a bytes-like object is required, not 'str'

I processed the samples with salmon version 0.8.2. Do you have any suggestion how I can fix this error? 

Thank you.

**Comment by rob-p** [comment]
Hi @tmmse,

  Interesting.  It should work out of the box.   Could you send / share one of your quant directories as well?

**Comment by tmmse** [comment]
Hello @rob-p 

I compressed a directory from a sample that was processed using the bootstrap options and added it as attachment.
[sample1_bootstraps30.tar.gz](https://github.com/COMBINE-lab/salmon/files/1387079/sample1_bootstraps30.tar.gz)

**Comment by rob-p** [comment]
Hi @tmmse,

  I have a feeling this is a python 2 vs. python 3 issue.  I just ran your data through the script without problem on my end, but my default python install is still 2.7.  When using a Python 3 install, I get the same error you're seeing.  I updated the script so that it should now be python3 compatible.  You can find that version [here](https://github.com/COMBINE-lab/salmon/blob/develop/scripts/ConvertBootstrapsToTSV.py). Please let me know if it works for you.  These changes should be in the next release as well (which should land soon).

**Comment by tmmse** [comment]
Hello @rob-p 

I was using python 3. 

Your new script works without producing an error. When I run it, I get a text where the first row are the transcripts and the otherline are bootstrapvalues. Thank you very much for the help!

**Comment by Ray6283** [comment]
Hi @rob-p 
When I run with --numBootstraps 50 for instance, it makes a folder called boostrap and has two files in it.

One is in  boostraps.gz (the format is not readable when I open it)  another file  names.tsv with some transcript IDs.
I was wondering what those transcripts represent in the file names.tsv?

Also, if a file is not readable, do you have any idea how to fix it? Because when I run for GC bias, it also produces two files observd_gc and expected_gc that I can open them but the format is not readable. 

Thanks in advance for your time.

**Comment by rob-p** [comment]
Hi @Ray6283,

  The `bootstraps.gz` file is not designed to be read as plain text. The file encodes information in binary.  If you are interested in extract the information encoded in those files, the easiest thing to do is likely to read them in using the [`fishpond`](https://bioconductor.org/packages/release/bioc/html/fishpond.html) package.  Looking at the code there will also show you exactly how those files are packed.

  The same is true for the bias files.  The format for those is documented [here](https://salmon.readthedocs.io/en/latest/file_formats.html#sequence-specific-bias-files) and [here](https://salmon.readthedocs.io/en/latest/file_formats.html#fragment-gc-bias-files), those these are binary encoded files and not designed for human consumption.  For the bias files, even if you did read them in, the information is not trivially interpretable (e.g. the parameters of the variable length Markov model, etc.).

--Rob

**Comment by Ray6283** [comment]
Thanks very much. 
The names.tsv file is readable with transcript ID, I was wondering what those transcripts indicate in names.tsv in the bootstrap folder.

Regards

**Comment by rob-p** [comment]
The `names.tsv` file lists the order in which the transcripts appear in the bootstrap samples (encoded in binary) in the `bootstraps.gz` file.

**Comment by Ray6283** [comment]
🙏 🙏

**Comment by hwoodw03** [comment]
Hi, 

Can the bootstraps.gz and names.tsv be used as inputs for further downstream analysis in Salmon when would use tximport command with bootstraps = TRUE? As it doesn't appear to be separate quantification files?

**Comment by rob-p** [comment]
Yes. Bootstraps or Gibbs replicates can be used downstream with Swish (via tximport) or EdgeR (via catchSalmon) to improve transcript level differential testing.

**Comment by hwoodw03** [comment]
Hi Rob, 

Thank you, would you need to run the script above to obtain the quantification data for the replicates or is it already contained in the quant.sf file? 

Thanks

**Comment by hwoodw03** [comment]
Thanks for your help!
