### ISSUE TITLE
Two quick questions about salmon

### ISSUE THREAD

**Issue by lauraht** [COMBINE-lab/salmon#478]
Hi Rob,

I have two quick questions about salmon:

(1) For paired-end reads, does it make any difference in running salmon whether or not the defline of the sequence in input fastq files has read id appended (as 'accession.spot.readid')?
In fastq-dump, if we use the “-I” option, the defline of the sequence in one file has read id appended as “xxx.1” and the other as “xxx.2”. For example:
In file_1.fastq, a sequence has its defline:
`@ERR1586786.1.1 1 length=125`
In file_2.fastq, the corresponding paired sequence has its defline:
`@ERR1586786.1.2 1 length=125`

If we do not use the “-I” option, in both file_1.fastq and file_2.fastq, the two paired sequences have the same defline:
`@ERR1586786.1 1 length=125`

So I was wondering whether or not these two situations make any difference in running salmon? In other words, does salmon have any requirements on this (since many tools require read id appended for paired-end reads)?

(2) I found that each time running salmon on the same sequence file, the results (the quant.sf file) have some differences. Is this an expected behavior?

I am using the version: salmon 0.9.1.

Thank you very much!

**Comment by rob-p** [comment]
Hi @lauraht,

  Sure; let me answer these in order.

(1) Salmon does not really make use of the read id (we assume the fasta files are synchronized in the input).  The one place that not using the `-l` option might raise a complication is if you wish to dump the mappings and examine them (using `--writeMappings`), in which case it will be difficult in the SAM file to discern which read is which just from the names (though the flags should still be valid).

(2) Yes, this is normal and expected behavior.  Since the online phase of salmon is asynchronous, the online updates may arrive in a slightly different order.  This can lead to a slightly different starting condition for the offline phase and, subsequently, small differences in the abundances.  However, these differences are generally small and are _inherent_ to the uncertainty in the inference itself.  That is, the estimates have inherent uncertainty that is greater than the variation you might see between runs.  To assess this you can (and, perhaps should) estimate this uncertainty by asking salmon to draw inferential samples (e.g. Gibbs samples with `--numGibbsSamples`).

Best,
Rob

P.S. As a general note, I'd recommending upgrading to the latest version of salmon.  We update salmon quite regularly with both small and large improvements (and bug fixes where relevant).  There has been quite a lot of progress since version 0.9.1.

**Comment by lauraht** [comment]
Thank you so much Rob! This is very helpful!

Just to further confirm: for the fastq files obtained without using the “-I” option in fastq-dump, salmon works perfectly fine; but for examining the mappings, it’d be more convenient to use the “-I” option in fastq-dump, is that right?

Another quick question: if using the latest version of salmon, is the latest version backward compatible with the salmon index previously created using the older version?

Thank you very much!

**Comment by lauraht** [comment]
Hi Rob,

Sorry for bothering you again. I just wanted to know whether the latest salmon version is backward compatible with the salmon index previously built using an older salmon version? In other words, is it OK to run the latest salmon version with the salmon index of transcriptome that was previously built using an older salmon version?

Thank you very much!
