### ISSUE TITLE
>50% of dovetail mapping in salmon 1.1.0

### ISSUE THREAD

**Issue by zhangchipku** [COMBINE-lab/salmon#485]
Dear Salmon Dev team,
I recently upgraded salmon 0.8.3 to 1.1.0.
I run the sample using libtype -IU.
For the new1.1.0, I used --validateMappings together with index built with genome decoys.
I noticed unusual amount of dovetail mapping being discarded. Here is the meta_info from the new version:
```
    "num_processed": 107275750,
    "num_mapped": 50376830,
    "num_decoy_fragments": 381872,
    "num_dovetail_fragments": 55224702,
    "num_fragments_filtered_vm": 47824323,
    "num_alignments_below_threshold_for_mapped_fragments_vm": 1540436314,
    "percent_mapped": 46.960128454007548,
```
Meta info from v0.8.3:
```
     "num_processed": 107275750,
    "num_mapped": 89940471,
    "percent_mapped": 83.8404494958087,
```
Again, they were ran on the same sample.
Please let me know if there is something wrong in my parameters. Or do you think this is a poor sample quality issue.
Thanks.

**Comment by rob-p** [comment]
Hi @zhangchipku,

  Thank you for raising this issue and providing the output of the different versions.  There certainly does seem to be a large number of dovetail reads.  These are not _always_ bad, or indicative of a poor quality library.  However, having such a large fraction is a bit strange.  We made the decision, when selective alignment became the default, to behave in a way similar to Bowtie2, by default — that is, consider dovetail mappings as discordant.  However, just like Bowtie2, we do have an option to allow them. The `--allowDovetail` option will allow these fragments to be counted toward quantification.  It is worth considering (1) how the quantification results allowing the dovetail fragments look and (2) if there may be a good explanation for why, in your sample, you might expect to see such a high proportion of dovetail alignments.

--Rob

**Comment by zhangchipku** [comment]
Thanks for the quick reply. Here is the output after adding --allowDovetail
    "num_processed": 107275750,
    "num_mapped": 50729814,
    "num_decoy_fragments": 375797,
    "num_dovetail_fragments": 55224698,
    "num_fragments_filtered_vm": 47470013,
    "num_alignments_below_threshold_for_mapped_fragments_vm": 757388230,
    "percent_mapped": 47.2891720635838,

Do you know why the mapping rate is still so low?

**Comment by rob-p** [comment]
@zhangchipku,

  Yes, it seems that the biggest culprit here is `num_fragments_filtered_vm`.  That is the number of fragments filtered because the best alignment failed to reach the threshold for a "valid" alignment.    Here, `47,470,013` fragments are discarded entirely because they didn't have an alignment meeting the required quality.  If these fragments (which do have matching MEMs, because alignment was carried out for them) were mapped, then the overall mapping rate would go up to `50,729,814 + 47,470,013 = 98,199,827 / 107,275,750 = ~91.5%`.  Now, I wouldn't expect _all_ of these to be mappable, and some alignments might not be feasible at any reasonable quality whatsoever.

  My recommendation would be as follows.  First, have you trimmed these reads (using e.g. `fastp` or `TrimGalore` or some such)?  Very low quality read ends or (more likely) adapter contamination could cause the reads that have matching MEMs to fail to align within the required score threshold.  My first recommendation would be to trim the reads and see how the mapping rate changes.  Second, the required alignment score is a user-alterable parameter.  By changing `--minScoreFraction` to be lower, you can allow reads with even lower alignment scores to be counted for quantification.  The default value is `0.65`, so you could explore what happens if you lower this number.  The number represents the fraction of the maximum achievable alignment score that a read must obtain to be considered a valid alignment.

--Rob

**Comment by zhangchipku** [comment]
Thanks, I usually do not trim reads. I am surprised to see such a difference from version 0.8.3. Do you have a recommendation for  --minScoreFraction if I do not trim reads? Or maybe I should go back to  NOT using --validateMappings?
For testing purposes, I will try trimming the reads for this sample. Will report back.

**Comment by rob-p** [comment]
@zhangchipku,

  The default value of `--minScoreFraction` is quite reasonable, I think.  It depends on the read length, but for a 100-bp read, it corresponds to 8 mismatches under the default scoring parameters.  So the read pair could have up to 16 mismatches before being discarded.  I understand that the recommendation to trim reads is a new one, but I think it is a standard best-practice anyway.  However, we are looking at the possibility of allowing read-end soft-clipping in future releases, which could mitigate this need in the most common case.

  It is worth noting that, if you *don't* want to use selective alignment, then the last version of salmon that you can use is the one tagged as `0.15.0`.  As of version 1.0.0, the index structure and default mapping algorithm changed, so that selective alignment is "always on".  This is discussed in some detail in the release notes for version 1.0.0.  Generally, we think that the benefits offered by selective-alignment are important, and, unless there is a very strong reason not to, one should generally ensure that reads sharing some exact matches with the reference also produce reasonable quality alignments at the implied loci.  However, we also try to be very receptive and responsive to our users' workflows and desiderata, so if the soft-clipping feature is something that would make your experience much smoother, we will certainly consider prioritizing that feature for a future release.

**Comment by zhangchipku** [comment]
You are right on the spot. 
After trimming, every problem went away:
    "num_processed": 102482661,
    "num_mapped": 85812375,
    "num_decoy_fragments": 760387,
    "num_dovetail_fragments": 1265734,
    "num_fragments_filtered_vm": 7722295,
    "num_alignments_below_threshold_for_mapped_fragments_vm": 293676436,
    "percent_mapped": 83.7335546937057,

I would really like to have the soft clipping feature though. With salmon being so fast, trimming step basically takes more time than the salmon quantification step. A lot of us are now turning to cloud platforms and are charged by the the computing time.

Some other questions unrelated to this topic:
For snRNA-seq like 10X platform, do you recommend just trimming read2?
From what I read out of documentation, decoy enhanced index would only work with --validateMapping. Would Alevin only work with non-decoy index then?

**Comment by zhangchipku** [comment]
By the way, I really need to thank your team for actively making Salmon better and even completely changing algorithyms years after publication. You guys are setting up good examples for academic research.

**Comment by rob-p** [comment]
Thank you for verifying @zhangchipku, and thank you very much for the kind words!  We appreciate the feedback and input from our users like yourself.  We'll prioritize the soft-clipping functionality for upcoming releases (maybe even the next if we can make that work in time).  For the time being, I can recommend `fastp` as a fairly efficient / fast trimmer that.  It might even be able to work in a streaming fashion so that you could pipe the trimmed reads directly to salmon.

**Comment by tamuanand** [comment]
@rob-p I would request that you try out bbduk and bbmap for quality/adapter trimming and contaminant removal.
> Thank you for verifying @zhangchipku, For the time being, I can recommend `fastp` as a fairly efficient / fast trimmer that. It might even be able to work in a streaming fashion so that you could pipe the trimmed reads directly to salmon.

**Comment by rob-p** [comment]
Hi @tamuanand,

  Sure; is there anything specific about bbduk and bbmap for quality / adapter trimming that you think would be provided beyond or in addition to what fastp provides?  Also, we have a beta implementation of soft-clipping and are looking for a wide net of testing data.  Any suggestions to that end would be welcome!

**Comment by tamuanand** [comment]
Hi @rob-p 

Before I answer your question and layout my logic, I want to mention that I am **_not_** suggesting fastp is not doing its job or working incorrectly.

Now to my answer(s) and logic:
1. With fastp, I am not sure if adapter trimming happens first and then quality trimming OR vice-versa. I could not find info on this from their README and **_I could be wrong here with my next line_** - [Based on Figure 1 of this paper, it looks to me as though quality trimming is done before adapter trimming](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6129281/figure/bty560-F1/)

-  [To quote Brian Bushnell (author of BBTools)]( http://seqanswers.com/forums/showpost.php?p=140819&postcount=5), 

> It's best to do adapter-trimming first, then quality-trimming, because if you do quality-trimming first, sometimes adapters will be partially trimmed and become too short to be recognized as adapter sequence. When you run BBDuk with both quality-trimming and adapter-trimming in the same run, it will do adapter-trimming first, then quality-trimming.

2.  I very well know that the advantage of using fastp is that it can do adapter trimming, etc in a automatic fashion - no need to provide external sequences (example adapter sequences). Yes, I know one can also provide a fasta file of adapters and fatsp will work off it. There are many fatsp issues in GH about adapters:

- [fail to detect adpaters automatically](https://github.com/OpenGene/fastp/issues/222  and https://github.com/OpenGene/fastp/issues/205)

- [incorrect automatic adapter detection](https://github.com/OpenGene/fastp/issues/240)

- [inconsistent behavior with different runs](https://github.com/OpenGene/fastp/issues/231)

3. When I see the above, I am bit skeptical using fastp for qc/adapter trimming. 

After lot of trials with bbduk and fastp, I have decided to use bbduk and bbmap for my high throughput analysis. Below I explain my reasoning behind those choices: 

1. I use bbduk with adapter trimming and quality trimming in same command line - also, the adapters.fa file that ships with BBTools can be used in all runs

2. After bbduk, I then pass those filtered_trimmed_reads via bbmap to remove contaminants - 
- You have alluded to the importance of removing contaminants [in this post](https://github.com/COMBINE-lab/salmon/issues/160#issuecomment-334762498), 
>However, the other thing to try is simply to align one of these samples to the genome with a tool like STAR or HISAT2 and look at their mapping rate to known features. If it's similar, then the other reads could be accounted for by e.g. intron retention or even contamination. Finally, [@vals has an excellent series of blog posts on investigating and addressing low mapping rates](http://www.nxn.se/valent/2017/9/18/low-mapping-rate-5-human-dna-contamination)
- bbmap Command ([based of this biostars post](https://www.biostars.org/p/143019/#210890)):
`bbmap.sh in=read_1.fq.gz ref=rRNA_Chlor_Mito.fa maxindel=1 minid=0.95 outu=clean_read_1.fq.gz nodisk`
- Strategy:
`use the rRNA+Mito+Chloroplast file and map the reads using bbmap, then collect the unmapped reads (clean_read_1.fq.gz) for my downstream analysis`

Hope that helps.

**Comment by kokyriakidis** [comment]
Hi @tamuanand !

Can you share the full commands you use for RNA-Seq data? DO you use similar commands for DNA-Seq data?

**Comment by tamuanand** [comment]
Hi @kokyriakidis 

I only use all the commands for bulk RNA SEQ analysis with salmon for quant

**Comment by kokyriakidis** [comment]
Hi @tamuanand !

I mean the commands from bbtools that your are reffering above, to preprocess the data!

**Comment by tamuanand** [comment]
Hi @kokyriakidis 

It is there - probably obscured by the link (to biostar

```bbmap usage as detailed on the below GH post in a different forum```

- https://github.com/ewels/MultiQC/issues/1146#issuecomment-607993048

```bbduk usage after using bbmap on the below GH post in a different forum```

- https://github.com/ewels/MultiQC/issues/1146#issuecomment-607980076

**Comment by kokyriakidis** [comment]
@tamuanand 
Thank you very much!

**Comment by tamuanand** [comment]
Thanks @rob-p  I am glad you and others have found it useful. The actual bbmap.sh and bbduk.sh commands for SE data are in the links to Phil Ewels' multiqc GH. 

Just like salmon indexing kmer size choice, one can tinker with the **_```k, hdist, minq and other parameters```_** of bbduk depending on how good/bad the data is. Needless to state, bbduk is the swiss-army-knife for sequence reads quality assessment with whole range of parameters to tweak 

https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbduk-guide/ suggests
![image](https://user-images.githubusercontent.com/8467214/78302368-a3695980-7508-11ea-990d-4b6e008e3f07.png)
