### ISSUE TITLE
how to find out salmon version used for indexing

### ISSUE THREAD

**Issue by tamuanand** [COMBINE-lab/salmon#498]
Hi @rob-p @k3yavi 

A question (or feature enhancement); When I am doing salmon indexing, is there a metadata file that will capture info about the salmon version used for indexing.

Why am I asking this: I am developing a high throughput pipeline (with bbmap, bbduk, etc and then salmon) where I use salmon 1.1.0 for quantification - in this scenario, independent users have to build their own salmon indices and I want to trap/capture the situation where the user has used a different salmon version of indexing.

Thanks

**Comment by tamuanand** [comment]
Hi @rob-p 

I see that you have added this as a feature request and you have added it in develop.

A suggestion - would it be better to have this captured as a single line item in txt file called indexVersion.txt and within that it would have Line 1 as 1.1.0 (or 1.2.0 as the case many be).

Thanks for looking into this.

**Comment by rob-p** [comment]
@tamuanand,

  Right now, I added the code to dump the _salmon_ version into versionInfo.json.  Which is a standard json file that goes in the index directory.  Actually, that file already contains an index version key, which is simply a number that is incremented every time there is a change made that alters the binary representation of the index on disk.  That is particularly useful because not every salmon version requires re-building the index.

  Regarding the feature I've added.  It's fairly standard practice for us to put information that is meant to be read by both humans and machines (scripts, R packages downstream, etc.) into a JSON file.  This makes it easy to access it simply from many languages, and to have _some_ (but not too much) structure to this data.  There are even slick command line tools for pulling info out of JSON files (like [jq](https://stedolan.github.io/jq/)).  If there is a strong reason that you need the _salmon_ version in its own text file, I'm willing to oblige and duplicate the information there.  Just let me know.

**Comment by tamuanand** [comment]
Hi @rob-p 

A json file would be fine - I was just suggesting a text file.  I myself use jq.  I am assuming I will find this information on salmon index version  inside 'versionInfo.json" file. 

Would you know when this update will be available?

On a different note - is salmon 1.2.0 available - see attached screenshot from the "readthedocs" page. I checked the releases and could only see 1.1.0 

![image](https://user-images.githubusercontent.com/8467214/77860517-d399bb00-71dd-11ea-9f07-d8173789cd6f.png)

**Comment by rob-p** [comment]
Hi @tamuanand,

  I expect `1.2.0` to land _very_ soon.  We'll probably get it out this week (but if not, then it would definitely be out next week).  Unless there is a strong need for the text file, I anticipate we'll stick with the json, as this is more consistent with how most of the other metadata files are structured.

  Regarding the documentation, I think this was due to a switch to the "default" documentation being "latest" (I believe @k3yavi was having some trouble forcing a rebuild for some alevin-related documentation and this fixed it).  The [stable](https://salmon.readthedocs.io/en/stable/salmon.html) RTD links still points at 1.1.0, but thanks for bringing up this behavior.  I think it's probably ok to have latest point to `develop`, but the default doc page should probably `stable`.

**Comment by tamuanand** [comment]
Thanks @rob-p 

Json is fine for outputting the salmon index version that was used during indexing.  Are you planning on something like below or will there be a new object in the json?
```
versionInfo.json
{
    "indexVersion": 1.1.0,
    "hasAuxIndex": false,
    "auxKmerLength": 31,
    "indexType": 1
}
```

**Comment by rob-p** [comment]
Hi @tamuanand,

The `versionInfo.json` file will look like : 

```
{
    "indexVersion": 5,
    "hasAuxIndex": false,
    "auxKmerLength": 31,
    "indexType": 2,
    "salmonVersion": "1.2.0"
}
```

The new field is `salmonVersion`.  Otherwise, this `versionInfo.json` is identical to those in version 1.0.0 and 1.1.0.  Note, the _new_ field is `salmonVersion`.  The `indexVersion` field has been around for a while and is incremented when the binary representation of the index on disk changes (which does not happen with each salmon version).

**Comment by tamuanand** [comment]
@rob-p Thanks for adding this to salmon 1.2.0
