### ISSUE TITLE
"you are using an empty matrix" error, seemingly during bias correction (--biasCorrect)

### ISSUE THREAD

**Issue by jmerkin** [COMBINE-lab/salmon#5]
I'm running salmon v.4 (downloaded and compiled today) on gencode v22 and got the following error:

Performing PCA decomposition
salmon: /home/merkija1/software/salmon-0.4.0/include/eigen3/Eigen/src/Core/Redux.h:202: static Eigen::internal::redux_impl<Func, Derived, 3, 0>::Scalar Eigen::internal::redux_impl<Func, Derived, 3, 0>::run(const Derived&, const Func&) [with Func = Eigen::internal::scalar_sum_op<double>; Derived = Eigen::Block<const Eigen::Matrix<double, -1, -1>, -1, 1, true>; Eigen::internal::redux_impl<Func, Derived, 3, 0>::Scalar = double]: Assertion `size && "you are using an empty matrix"' failed.
Aborted

The command I ran is:
salmon-0.4.0/src/salmon quant --index gencode.v22.index_0.4.0/ --mates1 <(gunzip -c r1_fq1.gz r1_fq2.gz --mates2 <(gunzip -c r2_fq1.gz r2_fq2.gz ) --output $OUTPUT_DIR --biasCorrect --threads 4 --geneMap gencode.v22.annotation.nochr.gtf --libType "ISF"

If I remove the --biasCorrect flag, it runs without error.

**Comment by rob-p** [comment]
Hi Jason,

  Yes, I apologize for this bug.  What happened is that in v0.4.0 we changed the output format (dropping FPKM), but I forgot to appropriately modify the reading of the input file in the post-hoc bias correction.  The bug should be fixed by commit 88f09218e65fe34884dbc17ecc6cf0ebc8efce8c.  Could you build this commit and see if this resolves the issue for you (Ido ran into a similar problem on the Google-group, and this seems to have fixed it).  If this fixes the issue for you, I'll roll it into a minor version bump.  Hopefully, we're moving toward getting rid of the post-hoc bias correction entirely, as more and more bias is being accounted for directly in the inference procedure.

Thanks,
Rob

**Comment by jmerkin** [comment]
Hi Rob,

I'm compiling it now. I ran into a different issue with this commit that took a little bit to track down. It looks like you switch from jellyfish 2.1.3 to 2.2.0. I was running into an issue with some undefined values, eraise and a few associated classes from jellyfish include/jellyfish/err.hpp that were present in 2.1.3 and seemingly removed in 2.2.0. Making it use 2.1.3 instead of 2.2.0 let it get past that point in the compilation (still ongoing). I'll get back to you about the impact of that commit.

**Comment by jmerkin** [comment]
Hi Rob,

Finished compiling and it no longer throws that error. Thanks for the help!

**Comment by rob-p** [comment]
Strange!  I should still be using Jellyfish 2.1.3 (https://github.com/COMBINE-lab/salmon/blob/master/CMakeLists.txt#L355).  I'm not sure why it was fetching 2.2.0 for you.  Anyway, I'm glad that this seems to resolve the error with the bias correction --- thanks for reporting back here.  I'll probably roll this and a few other small changes into a v0.4.1 soon.

**Comment by jmerkin** [comment]
Hm. I had to tweak a few bits in the cmake file for it to compile here due
to the firewall I'm behind (generally no ftp access) so it must have been a
side effect of that. I tried to make sure I was starting from a clean slate
to verify before posting, but guess I wasn't.

Jason

**Comment by rob-p** [comment]
No worries.  I've had issues with grabbing Jellyfish from the existing URL depending on the network setup as well.  I may just copy that tarball to a GitHub artifact an have the makefile pull from GitHub instead.

--Rob
