### ISSUE TITLE
question on indexing with salmon v1.2.0

### ISSUE THREAD

**Issue by tamuanand** [COMBINE-lab/salmon#504]
Hi @rob-p 

I have a question on indexing with salmon 1.2.0

This is the first time I am doing the indexing with salmon on my dataset and this is how `versionInfo.json' looks

```
{
    "indexVersion": 5,
    "hasAuxIndex": false,
    "auxKmerLength": 17,
    "indexType": 2,
    "salmonVersion": "1.2.0"
}

```

Question: Since I am doing the indexing for the first time, why does it say `indexVersion:5` and `indexType:2`

Shouldn't they be both saying 1  - or am I misreading anything?

**Comment by rob-p** [comment]
Hi @tamuanand,

  Nope; these values are right.  The `indexVersion` is a global identifier with respect to previous versions of salmon.  It is a global number that is incremented each time (a) a backward-incompatible change to the index is introduced or (b) a fundamentally new piece of information is contained in the index.  This field took a value of `1` way back when we started versioning the salmon index a number of years ago, and version `1` was based on the RapMap index (rather than pufferfish like the current one).  This is simply a global identifier that we can use internally to determine whether the version of salmon reading this index can be expected to make use of it.

The other field `indexType` corresponds to the value from an internal enumeration used in the salmon code.  Over the years (since it was first released in 2014), salmon has used a number of different data structures for its underlying index.  First, it used a modified version of the FMD index that BWA is based upon, then, it used the RapMap index (based upon a sparse hash map and an uncompressed suffix array), and now it uses the pufferfish index.  This `indexType` filed just records the type of this index.  In modern (post 1.0.0) versions of salmon, the pufferfish index (`2`) is the only valid version.

There's a lot of history to these values, but they all make sense internally within salmon, which is how the contents of this file are primarily used (i.e. to make sure there is compatibility between the version of salmon being run and the index we are trying to consume).  Hopefully, this description clears things up a bit.

Best,
Rob

**Comment by tamuanand** [comment]
Thanks @rob-p 

I was thinking I got something wrong. I will close this.
