### ISSUE TITLE
Quantification takes very long

### ISSUE THREAD

**Issue by nickhir** [COMBINE-lab/salmon#516]
I  noticed that the quantification of my reads took a very long time (>10h).

I generated the index in accordance with these instructions:
https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/
(I used the human genome hg19)

I am using CentOs 7 and I have access to 16GB of RAM and to 8 threads.

Here are some informations about the run:
"salmon_version": "1.2.0",
    "index": "04_genome_data/salmon_index/salmon_index/",
    "gcBias": [],
    "threads": "8",
    "libType": "A",
    "mates1": "02_rawreads//Adenocarcinoma/patient001/fastq/S0216_1.fastq.gz",
    "mates2": "02_rawreads//Adenocarcinoma/patient001/fastq/S0216_2.fastq.gz",
    "validateMappings": [],
    "output": "03_DEG/salmon//Adenocarcinoma/patient001",
    "auxDir": "aux_info"

"num_bootstraps": 0,
    "num_processed": 19848610,
    "num_mapped": 11112281,
    "num_decoy_fragments": 1953200,
    "num_dovetail_fragments": 33267,
    "num_fragments_filtered_vm": 2134945,
    "num_alignments_below_threshold_for_mapped_fragments_vm": 26561460,
    "percent_mapped": 55.98518485677335,
    "call": "quant",
    "start_time": "Wed Apr 22 12:53:21 2020",
    "end_time": "Thu Apr 23 00:14:34 2020"`

Is there something obvious I am doing wrong or do you have an idea why it takes so long? 

Furthermore, I was wondering if a mapping rate of 56% is considered "okay"? 
I didnt trim any reads, because the quality score was high throughout all bases.

Any help is appreciated!

**Comment by rob-p** [comment]
That is totally unexpected.  There is nothing obvious from the output above.  Could you share the output directory itself?  It will also contain a log file with time stamps so we can see where the time went.

**Comment by rob-p** [comment]
Thanks for the quick response yourself :).  Ok, so it looks like there is just an ungodly amount of time between this line:
```
[2020-04-22 13:00:24.946] [jointLog] [info] Automatically detected most likely library type as ISR
```

and this one

```
[2020-04-23 00:06:31.287] [jointLog] [info] Thread saw mini-batch with a maximum of 1.06% zero probability fragments
```

This is an absolutely outrageous amount of time spent on trying to align ~19M reads.  Was there any other console output that is missing here?  

However, even other parts of the run are outrageously slow.  For example

```
[2020-04-23 00:07:47.416] [jointLog] [info] Thread saw mini-batch with a maximum of 1.24% zero probability fragments
[2020-04-23 00:10:07.526] [jointLog] [info] Computed 414,258 rich equivalence classes for further processing
```

literally minutes passed between these two lines but almost nothing is done in this time.  This makes me think there is, perhaps, a resource problem.  Is this a shared machine?  Was someone else, perhaps, using all of the cores?

I assume the data can't be easily shared, right?  I could see how long it takes to run on a different machine.  Otherwise, do you have a different machine on which you could run?

**Comment by nickhir** [comment]
To the best of my knowledge this is not a shared machine, but a private VM. However, I just ran this sample on my own home computer and it finished in no time, so there is definitely a problem at my end. Ill talk to my system manager.
Im sorry for any trouble I caused and thank you very much for taking the time to answer!
