### ISSUE TITLE
Correct target in salmon for alignment based mode

### ISSUE THREAD

**Issue by crmclean** [COMBINE-lab/salmon#520]
Good Afternoon,

I hope this message finds you well. 

I am having a hard time running salmon version 0.14.1 downloaded via bioconda. I am trying to count my reads using alignment-based mode. Whenever I run the program, I get similar error messages to [issue 104](https://github.com/COMBINE-lab/salmon/issues/104). Here is the command I am running:

salmon quant -t trimmed_fasta/SRR1810204_1.trim.fastq -l A -a results/bam_files/SRR1810204_1.trim.fastq.bam -o salmon_test

trimmed_fasta/SRR1810204_1.trim.fastq is a fastq sample that I've obtained following trimmomatic and contains the forward strands of the data. 

results/bam_files/SRR1810204_1.trim.fastq.bam is the bam file following bwa alignment of the fastq file here and its reverse strand to a reference database. 

Could the issue be that I am not using both forward and reverse strands in the target argument for salmon since they were both used to generate the alignment file? I tried to look at the docs for guidance on the best course of action, and I had a hard time finding info.

All help would be very much appreciated.

All the best,
Craig

**Comment by rob-p** [comment]
Hi Craig,

  Thank you for the details you've provided.  The problem is that you are passing the reads, rather than the transcriptome, to the `-t` option of salmon.  You should pass to salmon the transcriptome file you used to generate the BWA index.

Also, while not related to this issue directly, it's worth noting we highly recommend people always use the latest version of salmon (now 1.2.1), rather than an older version.

Best,
Rob

**Comment by crmclean** [comment]
Dear Rob,

Thank you so much for your guidance. I appreciate you taking the time to help me. I was able to run salmon, no problem.

All the best,
Craig
