### ISSUE TITLE
Estimated counts discrepancy from different database 

### ISSUE THREAD

**Issue by silvernano** [COMBINE-lab/salmon#525]
Hi,

I used salmon to build indexes from both ENSEMBL and NCBI database. For the same transcript, I got totally different estimated counts (huge difference). I understand there are differences between databases, but since the counts differences are so large, I want to compare how these two indexes were used in the quantifying step. Is there a way to check how Salmon mapping/quantifying a specific transcript? Except output mapping information, may I set the location/position that I want to map in the quantify step? Because my guess is the different results caused by positional differences on the human genome for the same transcript among different databases.  Thank you!

**Comment by rob-p** [comment]
Hi @silvernano,

  I'm not sure that I understand this part of your question:

> Except output mapping information, may I set the location/position that I want to map in the quantify step? 

You can output the mapping information that salmon uses internally with the `--writeMappings` flag, which will output a SAM file giving the mappings that salmon uses internally.  However, this will include all relevant multimappings.  One question may be, for the transcript where there is a discrepancy between the databases, _where_ do the reads go?  Are there other (sequence similar) transcripts that exist in e.g. the ENSEMBL database that don't exist in the NCBI database?  Generally, ENSEMBL tends to include more, and so it may be the case that in the ENSEMBL database there is a better match for the reads, while in the NCBI database, the transcript showing the discrepancies is the best locus to assign the reads.

**Comment by silvernano** [comment]
Hi @rob-p,

Thank you for your explanation. The NCBI database actually gave much more counts in my case, that's why I want to take a close look at the details. I tried to add --writeMappings, but no SAM file was found in the output folder. Since the SAM file contains all the information, and I'm only interested in 1 specific transcript, can I output relevant mapping information for only interested transcript? Thank you!

**Comment by rob-p** [comment]
Hi @silvernano,

> I tried to add --writeMappings, but no SAM file was found in the output folder

the implicit argument to `--writeMappings` is stdout, so if you didn't give it an argument, that is likely why you didn't see a SAM file.  You should do something like `--writeMappings=path_to_desired_sam_file`.

> Since the SAM file contains all the information, and I'm only interested in 1 specific transcript, can I output relevant mapping information for only interested transcript?

There is no way to do that directly within salmon (i.e. the filtering of the mappings that are produced).  However, if you dump the SAM file, you should be able to easily `grep` for just the target of interest, to extract only the SAM records that map to this.

> The NCBI database actually gave much more counts in my case

Though I can't say what is happening without looking at the data, this observation is consistent with my hypothesis above.  It's possible (likely) that ENSEMBL annotates more transcripts, and in the ENSEMBL quantifications this transcript (let's call it X) has fewer reads, because there is some sequence-similar transcript Y that better explains the reads.  However, in the NCBI annotation, the Y transcript doesn't exist, and so X is the best explanation for the reads (and so the number of assigned reads is higher).  The SAM files from both runs should help you figure this out, but you will need to determine the other transcript (i.e. Y) that reads are going to in the ENSEMBL case.

**Comment by silvernano** [comment]
Hi @rob-p,

I will start with the SAM file. Thank you for your help!

**Comment by silvernano** [comment]
Hi @rob-p,

Another issue is I used an old version of SALMON (<1.0.0), should I use the latest version instead? Will the latest version give me more similar reads between two database? Thank you.

**Comment by rob-p** [comment]
@silvernano,

  I would certainly strongly recommend to use the latest version of salmon if you can.  There have been substantial improvements in version 1.0.0 and beyond.  This may somewhat mitigate the discrepancies you see.  I'm not certain, however, that it will address them entirely, since I think they are due to the "background" set of genes being used for quantification.  Nonetheless, I do think it's worth running the analysis with the latest version to see how things change.

**Comment by silvernano** [comment]
Hi @rob-p ,
I used the latest version of salmon, and you were right, the difference between two database decreased a little bit, but still affect my downstream analysis. So I'm wondering should I change or add some options when run salmon quantification step to count for the different reads between two databases? Now I'm using the same script for both NCBI and ENSEMBL quantification except using related index file as below:

./salmon-latest_linux_x86_64/bin/salmon quant -i index -l A -r SRR.fastq -p 8 --numBootstraps 100 --validateMappings --writeMappings=../mapinfo.sam -o pat1 

As you mentioned the NCBI find the best locus to assign reads and ENSEMBL match the reads better, so should I use different parameters when quantify reads for these two databases? Thank you.

**Comment by rob-p** [comment]
Hi @silvernano,

  Though alignment stringency parameters can have an effect here, the problem of comparing the abundance of a specific transcript within the context of different annotations is more fundamental.  That is, apart from the transcript of interest, the "background" of related transcripts may be different.

  Consider the following case:

You have an annotation with 2 transcripts annotated for your gene:

```
[A, B, C]
[A,C]
```

Where `A`, `B`, and `C` are exons and the `[A,B,C]` notation means the transcript is exon `A`, followed by `B`, followed by `C`.

Now, imagine that in annotation 2, you just have:

```
[A,C]
```

That is, the other isoform `[A, B, C]` is missing from annotation 2.

Now, imagine that, in reality, `[A,B,C]` is highly expressed in your sample and `[A,C]` is lowly expressed.

Under annotation 1, you get (correct) high expression for `[A,B,C]` and low expression for `[A,C]`.  However, in annotation 2, since you still have to describe the `A` reads and the `C` reads, you get high expression for `[A,C]` since the reads contained within `A` and within `C` still map well there — the reads that map to `B` and to the `A-B` and `B-C` junction will likely just go un-mapped (which explains a difference in mapping rate).

Now if you compare `[A,C]` across databases ... you will see big differences.  This is not really related to the alignments that are observed, but rather how the data (reads) must be explained conditioned on the transcriptome (annotation) you have available.  In other words, in loci with substantial unannotated transcription, the annotation used can definitely have a considerable effect on the quantification results.  How to best assess, detect, and mitigate these effects is an active area of research, but I can point you at papers like [this](https://www.life-science-alliance.org/content/2/1/e201800175) and [this](https://www.cell.com/cell-systems/pdfExtended/S2405-4712(19)30381-3).

**Comment by silvernano** [comment]
Hi @rob-p,

Thank you so much for your detailed explanation!
