### ISSUE TITLE
Salmon indexing on UCSC intron.fa files fail for hg19

### ISSUE THREAD

**Issue by njbernstein** [COMBINE-lab/salmon#53]
Hi all,

So I'm having a similar problem to whats found in issue https://github.com/COMBINE-lab/salmon/issues/49.  I'm want to see how much intron RNA is quantified in my experiment, but it seems like the number of "transcripts" (i.e. introns) from the fasta is too many. Any ideas as to how to approach this?

Best

```
/labseq/tools/SalmonBeta-0.5.0_DebianSqueeze/bin/salmon index -t /labseq/Genomes/introns/hg19.introns.fasta   -i /labseq/Genomes/salmon/SalmonBeta-0.5.0_DebianSqueeze.quasi.intron/  --type quasi 
```
```
Version Info: ### A newer version of Salmon is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases 
contains **important bug fixes**; please upgrade at your
earliest convenience.
###
index ["/labseq/Genomes/salmon/SalmonBeta-0.5.0_DebianSqueeze.quasi.intron/"] did not previously exist  . . . creating it
[2016-03-28 13:52:29.407] [jointLog] [info] computeBiasFeatures( {[/labseq/Genomes/introns/hg19.introns.fasta] , /labseq/Genomes/salmon/SalmonBeta-0.5.0_DebianSqueeze.quasi.intron/bias_feats.txt, 1, 24)

readFile: /labseq/Genomes/introns/hg19.introns.fasta, 
file /labseq/Genomes/introns/hg19.introns.fasta: 
processed 659300 transcripts (4515) transcripts/snscripts/sipts/s transcripts/sts/s
[2016-03-28 13:54:55.658] [jointLog] [info] building index
RapMap Indexer

[Step 1 of 4] : counting k-mers
counted k-mers for 650000 transcriptsElapsed time: 128.964s

Clipped poly-A tails from 0 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 5.40482s
Writing sequence data to file . . . done
Elapsed time: 40.1748s
[info] Building 64-bit suffix array (length of generalized text is 4128215243 )
Building suffix array . . . 
success
saving to disk . . . done
Elapsed time: 358.792s
done
Elapsed time: 3065.92s
processed 3810000000 positionssalmon: /home/vagrant/salmon/external/install/include/sparsehash/internal/densehashtable.h:782: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const long unsigned int, rapmap::utils::SAInterval<long int> >; Key = long unsigned int; HashFcn = rapmap::utils::KmerKeyHasher; ExtractKey = google::dense_hash_map<long unsigned int, rapmap::utils::SAInterval<long int>, rapmap::utils::KmerKeyHasher, std::equal_to<long unsigned int>, google::libc_allocator_with_realloc<std::pair<const long unsigned int, rapmap::utils::SAInterval<long int> > > >::SelectKey; SetKey = google::dense_hash_map<long unsigned int, rapmap::utils::SAInterval<long int>, rapmap::utils::KmerKeyHasher, std::equal_to<long unsigned int>, google::libc_allocator_with_realloc<std::pair<const long unsigned int, rapmap::utils::SAInterval<long int> > > >::SetKey; EqualKey = std::equal_to<long unsigned int>; Alloc = google::libc_allocator_with_realloc<std::pair<const long unsigned int, rapmap::utils::SAInterval<long int> > >; google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]: Assertion `table' failed.


Aborted
```

head of fasta file:
```
>uc001aaa.3_intron_0_0_chr1_12228_f| chr1:12227-12612
GTAAGTAGTGCTTGTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAGCTGGACCCCTACCTGCCGTCTGCTGCCATCGGAGCCCAAAGCCGGGCTGTGACTGCTCAGACCAGCCGGCTGGAGGGAGGGGCTCAGCAGGTCTGGCTTTGGCCCTGGGAGAGCAGGTGGAAGATCAGGCAGGCCATCGCTGCCACAGAACCCAGTGGATTGGCCTAGGTGGGATCTCTGAGCTCAACAAGCCCTCTCTGGGTGGTAGGTGCAGAGACGGGAGGGGCAGAGCCGCAGGCACAGCCAAGAGGGCTGAAGAAATGGTAGAACGGAGCAGCTGGTGATGTGTGGGCCCACCGGCCCCAGGCTCCTGTCTCCCCCCAG
>uc001aaa.3_intron_1_0_chr1_12722_f| chr1:12721-13220
GTGAGAGGAGAGTAGACAGTGAGTGGGAGTGGCGTCGCCCCTAGGGCTCTACGGGGCCGGCGTCTCCTGTCTCCTGGAGAGGCTTCGATGCCCCTCCACACCCTCTTGATCTTCCCTGTGATGTCATCTGGAGCCCTGCTGCTTGCGGTGGCCTATAAAGCCTCCTAGTCTGGCTCCAAGGCCTGGCAGAGTCTTTCCCAGGGAAAGCTACAAGCAGCAAACAGTCTGCATGGGTCATCCCCTTCACTCCCAGCTCAGAGCCCAGGCCAGGGGCCCCCAAGAAAGGCTCTGGTGGAGAACCTGTGCATGAAGGCTGTCAACCAGTCCATAGGCAAGCCTGGCTGCCTCCAGCTGGGTCGACAGACAGGGGCTGGAGAAGGGGAGAAGAGGAAAGTGAGGTTGCCTGCCCTGTCTCCTACCTGAGGCTGAGGAAGGAGAAGGGGATGCACTGTTGGGGAGGCAGCTGTAACTCAAAGCCTTAGCCTCTGTTCCCACGAAG
>uc010nxr.1_intron_0_0_chr1_12228_f| chr1:12227-12645
GTAAGTAGTGCTTGTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAGCTGGACCCCTACCTGCCGTCTGCTGCCATCGGAGCCCAAAGCCGGGCTGTGACTGCTCAGACCAGCCGGCTGGAGGGAGGGGCTCAGCAGGTCTGGCTTTGGCCCTGGGAGAGCAGGTGGAAGATCAGGCAGGCCATCGCTGCCACAGAACCCAGTGGATTGGCCTAGGTGGGATCTCTGAGCTCAACAAGCCCTCTCTGGGTGGTAGGTGCAGAGACGGGAGGGGCAGAGCCGCAGGCACAGCCAAGAGGGCTGAAGAAATGGTAGAACGGAGCAGCTGGTGATGTGTGGGCCCACCGGCCCCAGGCTCCTGTCTCCCCCCAGGTGTGTGGTGATGCCAGGCATGCCCTTCCCCAG
>uc010nxr.1_intron_1_0_chr1_12698_f| chr1:12697-13220
GTGAGTGTCCCCAGTGTTGCAGAGGTGAGAGGAGAGTAGACAGTGAGTGGGAGTGGCGTCGCCCCTAGGGCTCTACGGGGCCGGCGTCTCCTGTCTCCTGGAGAGGCTTCGATGCCCCTCCACACCCTCTTGATCTTCCCTGTGATGTCATCTGGAGCCCTGCTGCTTGCGGTGGCCTATAAAGCCTCCTAGTCTGGCTCCAAGGCCTGGCAGAGTCTTTCCCAGGGAAAGCTACAAGCAGCAAACAGTCTGCATGGGTCATCCCCTTCACTCCCAGCTCAGAGCCCAGGCCAGGGGCCCCCAAGAAAGGCTCTGGTGGAGAACCTGTGCATGAAGGCTGTCAACCAGTCCATAGGCAAGCCTGGCTGCCTCCAGCTGGGTCGACAGACAGGGGCTGGAGAAGGGGAGAAGAGGAAAGTGAGGTTGCCTGCCCTGTCTCCTACCTGAGGCTGAGGAAGGAGAAGGGGATGCACTGTTGGGGAGGCAGCTGTAACTCAAAGCCTTAGCCTCTGTTCCCACGAAG
>uc010nxq.1_intron_0_0_chr1_12228_f| chr1:12227-12594
GTAAGTAGTGCTTGTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAGCTGGACCCCTACCTGCCGTCTGCTGCCATCGGAGCCCAAAGCCGGGCTGTGACTGCTCAGACCAGCCGGCTGGAGGGAGGGGCTCAGCAGGTCTGGCTTTGGCCCTGGGAGAGCAGGTGGAAGATCAGGCAGGCCATCGCTGCCACAGAACCCAGTGGATTGGCCTAGGTGGGATCTCTGAGCTCAACAAGCCCTCTCTGGGTGGTAGGTGCAGAGACGGGAGGGGCAGAGCCGCAGGCACAGCCAAGAGGGCTGAAGAAATGGTAGAACGGAGCAGCTGGTGATGTGTGGGCCCACCGGCCCCAG
```

I know it might not be doable in this manner based off what I read in issue #49  but any help would be much appreciated

**Comment by rob-p** [comment]
The problem you're encountering here seems to be a result of a memory allocation error.  Basically, building the index requires considerably more memory than actually storing it (and using it for quantification).  One option would be to try and build the index with smaller k-mers, which should require less memory.  It looks like you successfully indexed 3.8 / 4.1 billion nucleotides, so you're reasonably close to done.  The other option will only work with the newest commits of Salmon (i.e. you'd have to clone the repository and build) --- however, they allow building a perfect hash index rather than using the google dense hash we use by default.  The perfect hash construction uses an external memory algorithm, and it takes considerably less memory to build the index.  A pre-compiled binary exposing this option should also be available later this week.

**Comment by njbernstein** [comment]
Great! Thanks for the help and timely response. I'll try that later today.

**Comment by rob-p** [comment]
No problem :).  If you have trouble building the newer versions from source or if this doesn't resolve the issue for you for some reason (it should!), I have a large memory machine where I'd be happy to build the index for you as a temporary solution.

**Comment by njbernstein** [comment]
Great! Thanks!

**Comment by njbernstein** [comment]
Hi Rob,

I don't have git (don't have root access on the red hat server im on). I downloaded the salmon-master.zip, and then tried running the following:

```
[bernsteinnj@lngnode1 salmon-master]$ cmake . 

-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:69 (message):
  Salmon requires g++ 4.7 or greater.
```

I'm trying now with -k 27 with the original build I had. Keep you updated.

Best

**Comment by rob-p** [comment]
Hi Nick,

  If that doesn't work, you can use [this](https://github.com/COMBINE-lab/salmon/files/197982/SalmonBeta-0.6.5-pre_CentOS5.tar.gz) salmon executable to try the perfect hash indexing.  If you pass the `--perfectHash` flag when indexing, it will use the minimum perfect hash rather than Google's dense hash.

**Comment by njbernstein** [comment]
Should I use `--perfectHash` for all subsequent indexing, or only when it blows up my memory? Probably more nuanced than that, but if an explanation wouldn't be too much to ask that'd be great as to the benefits and disadvantages of the `perfectHash` vc `Google's dense hase`

**Comment by rob-p** [comment]
Hi Nick,

  No problem at all; sorry for not providing a better explanation (I'm planning on writing one up for when this feature is listed in the next official release).  In terms of strategy, my recommendation would be to use the default (the `dense hash`) unless indexing memory becomes a problem.  The main differences are the following:

  * The perfect hash uses an external memory algorithm to construct the hash function, and so requires less memory.
  * Because the perfect hash function is built in external memory, **construction** of the hash using this data structure is sower.  I don't have longitudinal benchmarks, but it is somewhere between 2 and 5x slower to populate the perfect hash than the dense hash.
  *  Once constructed, the perfect hash is *considerably* smaller, and so quantification on an index built using a perfect hash will require only ~50% of the memory that is required when using a dense hash.  Obviously if you're quantifying on the same machine that was able to build the index, this isn't a problem.  However, if you're shipping the index to smaller memory computers, then this is something to consider.
  * The performance difference in terms of mapping speed is very minimal; the minimum perfect hash can be 5-10% slower than the dense hash, but this difference is usually only a matter of seconds.  Also, the total runtime difference can be even less since the smaller perfect hash can be read more quickly from disk than the larger dense hash.

So, the standard recommendation would be use the default unless you run into memory problems building the index; in that case, try enabling the `--perfectHash` flag.

**Comment by njbernstein** [comment]
Great! Thanks for the info.

**Comment by rob-p** [comment]
I think this issue is resolved, but let me know if I'm wrong about that.
