### ISSUE TITLE
Cannot set minScoreFraction

### ISSUE THREAD

**Issue by apinto-helomics** [COMBINE-lab/salmon#549]
Hello,

I recently updated to 1.3.1 and I have been trying to set minScoreFraction to 0.7. However when i try to set this value I get an error stating it is an unknown option.

Anyone else have this issue?

**Comment by hiraksarkar** [comment]
Hi, 

Can you please share the full command you are running. 

Thanks

**Comment by apinto-helomics** [comment]
```
/salmon/bin/salmon quant -p 2 -t Homo_sapiens.GRCh38.transcripts.generated.gffread.fa -l A -a SL71_transcriptomSAMAligned.sorted.out.bam -o quants/SL71_min_fraction_0.7 --minScoreFraction
```

**Comment by rob-p** [comment]
Hi @apinto-helomics,

  Thank you for the report and the quick follow up.  The problem is that the `—minScoreFraction` option is not supported in _alignment_-based mode.  It is used in our default (selective-alignment) mode, for our own internal alignment scoring to determine when a read’s quality is sufficiently high to consider it mapped (rather than to consider its seeds as spurious hits).  However, in alignment-based mode, that determination has already been made based on the parameters passed to the upstream aligner (and allowing a different `—minScoreFraction` would require re-scoring alignments and knowing the original scoring function used to produce them).  Thus, if you are running salmon in _alignment-based_ mode, you need not (can not) use the `—minScoreFraction` flag.  However, it is, of course, meaningful and potentially useful in selective-alignment based mode when you let salmon, itself, do the mapping.

—Rob

**Comment by apinto-helomics** [comment]
Thank you! I thought it might have been that.
