### ISSUE TITLE
unrecognised option '--validateMappings'

### ISSUE THREAD

**Issue by Cold7** [COMBINE-lab/salmon#563]
Dear salmon team.

I'm using salmon v1.3.0 and I've tried to ran the quantification using the command as is in the web page

` salmon quant -i mus_musculus_index -l A -1 ../../output_paired_PVI18_1.fastq.gz -2 ../../output_paired_PVI18_2.fastq.gz -p 4 --validateMappings -o quants/`

but it give me the error 

Exception : [unrecognised option '--validateMappings']. Exiting.

at first look my line doesn't seems to be bad-formatted, so can you help me with the error please

Thanks

**Comment by rob-p** [comment]
Hi @Cold7,

  Thanks for the report.  So, could you provide the full output that you get on the terminal when you run this?  Your command line looks fine to me.  Since version 1.0.0, `--validateMappings` has become the default behavior and so this flag technically has no effect (it is marked as "deprecated").  However, the argument parser should _absolutely_ accept it, and it's not clear to me why it might be giving you this error.  The full output from the terminal may help to diagnose this.

**Comment by Cold7** [comment]
my bad about that, just upgraded the alias to change salmon's path (from 0.7.2 to 1.3.0), but changes have not been affected. I'm so sorry about that

**Comment by rob-p** [comment]
No worries, I'm glad this was resolved :).
