### ISSUE TITLE
How to assess the effect of GC bias correction for read count table?

### ISSUE THREAD

**Issue by yeodynasty** [COMBINE-lab/salmon#578]
I understand that SALMON 'corrects' the count table to account for GC bias in expression.
However, since there is no 'before' and 'after' count tables for comparison, how do users assess if there is an correction and the degree of correction?

**Comment by rob-p** [comment]
Hi @yeodynasty,

  There are two different ways to tackle this question.  The first relies on the fact that the correction employed by salmon for GC bias is done via the adjustment of transcript effective lengths.  Here, you could compare the effective length in the quant.sf file to the effective length you would get ignoring GC-fragment (or other bias).  Granted, the latter is not written down in the file here, but it is straightforward to calculate since salmon also writes out the fragment length distribution. 
The effective length discarding bias estimates is simply the transcript length, minus the mean of the conditional fragment length distribution (the fragment length distribution from 0 up to the transcript length, re-normalized to be an appropriate probability distribution).  If you look at the differences between these values, you can infer how much bias correction was applied.  Specifically, when the bias-corrected length is longer than the non bias-corrected length, then these transcripts are over-represented in sequencing and the bias correction aims to reduce their estimated abundance.  On the other hand, when the bias-corrected length is shorter than the non bias-corrected length, then these transcripts are under-represented in sequencing and the bias correction aims to increase their estimated abundance.

**Comment by yeodynasty** [comment]
Hi

**Comment by yeodynasty** [comment]
I'll like to share a figure of the average expression values by GC content, but I can't add tiff file by dragging and dropping, selecting or pasting.

**Comment by yeodynasty** [comment]
After Salmon's correction, I can still see the bias in expression level with GC content (picture link): https://ibb.co/TbVqZy4

**Comment by rob-p** [comment]
Hi @yeodynasty,

  Thanks for the plot.  I'm not sure I completely understand what is being plotted here (i.e. what the lines in the plot actually represent).  However, there are a couple of important points to make.  

* First, even though counts are indirectly de-biased because of effective length adjustment, it's best to look at bias correction visually via the TPM estimates.  In fact, the conjunction of the TPM, effective lengths, and the total library sample size are what are used by `tximport` to derive the count matrix for DE (in the appropriate modes).

* Second, we don't expect there to be no relation between GC content and abundance.  What the GC bias correction does is to model and attempt to remove the bias compared to _an unbiased experiment expressing the same transcripts, at the same abundances, but with uniform coverage_.  In other words, given the GC content of the underlying transcriptome itself, as well as the set of transcripts expressed in a sample, we wouldn't expect a "flat line" on such a plot (if I'm interpreting it correctly).  Rather, we'd expect something that follows the underlying GC content histogram of the set of expressed transcripts.  The bias occurs when certain _regions_ of the transcripts (high or low GC-content) are under/over-sampled relative to the rest of the same transcript; that is the bias being corrected.

* Third, it is, of course, possible there is _some_ residual effect even after bias correction.  I'm not convinced that's what's happening here, but it is the case that the modeling and correction generally attempts strongly not to "over-correct".

Hopefully this helps.

**Comment by yeodynasty** [comment]
Hi, thanks for your perspective.
I think point 2 and 3 resonates with me.
