### ISSUE TITLE
Find the effective length of equivalence classes

### ISSUE THREAD

**Issue by sagnikbanerjee15** [COMBINE-lab/salmon#579]
Hello,

We are using Salmon to quantify gene counts for samples in RNA-Seq experiment. We will be using the weights of the equivalence class to perform a calculation for which we require the effective length of the equivalence classes. I checked in the eq_class.txt file under the aux_info directory but I was unable to find it. We are using alignment-based method where we supply a bamfile to salmon. Could you please help us to obtain the effective length of the equivalence classes?

I have another question. Salmon operates in both lightweight alignment mode and in alignment mode. For the lightweight mode, one needs to first create an index (which is the colored De Bruijn graph). I understand that this index (along with all the equivalence class) remains the same even when gene counts of different RNA-Seq samples are estimated. But I am a bit confused about the alignment-based method. In this case, salmon does not require an index since it has the actual alignments. If we have multiple samples, which are mapped to the same transcriptome will Salmon return the same set of equivalence classes? Since the samples are different the weights will change and so will the reads mapped to each equivalence class but will the set of eq. classes change?

Thank you.

**Comment by rob-p** [comment]
Hi @sagnikbanerjee15,

> We are using Salmon to quantify gene counts for samples in RNA-Seq experiment. We will be using the weights of the equivalence class to perform a calculation for which we require the effective length of the equivalence classes. I checked in the eq_class.txt file under the aux_info directory but I was unable to find it. We are using alignment-based method where we supply a bamfile to salmon. Could you please help us to obtain the effective length of the equivalence classes?

An equivalence class is not an object that has a notion of a length or effective length.  Specifically, an equivalence class represents a set of transcripts to which a set of fragments map or align.  If you are using the range-factorized equivalence classes (which is what salmon uses by default internally), these represent a set of transcripts to which a set of fragments map or align with very similar conditional probability vectors.  Since the equivalence class represents mappings or alignments to a collection of transcripts — where each transcript may have an arbitrarily different length — there is no such thing as the notion of the "effective length" of an equivalence class.  Note that the sequence that induces an equivalence class need not even be a contiguous region of the underlying reference (see answer below), and thus the notion of an effective length (or a length in general) is not applicable here.

> I have another question. Salmon operates in both lightweight alignment mode and in alignment mode. For the lightweight mode, one needs to first create an index (which is the colored De Bruijn graph). I understand that this index (along with all the equivalence class) remains the same even when gene counts of different RNA-Seq samples are estimated. But I am a bit confused about the alignment-based method. In this case, salmon does not require an index since it has the actual alignments. If we have multiple samples, which are mapped to the same transcriptome will Salmon return the same set of equivalence classes? Since the samples are different the weights will change and so will the reads mapped to each equivalence class but will the set of eq. classes change?

The index remains the same when different samples are processed, just as with a traditional alignment tool like STAR or HISAT2.  However, the set of equivalence classes are _not_ fixed between samples.  The equivalence classes are induced by the specific set of aligned or mapped reads.  Further, salmon adopts a notion of [range-factorized equivalence classes](https://academic.oup.com/bioinformatics/article/33/14/i142/3953977) in which the equivalence relation depends not only on the transcripts to which a read aligns or maps, but also on the conditional probabilities of the fragment being generated from these transcripts, which itself depends on experiment-specific parameters like the fragment length distribution.  Thus, it is not the case under either its own builtin lightweight (selective) alignment, nor when operating with an external BAM file, that the set of equivalence classes produced by salmon will be the same across samples.  The equivalence classes are _based_ on the underlying reference sequence, but are sample specific and induced both by the specific patterns of multimapping as well as by the sample-specific parameters (like the fragment length distribution).  Thus, if you wish to perform some type of equivalence-class type analysis over multiple samples, you'll need to take the union over the equivalence classes observed in each of them.

I hope this helps!
