### ISSUE TITLE
Question: Optimal way to run Salmon for numerous samples

### ISSUE THREAD

**Issue by AndrewSkelton** [COMBINE-lab/salmon#589]
I've got some SMART-seq2 data that's been demultiplexed, so hundreds of small Fastq files. So, I was wondering: 

- Does Salmon have a way to take multiple samples / libraries on a single run and perform quantification in an optimised serial way? 
- Does Salmon have a way to keep the index in memory similar to STAR? 

I guess the obvious alternative is to schedule lots of runs, but just wondered if there were alternative options.

Thanks!

**Comment by rob-p** [comment]
Hi @AndrewSkelton,

  There is currently no easy way to keep the index in RAM as STAR/Bowtie2 do.  This is a feature we've been interested in for a _long_ time, but it's a feature that is very hard to justify spending a PhD student's time on since it's not going to contribute directly to any paper.  But, this is a feature we'd like to add and maybe we can swing it with some of the CZI round-3 funding we just got.  Nonetheless, the capability currently doesn't exist.  Salmon can take multiple fastq files as input, but then it assumes they all derive from the same library, so you get one "aggregate" quant.sf, which isn't what you want here.

  So, I think the only approach currently would be to schedule a number of small jobs.  I get why this isn't ideal.  One small saving grace is that recent versions of salmon (>= 1.0.0) adopt the pufferfish index which is _much_ smaller than the previous RapMap index.  Thus, the index loading time is quite small for a typical transcriptome.  Also, this often allows operating system cache to keep the index around, even if it's not explicitly stored in shared memory.

  Thanks for both of the suggestions, and I'll be sure to keep you in the loop if we acquire either of the capabilities you mention above!

**Comment by AndrewSkelton** [comment]
Hi @rob-p 

Appreciate the comment, and agree with your sentiments. I'm using the partial SA index, which has a significantly lower overhead, so will do some micro-optimisation before kicking off the jobs. 

Thanks for the input and work with Salmon / Alevin, it's a fantastic resource.
