### ISSUE TITLE
Relationship between salmon libType and STAR strandedness

### ISSUE THREAD

**Issue by birnbera** [COMBINE-lab/salmon#590]
I posted this on the Salmon gitter channel, but didn't get any response, so I figured I'd see if someone here is willing to take the bait 🍣 .

I'm using Salmon with in alignment mode following alignment with STAR. I'm confused about the relationship between the STAR strandedness settings ("unstranded", "forward", "reverse") and the chosen libType for Salmon. If I align with STAR in "unstranded" mode, but then set the libType in Salmon to, e.g., ISR, does Salmon reassign all reads to the transcript on the correct strand based on the most likely transcript (via on some EM algorithm) or do I have to run STAR with the correct strandedness option and then apply the same settings (or use libType A) to Salmon quant?

**Comment by rob-p** [comment]
Hi @birnbera,

  Sorry you didn't get a response on Gitter.  We've moved to answering most questions via GitHub issues and are hanging around there less frequently now.  We should probably note that somewhere in the readme :).

  Regarding your question, salmon's library type is applied _on top of_ the alignments that are provided.  So, if you aligned with STAR (with `--quantMode TranscriptomeSAM`), the default is unstranded alignment.  But if you provide salmon with `-l ISF`, then it will only consider alignments where the first read aligns to the forward orientation of the transcript as valid; basically, it will filter out alignments in the input BAM that do not accord with this prescribed orientation.  If you have unstranded alignments and quantify with `-l A`, salmon will look at the rate of alignments in different orientations and attempt to automatically infer the most likely orientation; then it will apply that rule for assessing compatibility.  It's worth noting that you can always apply an orientation filter to reads aligned in an unstranded manner, but you can't do the reverse.  So, if you aligned in a stranded way, you can't then meaningfully do unstranded quantification.  If you're using STAR upstream of salmon, this isn't so much of a concern, because I don't think STAR takes strandedness flags anyway.  Hopefully, this addresses your question.

Best,
Rob

**Comment by birnbera** [comment]
Hi @rob-p, thanks for you response! I think this answers my question, but let me ask a couple follow up questions just to be sure:

In `STAR` there is an option to use stranded alignment (`--readStrand`, which can take "Unstranded", "Forward", or "Reverse"). For the pipeline I'm building it would be ideal if I didn't have to specify the strandedness of the library as I'm not the one preparing the samples and it's not always easy to get that information from the scientist in the lab. As such, it would be great if I can use the default strandedness argument to `STAR` ("Unstranded") and let `salmon` "do the right thing" by letting it choose the `libType` for me. With that in mind, if I let `salmon` choose for me (`-l A`) am I risking throwing out any data?

In addition, if a transcript was aligned in a unstranded manner and ended up aligning to the wrong location due to ambiguity between the positive orientation of one transcript and the negative orientation of another, can `salmon` correct this by reassigning it to the right transcript based on the joint probability of all the other alignments (if you can't tell I'm at the edge of my BS zone)?

**Comment by rob-p** [comment]
> In STAR there is an option to use stranded alignment (--readStrand, which can take "Unstranded", "Forward", or "Reverse"). For the pipeline I'm building it would be ideal if I didn't have to specify the strandedness of the library as I'm not the one preparing the samples and it's not always easy to get that information from the scientist in the lab. As such, it would be great if I can use the default strandedness argument to STAR ("Unstranded") and let salmon "do the right thing" by letting it choose the libType for me. With that in mind, if I let salmon choose for me (-l A) am I risking throwing out any data?

Right, so in this case, STAR should produce all highest-scoring valid alignments regardless of orientation.  Then, when running salmon with `-l A` it will detect the strandedness and only discard alignments compatible with the appropriate strand type (which may be unstranded if that is the protocol).  Salmon is pretty conservative about reporting when there is any ambiguity.  By default, if the strand bias is stronger than a few percent. In a stranded protocol, it will report and if it infers more than a few percent of fragments no having a valid alignment.  So you can always double-check samples where the strandedness is at all ambiguous.

> In addition, if a transcript was aligned in a unstranded manner and ended up aligning to the wrong location due to ambiguity between the positive orientation of one transcript and the negative orientation of another, can salmon correct this by reassigning it to the right transcript based on the joint probability of all the other alignments (if you can't tell I'm at the edge of my BS zone)?

If there is not an alignment to the correct location _in addition to_ the wrong location, then no.  If you run salmon in alignment mode, it will assign each fragment probabilistically to the set of transcripts to which it aligns.  There is, by definition, a probability of 0 for a fragment being assigned to a location where it doesn't align.  That is, the reported alignment positions should contain the true alignment.  STAR is pretty good at reporting all equally good alignments, but you could see some corner cases (e.g. if there is an alignment to a pseudogene location that looks _very_ similar to a gene, etc.).  However, these are the issues that arise due to the inherent difficulty of spliced alignment.  Salmon's built-in [selective alignment](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02151-8) is quite sensitive, but if you're using the STAR alignments for other tasks apart from transcript quantification, it may not be worth it to align the reads twice.  Overall, STAR unstranded (using the `--quantMode TranscriptomeSAM`) -> salmon with `-l A` and then checking samples where there are any warnings should be a pretty robust pipeline.

**Comment by birnbera** [comment]
Thank you! Great information here; now I have confidence in my workflow moving forward.
