### ISSUE TITLE
Gene counts missing transcripts

### ISSUE THREAD

**Issue by CoderMatthias** [COMBINE-lab/salmon#60]
Hi,

Fantastic program, so much quicker than our old workflow.  I ran into one issue when trying to get the gene counts in addition to the transcript counts (quant.genes.sf & quant.sf).  I know Ucp1 should be highly expressed, but didn't see it in quant.genes.sf.  

I have Ucp1 in the gene to transcript list (the list I supplied using the -g option):
$ grep Ucp1 ucsc2gene.tsv
uc009mjx.2  Ucp1

I don't have the Ucp1 gene in the Salmon gene output (quant.genes.sf):
$ grep Ucp1 quant.genes.sf
(nothing)

But I do see the corresponding transcript in the Salmon transcript output (quant.sf):
$ grep uc009mjx.2 quant.sf
uc009mjx.2  1644    1456.52 1599.27 51083

Based on this, I would have expected to see Ucp1 in the quant.genes.sf, as I thought this file was a summation of the transcript counts corresponding to a given gene.  Am I missing something on the functionality of the geneMap option, or should have I seen that gene in my quant.genes.sf output.

Thanks for your help.
Matt

**Comment by rob-p** [comment]
There was previously a bug that could lead to this behavior if the transcript to gene mapping was incomplete (i.e. if there were transcripts without an appropriately mapping gene).  This is fixed in the latest release.  Nonetheless, I'll note that [tximport](http://bioconductor.org/packages/release/bioc/html/tximport.html) is now the preferred way to aggregate abundances to the gene level.
