### ISSUE TITLE
Question for quantification of Nanopore reads

### ISSUE THREAD

**Issue by shnmunk** [COMBINE-lab/salmon#602]
Dear Salmon team,

I have been looking into Salmon for quantifying Nanopore cDNA reads in alignment-based mode, and I want to ask whether the option ‘--noLengthCorrection’ is recommended for this given the reads are single-end reads with lengths equal to the fragment lengths?

And I assume running Salmon with this option would cancel/overrule ‘--fldMean’ and ‘--fldSD’ settings? 

Thanks in advance,
Sebastian

**Comment by rob-p** [comment]
Hi @shnmunk,

  Yes, the `--noLengthCorrection` flag is recommended for nanopore based quantification.  We expect (and generally observe) that there is not a fragmentation effect in ONT data.  Therefore, it is recommended that you use the `--noLengthCorrection` flag with ONT data.  You are correct that this make the setting of `--fldMean` and `--fldSD` irrelevant, since there is no length effect applied during the EM algorithm.

  The other point of note is that selective-alignment is not really designed for long reads, so folks typically use salmon with external alignment for quantifying long-read data (minimap2 is a popular choice).  Currently, it's necessary to turn off the read error model `--noErrorModel` when processing long-read alignments, as the long read error profiles are very different form those of short reads.  However, this is a temporary issue, as a long-read error model has been developed and is in the pipeline.  For the time being though, `--noErrorModel --noLengthCorrection` is the relevant set of flags to get the best results with long-read RNA-seq (either cDNA or direct RNA).

**Comment by shnmunk** [comment]
Hi @rob-p,

Thanks a lot for the clarification.

In combination with the flags you specified above, do you think the `--gcBias` setting can be used to correct for potential PCR amplification bias in Nanopore cDNA reads? 

Or would it currently be the better option not to use this setting for Nanopore PCR-cDNA reads?

Best,
Sebastian
