### ISSUE TITLE
salmon --writeUnmappedNames produced undocumented result

### ISSUE THREAD

**Issue by aedavids** [COMBINE-lab/salmon#657]
I am using the  --writeUnmappedNames parameter. Some of the unmapped reads are flagged with 'd' . what does this mean ?

```
$ salmon -version
salmon 1.4.0
```

https://salmon.readthedocs.io/en/latest/salmon.html#writeunmappednames

 ```
   u   = The entire pair was unmapped. No mappings were found for either the left or right read.
   m1  = Left orphan (mappings were found for the left (i.e. first) read, but not the right).
   m2  = Right orphan (mappinds were found for the right read, but not the left).
   m12 = Left and right orphans. Both the left and right read mapped, but never to the same transcript.
   ```
    
   - $outdir /aux_info/unmapped_names.txt 
   ```
   $head aux_info/unmapped_names.txt 
   NB551675:38:HTMGLAFXY:1:11101:22494:8399 u
   NB551675:38:HTMGLAFXY:1:11101:10728:8400 d
   NB551675:38:HTMGLAFXY:1:11101:21165:8401 d
   NB551675:38:HTMGLAFXY:1:11101:6081:8410 d
   NB551675:38:HTMGLAFXY:1:11101:19777:8412 u
   NB551675:38:HTMGLAFXY:1:11101:4640:8415 d
   NB551675:38:HTMGLAFXY:1:11101:11482:8418 d
   NB551675:38:HTMGLAFXY:1:11101:21024:8419 d
   NB551675:38:HTMGLAFXY:1:11101:25790:8423 u
   NB551675:38:HTMGLAFXY:1:11101:8557:8423 u
   ```

```
ctrl.1.unmapped]$ cut -d " " -f 2 aux_info/unmapped_names.txt | sort | uniq -c
 519916 d
  39097 m1
  34534 m2
 747447 u
```

kind regards

Andy

**Comment by rob-p** [comment]
Hi @aedavids,

  Thanks for catching that this is undocumented!  This means that the mapping type was determined as mapping to a _decoy_ sequence.  When we added this output into the code, the documentation wasn't updated accordingly.  We'll update the documentation.

Best,
Rob

**Comment by aedavids** [comment]
thanks

From: Rob Patro ***@***.***>
Reply-To: COMBINE-lab/salmon ***@***.***>
Date: Thursday, May 6, 2021 at 1:53 PM
To: COMBINE-lab/salmon ***@***.***>
Cc: "andrew e. davidson" ***@***.***>, Mention ***@***.***>
Subject: Re: [COMBINE-lab/salmon] salmon --writeUnmappedNames produced undocumented result (#657)


Hi @aedavids<https://github.com/aedavids>,

Thanks for catching that this is undocumented! This means that the mapping type was determined as mapping to a decoy sequence. When we added this output into the code, the documentation wasn't updated accordingly. We'll update the documentation.

Best,
Rob

**Comment by aedavids** [comment]
Hi Rob

I thought about this a little bit more. I am confused.  We build the index from decoys. My understanding is that only reads that map to the decoy will be quantified. I am surprised to see that the name for mapped reads would show up in the unmapped_names.txt file. It seems like I need to use something like

Grep -v “$d”

to find the reads that did not map. Is this correct? I have been given the task of exploring our unmapped reads. Running grep is not a big deal. I just want to make sure I do not mess up my downstream analysis

By the way our lab is a huge fan of Salmon.


ctrl.1.unmapped]$ cut -d " " -f 2 aux_info/unmapped_names.txt | sort | uniq -c
519916 d
39097 m1
34534 m2
747447 u

Kind regards

Andy

From: Rob Patro ***@***.***>
Reply-To: COMBINE-lab/salmon ***@***.***>
Date: Thursday, May 6, 2021 at 1:53 PM
To: COMBINE-lab/salmon ***@***.***>
Cc: "andrew e. davidson" ***@***.***>, Mention ***@***.***>
Subject: Re: [COMBINE-lab/salmon] salmon --writeUnmappedNames produced undocumented result (#657)


Hi @aedavids<https://github.com/aedavids>,

Thanks for catching that this is undocumented! This means that the mapping type was determined as mapping to a decoy sequence. When we added this output into the code, the documentation wasn't updated accordingly. We'll update the documentation.

Best,
Rob

**Comment by rob-p** [comment]
Hi @aedavids,

  Sorry for the delay in replying to your reply here.  So I think what you suggest is the right solution, and there are some strange historical reasons we write the decoy names out in the unmapped file.
  
  >  We build the index from decoys. My understanding is that only reads that map to the decoy will be quantified. I am surprised to see that the name for mapped reads would show up in the unmapped_names.txt file.
  
  Well, it's the case the decoys are *not* be quantified.  That is, only the target transcripts will appear in the `quant.sf` file, no decoys should be present there.  The main purpose of the decoys is to account for reads _not_ from target transcripts that might otherwise be sequenced in the sample.
  
  The reason we report the decoy mapping fragments in the unmapped names file is, as I said, a historical contingency.   Basically, since we're not mapping the decoys to targets and counting them toward quantification, one might be interested in knowing _where_ the decoy sequences come from.  At some point, the easiest way to do this was just to place the name of these fragments in the unmapped names file (with the `d` tag) and then grab the reads and go fishing with them in some other way.  However, I totally understand why including them in the unmapped names file is confusing.  During selective-alignment, if we assign a fragment as best mapping to a decoy, it doesn't get assigned to a quantifiable target, but it's not technically unmapped in the same sense as the other unmapped reads.  That is, we know it comes from the decoy sequence, that the alignment score is at least the minimum required, and that it maps better to the decoy than to any non-decoy target.  That's quite different that "truly" unmapped fragments where we find no mapping for the fragment within the required score threshold.

  Anyway, I hope the answer is useful for you.  If you want to select only unmapped reads that were matched to *neither* your target sequences (transcripts) *nor* to the decoy sequences, then your `grep` command should do the trick.  However, if you want to look at all of the reads that simply didn't contribute to the counts in the `quant.sf` file, then you'd want to look at everything in the unmapped names file.  Let me know if you have any other questions!

Best,
Rob

**Comment by aedavids** [comment]
Hi Rob

Thanks for the explination

Andy

From: Rob Patro ***@***.***>
Reply-To: COMBINE-lab/salmon ***@***.***>
Date: Friday, May 14, 2021 at 1:41 PM
To: COMBINE-lab/salmon ***@***.***>
Cc: "andrew e. davidson" ***@***.***>, Mention ***@***.***>
Subject: Re: [COMBINE-lab/salmon] salmon --writeUnmappedNames produced undocumented result (#657)


Hi @aedavids<https://github.com/aedavids>,

Sorry for the delay in replying to your reply here. So I think what you suggest is the right solution, and there are some strange historical reasons we write the decoy names out in the unmapped file.

We build the index from decoys. My understanding is that only reads that map to the decoy will be quantified. I am surprised to see that the name for mapped reads would show up in the unmapped_names.txt file.

Well, it's the case the decoys are not be quantified. That is, only the target transcripts will appear in the quant.sf file, no decoys should be present there. The main purpose of the decoys is to account for reads not from target transcripts that might otherwise be sequenced in the sample.

The reason we report the decoy mapping fragments in the unmapped names file is, as I said, a historical contingency. Basically, since we're not mapping the decoys to targets and counting them toward quantification, one might be interested in knowing where the decoy sequences come from. At some point, the easiest way to do this was just to place the name of these fragments in the unmapped names file (with the d tag) and then grab the reads and go fishing with them in some other way. However, I totally understand why including them in the unmapped names file is confusing. During selective-alignment, if we assign a fragment as best mapping to a decoy, it doesn't get assigned to a quantifiable target, but it's not technically unmapped in the same sense as the other unmapped reads. That is, we know it comes from the decoy sequence, that the alignment score is at least the minimum required, and that it maps better to the decoy than to any non-decoy target. That's quite different that "truly" unmapped fragments where we find no mapping for the fragment within the required score threshold.

Anyway, I hope the answer is useful for you. If you want to select only unmapped reads that were matched to neither your target sequences (transcripts) nor to the decoy sequences, then your grep command should do the trick. However, if you want to look at all of the reads that simply didn't contribute to the counts in the quant.sf file, then you'd want to look at everything in the unmapped names file. Let me know if you have any other questions!

Best,
Rob

**Comment by rob-p** [comment]
Great.  I will close this issue for now @aedavids, but please feel free to re-open if you have any further questions.
