### ISSUE TITLE
Detected a *potential* strand bias warning

### ISSUE THREAD

**Issue by mooreann** [COMBINE-lab/salmon#659]
Hi, I've been using salmon v1.0.0 to quantify bulk transcripts from fastqs using the genocde v32 reference. Ive used it successfully on several cohorts but on my most recent I received the following warning in my log file (I also attached the entire file):

[2021-05-10 20:51:46.936] [jointLog] [warning] NOTE: Read Lib [[ /gcloud-shared/inputR1.gz, /gcloud-shared/inputR2.gz]] :

Detected a *potential* strand bias > 1% in an unstranded protocol check the file: /gcloud-shared/sample/lib_format_counts.json for details

Here is also the lib_formats_count.json:
{
    "read_files": "[ /gcloud-shared/inputR1.gz, /gcloud-shared/inputR2.gz]",
    "expected_format": "IU",
    "compatible_fragment_ratio": 1.0,
    "num_compatible_fragments": 43142675,
    "num_assigned_fragments": 43142675,
    "num_frags_with_concordant_consistent_mappings": 36380775,
    "num_frags_with_inconsistent_or_orphan_mappings": 7777480,
    "strand_mapping_bias": 0.5172763911708863,
    "MSF": 0,
    "OSF": 0,
    "ISF": 18818916,
    "MSR": 0,
    "OSR": 0,
    "ISR": 17561859,
    "SF": 2219340,
    "SR": 5558140,
    "MU": 0,
    "OU": 0,
    "IU": 0,
    "U": 0
}

Here is the salmon command I've been using:

salmon --no-version-check quant -i /gcloud-shared/reference -l A -1 ${FASTQR1} -2 ${FASTQR2} \
--validateMappings --seqBias --gcBias --posBias --threads $(nproc) -o /gcloud-shared/sample

The whole process still produces quants files, but having never received this warning with other sample cohorts I want to be sure it's not affecting the results. Any idea why I might be getting this? Am I using the wrong lib type?

Thanks!

[ukbec_quants_gencode_32_filtered_A653_002_logs_salmon_quant.log](https://github.com/COMBINE-lab/salmon/files/6479118/ukbec_quants_gencode_32_filtered_A653_002_logs_salmon_quant.log)

**Comment by rob-p** [comment]
Hi @mooreann,

  So, as you can see the strand mapping bias is calculated as `0.5172763911708863`, so ~51.7%.  A *perfectly* unbiased ratio would be 50%.  However, there are many reasons you might see small deviations from this in your sample.  Salmon is *super* conservative in reporting a _potential_ bias (anything > 1% deviation from 50/50), since raising the warning doesn't cost anything (we compute these statistics anyway), and it's better that someone who could be expecting such a thing is a aware of it than that someone notice the warning and decide it's not a problem.  In this case, your sample is 0.7% above the detection threshold, and so the warning is raised.  Unless you're noticing anything else that looks strange with the results, I would suggest that this probably isn't anything you need to worry about.  As I mentioned, one might expect some natural variation from a "perfect" 50% split between reads arising in each orientation, and the bias in this data looks pretty slight; it's just that salmon is very conservative in reporting the issue.

Best,
Rob
