### ISSUE TITLE
Segfault on SRA data

### ISSUE THREAD

**Issue by mpi-pebert** [COMBINE-lab/salmon#66]
Hi,
I am processing canine data (replicates SRR636842 and SRR636843) and Salmon segfaults with no (?) useful information in the log that would help me to identify the problem. Other data from the same study are processed fine (mouse, cow and pig; all 51nt reads).

```
# salmon (mapping-based) v0.6.0
# [ program ] => salmon 
# [ command ] => quant 
# [ index ] => { /[...path...]/genemodel/cfa_canFam3_ensembl_vN.pctr_norm.k19.idx }
# [ threads ] => { 16 }
# [ libType ] => { IU }
# [ mates1 ] => { /dev/fd/63 }
# [ mates2 ] => { /dev/fd/62 }
# [ biasCorrect ] => { }
# [ output ] => { /[...path...]/tmp/SRX211583 }
# [ forgettingFactor ] => { 0.8 }
# [ useVBOpt ] => { }
# [ sensitive ] => { }
# [ geneMap ] => { /[...path...]/genemodel/cfa_canFam3_ensembl_vN.pctr_map.tsv }
    Logs will be written to /[...path...]/tmp/SRX211583/logs
    there is 1 lib
    [2016-07-19 09:35:23.827] [jointLog] [info] parsing read library format
    Loading 32-bit quasi index[2016-07-19 09:35:23.895] [jointLog] [info] Loading Quasi index
    [2016-07-19 09:35:23.898] [stderrLog] [info] Loading Suffix Array 
    [2016-07-19 09:35:23.899] [stderrLog] [info] Loading Position Hash
    [2016-07-19 09:35:29.545] [stderrLog] [info] Loading Transcript Info 
    [2016-07-19 09:35:30.913] [stderrLog] [info] Loading Rank-Select Bit Array
    [2016-07-19 09:35:31.452] [stderrLog] [info] There were 24526 set bits in the bit array
    [2016-07-19 09:35:31.737] [stderrLog] [info] Computing transcript lengths
    [2016-07-19 09:35:31.737] [stderrLog] [info] Waiting to finish loading hash
    Index contained 24526 targets
    [2016-07-19 09:36:30.462] [jointLog] [info] done
    [2016-07-19 09:36:30.462] [stderrLog] [info] Done loading index
```

All data are processed in the same pipeline, so I guess there is something particular about this dataset - but given this information, I have no clue where to start looking.
I have seen ticket #64, but I am not using the `--useFSPD` parameter, so I assume it's a different problem.

+Peter

**Comment by rob-p** [comment]
Hi Peter,

  Thank you very much for reporting this, and for providing details of the data so that I can try to reproduce it.  One more piece of information I'll need to try and reproduce this is the reference transcriptome to which you're mapping (a link to the fasta file should be fine).  I have a rather large deadline tomorrow, but I should be able to work on this and get you an answer / fix later this week.

--Rob

**Comment by rob-p** [comment]
Hi Peter,

  Obviously, I got tied up with other obligations a bit longer than I thought!  Sorry for the delay.  Anyway, I've run both of these samples with the newest release, using parameters as close as I can (given that the bias correction flags have changed in 0.7.0).  Both samples seem to run cleanly.  Would you mind testing with the latest release and seeing if the issue is resolved?  Here is the procedure I used:

Index with k=19 (I think this is what you did), using the default `quasi` index.

```
> salmon index -t Canis_familiaris.CanFam3.1.cdna.all.fa.gz -i index -k 19
```

Run sample `SRR636842`:
```
> salmon quant -i index -p 16 -l IU -1 SRR636842_1.fastq.gz -2 SRR636842_2.fastq.gz --seqBias -o quant_SRR636842 --useVBOpt
```
here, the mapping rate was ~78.8%.

Run sample `SRR636843`:
```
>salmon quant -i index -p 16 -l IU -1 SRR636843_1.fastq.gz -2 SRR636843_2.fastq.gz --seqBias -o quant_SRR636843 --useVBOpt
```
here, the mapping rate was ~79.5%.

The mapping rates may differ for you a bit, since I used [this](ftp://ftp.ensembl.org/pub/release-85/fasta/canis_familiaris/cdna/Canis_familiaris.CanFam3.1.cdna.all.fa.gz) Ensembl transcript set directly.

**Comment by mpi-pebert** [comment]
Hi Rob,
thanks for getting back to me about this issue. It looks like with the most recent version [0.7.1], the problem - whatever it was - is solved; both samples are processed fine, I am ending up with mapping rates of ~72% and 78%, respectively. Thanks for the support.
Best,
Peter
