### ISSUE TITLE
--gencode flag doesn't work with salmon quant 

### ISSUE THREAD

**Issue by callumparr** [COMBINE-lab/salmon#671]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
salmon quant

**Describe the bug**
--gencode used with salmon quant does not result in correct handling of of multi-label headers in gencode reference files. Resulting in errors and failure to estimate counts when using gencode transcriptome for alignment.

Now for every reference header error is output: 
```
[2021-06-15 00:15:36.623] [jointLog] [critical] Please provide a reference FASTA file that includes all targets present in the BAM header
If you have access to the genome FASTA and GTF used for alignment
```

**To Reproduce**
Steps and data to reproduce the behavior:

align reads to transcriptome using minimap2 to generate BAM file. Use of salmon to estimate transcript counts using ONT specific flags.

```
salmon-1.5.1_linux_x86_64/bin/salmon quant --ont --gencode -p 4 -t Genome_files/gencode.vM24.transcripts.fa -l U -a Documents/Day2_03_DRS_pass.bam -o Documents/counts/Day2_03_DRS_pass
```

Specifically, please provide at least the following information:

  * Which version of salmon was used? v1.5
  * How was salmon installed (compiled, downloaded executable, through bioconda)? binary downloaded from github
  * Which reference (e.g. transcriptome) was used? gencode.M24.transcriptome.fa
  * Which read files were used? direct RNA sequences from MinION platform 
  * Which which program options were used? see above

**Expected behavior**
Expect that salmon splits the header from gencode reference and takes first part of the header and uses in output files for transcript estimatation.

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX]
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]

**Additional context**

**Comment by rob-p** [comment]
Hi @callumparr,

  Thank you for the detailed report.  I think this is primarily an error in documentation.  The `gencode` flag is intended to be used only with "mapping-based" mode and when creating the index.  It ensures that the index (and hence the resulting quantifications) contain the shortened names for gencode transcripts.

  In alignment-based mode, the behavior of the flag would have to be slightly different.  It would have to re-normalize not only the names of the reference sequences in the fasta file, but it would also have to re-normalize the names in the BAM header so that they match.  Specifically, the requirement is that the names of the sequences in the input fasta file are a 1-1 match with the names in the BAM header so that transcripts can be matched up properly with their sequences for training and applying the error model.

  However, if your BAM file already contains the stripped transcript names (i.e. if the BAM file header has the names without everything past the initial `|`), then I believe you can use the following command to have salmon do the same to the fasta file on the fly, so that the names match.

```{bash}
salmon-1.5.1_linux_x86_64/bin/salmon quant --ont -p 4 -t <(awk '{ if ($0 ~ "^>") { split($0,a,"|"); print a[1] } else { print $0 } }' Genome_files/gencode.vM24.transcripts.fa) -l U -a Documents/Day2_03_DRS_pass.bam -o Documents/counts/Day2_03_DRS_pass
```

  If the BAM file contains the "full" transcript name however, I think the current options are either to let salmon use the full transcript name from the fasta file, or to modify the GTF when running with minimap2, so that the BAM file itself contains the shortened names.

  Finally, I'd like to mention that the way you _intended_ to use the `--gencode` flag in alignment mode actually makes _a lot_ of sense, and I think it would be a very nice feature.  Basically, the idea would be to apply stripping everything after the first `|` from *both* the fasta header and the BAM header, and using the reduced names for `quant.sf` outputs.  We'll certainly. look into adding this functionality in a future release.  Apologies for confusion caused by the ambiguous documentation of this flag.

--Rob

**Comment by callumparr** [comment]
Hey Rob, thank you again for the detailed response. 

I guess I got confused by this response here: https://github.com/COMBINE-lab/salmon/issues/95#issuecomment-250509570  I thought this feature had already been added to quant alignment mode.

I will run without the --gencode flag.
