### ISSUE TITLE
Salmon quasi-index definition in documentation

### ISSUE THREAD

**Issue by mishaprochazka** [COMBINE-lab/salmon#727]
Hi,
while I was reading the Salmon documentation regarding --writemappings option I ran into term quasi-index (https://github.com/COMBINE-lab/salmon/blob/d8300c3a476ef8b703fcb25aab6d6eca4a7bf3b4/doc/source/salmon.rst#--writemappings), however, I haven't found any other mention or definition of this term in the documentation. 

Could you please explain what it mean as I'd like to use the option (running Salmon mapping-based mode) properly.

Thank you.

**Comment by jdidion** [comment]
+1 @rob-p if you could help with this I'd really appreciate it. Thanks!

**Comment by rob-p** [comment]
Hi @mishaprochazka and @jdidion,

  Thanks @jdidion for pinging me on this.  Somehow, Gmail has decided that all GitHub notifications (except those that explicitly tag me) should go to SPAM.  So, I've been missing some of the newer issues here.

  The short answer is that the documentation needs to be updated.  When salmon was originally published, we made use of [RapMap](https://github.com/COMBINE-lab/RapMap) as the underlying mapper, which performed quasi-mapping against an index that consisted of a suffix array and a hash over k-mers pointing to prefixes in the suffix array (similar to the strategy used by STAR, but using much longer k-mers to improve lookup speed).  We referred to this index as the quasi-index.

  As the software evolved and we continued to improve the mapping methodology, we eventually transitioned over to an index based on [our pufferfish data structure](https://github.com/COMBINE-lab/pufferfish).  In addition to the new data structure, this coincided with our move over to selective-alignment as the mapping algorithm, and all of this happened at the 1.0.0 release (this is why, for example, indices built before 1.0.0 are not compatible with salmon > 1.0.0; a topic on which there have been a few GitHub issues).

  However, given the fact that the documentation and software are linked only through manual human intervention (we haven't leveled up to e.g. having salmon be a [literate program](https://en.wikipedia.org/wiki/Literate_programming) yet), these two sometimes get out of sync.  This is an instance of that.  We have maintained the functionality of the `--writeMappings` feature, and in fact, even augmented it.  However, we have not replaced the antiquated `quasi-index` terminology in the documentation.  The TLDR is that you can use `--writeMappings` with the index you built with the `salmon index` command, and it should work fine.  If you are mapping against an index without decoy sequences, then the output format will be basically the same as older (pre 1.0.0) versions.  If you have decoy sequences in your index, then there is an optional SAM flag with each record that tells you if the mapping is to a target or a decoy. Specifically, `XT:A:T` signifies that the mapping was to a non-decoy target and `XT:A:T` specifies that the mapping was to a sequence marked in the index as a decoy.

  I hope this diversion into historical leakage into the current documentation answers your question.  Thanks for reporting this, and we'll try to address it upstream so it's fixed in the next release.

Best,
Rob

**Comment by jdidion** [comment]
Thanks for the thorough and illuminating response!

**Comment by mishaprochazka** [comment]
Thank you for the explanation.
