### ISSUE TITLE
weird error when running quant command

### ISSUE THREAD

**Issue by bzmby** [COMBINE-lab/salmon#746]
I am using `salmon` for both creating index and quant using the latest version of salmon using the following commands:

1- for indexing:

    salmon index 
        -t "${fasta}" 
        -i index 

2- for quantification:

    salmon quant 
        --libType=U
        --index $index 
        -1 ${reads[0]} 
        -2 ${reads[1]} 
        -o $pair_id

But I am getting this error:

    Command error:
      Version Info: This is the most recent version of salmon.
      (mapping-based mode) Exception : [the option '--index' is required but missing].
      Please be sure you are passing correct options, and that you are running in the intended mode.
      alignment-based mode is detected and enabled via the '-a' flag. Exiting.

This error is related to quant part. Do you know how I can fix the problem?

**Comment by rob-p** [comment]
Hi @bzmby,

  This is very strange and we recently had a report from another user that seemed related. Except their issue was resolved by using the long-form `--index` rather than `-i` and happened in the `index` command rather than the `quant` command.  Do things look any different if you use short-form or re-arrange the option order e.g. 👍🏻 

```
salmon quant 
    -i $index
    -l U
    -1 ${reads[0]} 
    -2 ${reads[1]} 
    -o $pair_id
```

Also, are there any strange characters (e.g. spaces) in the `$index` path that would cause it to be necessary to e.g. quote the string?

Best,
Rob

**Comment by rob-p** [comment]
I think this was resolved via an e-mail follow up — there was an errant newline after the `--libType` parameter.  If this wasn't resolved, feel free to re-open.
