### ISSUE TITLE
--incompatPrior doesn't work with salmon alevin

### ISSUE THREAD

**Issue by yagam-fluent** [COMBINE-lab/salmon#749]
Using salmon-1.6.0_linux_x86_64, any call to salmon alevin with "--incompatPrior x.x" gives me the following exception:
Exception : [unrecognised option '--incompatPrior']
No problem when running salmon quant.

Is this option only valid in quant mode, and if so, why?
Is there another way to prevent antisense reads in alevin results?

**Comment by rob-p** [comment]
Hi @yagam-fluent,

  Thanks for the excellent question.  We should update the documentation regarding this option.  Basically, in `salmon alevin`, we assumptions about expected read orientation are applied as "hard filters".  That is, the behavior is equivalent to `--incompatPrior 0`, so that aligninments not in the prescribed orientation are simply not considered as invalid alignments.  This is because in the case of single-cell processing, we (the community in general) currently do not have as sophisticated of probabilistic models for resolving UMI origins and gene abundances, and so algorithms typically do not take into account a "wrong orientation" probability.

  So, in `salmon alevin` if you are using alevin itself for the quantification, then hard filtering will be applied based on the expectations of `--libType`.  On the other hand, if you are using `salmon alevin` to simply map the reads for subsequent processing with [`alevin-fry`](https://github.com/COMBINE-lab/alevin-fry) (i.e. `salmon alevin .... --rad` or `salmon alevin ... --sketch`), then *no* filtering is applied to mapping orientation, and instead you filter reads by orientation later in `alevin-fry`'s `generate-permit-list` step.

Best,
Rob

**Comment by yagam-fluent** [comment]
Thanks Rob. I am using alevin with libType of ISR. When I looked at the SAM file after setting the writeMapping option, I observed that ~1% had the "reverse alignment" flag set to 1 (the only flags field that had this flag set was 341, all the rest had that bit set to 0). It's not clear to me whether alevin uses those reads for UMI counting, and if so, what's the best way to turn off this behavior.

**Comment by rob-p** [comment]
Hi @yagam-fluent,

  Alevin should not be using these reads for UMI counting.  In general, we now recommend using [`alevin-fry`](https://github.com/COMBINE-lab/alevin-fry) for single-cell processing.  In that program the `-d`/`--expected-ori` parameter to [`generate-permit-list`](https://alevin-fry.readthedocs.io/en/latest/generate_permit_list.html) determines which directions of mapping are considered.

Best,
Rob
