### ISSUE TITLE
--mimicBT2

### ISSUE THREAD

**Issue by yagam-fluent** [COMBINE-lab/salmon#750]
The documentation says it is a meta-flag that sets other parameters to mimic Bowtie2 behavior, but it doesn't specify which parameters and what values they are set to. Could you please clarify this?

**Comment by rob-p** [comment]
Yes; the main parameters it changes are [here](https://github.com/COMBINE-lab/salmon/blob/9c3259983c7cff02018bf8e2dc6d81ab22520b6c/src/SalmonUtils.cpp#L1594).  Not all can be understood without knowing the details of the algorithm but the high-level points are:

* It raises the number of places a read can occur and still be considered to map well enough to be considered.
* It lowers the consensus slack (allowing more mappings to be considered for alignment)
* It disables orphan mapping if it is otherwise enabled
* It disables softclipping of overhangs, if that's otherwise enabled
* It changes the details of the alignment scoring function with these new penalties
```
        matchScore = 2;
        mismatchPenalty = -4;
        gapOpenPenalty = 5;
        gapExtendPenalty = 3;
```

In general, these make the requirements on alignments that are discovered stricter than the standard parameters, but it looses criteria used to filter mappings prior to alignment (so it will look at more alignment loci).

Best,
Rob
