### ISSUE TITLE
Unrecognised option using salmon quant

### ISSUE THREAD

**Issue by Klud112** [COMBINE-lab/salmon#764]
Hi,
I am new to using salmon. I have tried quantifying one of my samples in both alignment and mapping-based modes. In both cases I get an error saying "unrecognised option" for various parts of the command (including both the "-i" and "-t" flags).  Below is an example of my code and the error:

salmon quant -t References/Ensembl/Homo_sapiens.GRCh37.cdna.all.fa\
-l A\
-a bam_files/RNA_007_7669.Aligned.out.sort.com.bam\
-o salmon_quant_trial
Version Info: This is the most recent version of salmon.
(mapping-based mode) Exception : [unrecognised option '-t'].
Please be sure you are passing correct options, and that you are running in the intended mode.
alignment-based mode is detected and enabled via the '-a' flag. Exiting

Do you know why flags such as -i and -t are not being recognized? I have tried using --index and --targets instead which hasn't helped.

Thanks!

**Comment by rob-p** [comment]
Hi @Klud112,

  The command itself looks OK.  However, given the formatting, I wonder if the line breaks are intentional.  The error you get is what I might imagine if the command is actually spread over multiple lines and therefore not properly parsed.  When there is a new line in your command above, is that just for formatting, or actually present in the command you issue on the command line?  If the latter, you need to escape it with `\` i.e.

```

salmon quant -t References/Ensembl/Homo_sapiens.GRCh37.cdna.all.fa \
-l A \
-a bam_files/RNA_007_7669.Aligned.out.sort.com.bam \
-o salmon_quant_trial
```

Best,
Rob

**Comment by rob-p** [comment]
Not sure why the `\` wouldn't fix it, but I'm glad to hear you were able to resolve the issue!
