### ISSUE TITLE
High number of "Replaced non-ATCG nucleotides" in index built from Ensembl

### ISSUE THREAD

**Issue by fweghorst** [COMBINE-lab/salmon#766]
I was attempting to create an index for mapping of transcripts using the full chicken (Gallus gallus) genome from Ensembl. No errors appeared, but the ref_indexing.log stated "Replaced 9,788,221 non-ATCG nucleotides" which seems rather high compared to some of the numbers I've seen from gencode-derived indices. This is my first time making an index, so I don't know where to begin troubleshooting. What "non-ATCG nucleotides" are being replaced here, and what are they being replaced with? Could Salmon be reading metadata in transcript headers as nucleotide sequences? Why would it do that? Am I just being paranoid?

Here's my code. Note that chicken does not have a "transcriptome" file, so I concatenated the cdna and ncrna files ahead of the full genome. I've also attached the ref_indexing.log file.
```

SALMON_BIN=/data/homezvol1/fweghors/chickscripts/salmon-1.8.0_linux_x86_64/bin/salmon
grep "^>" <(gunzip -c Gallus_gallus.GRCg6a.dna.toplevel.fa.gz) | cut -d " " -f 1 > decoys.txt
sed -i.bak -e 's/>//g' decoys.txt

cat Gallus_gallus.GRCg6a.cdna.all.fa.gz Gallus_gallus.GRCg6a.ncrna.fa.gz Gallus_gallus.GRCg6a.dna.toplevel.fa.gz > gentrome.fa.gz

gunzip gentrome.fa.gz

$SALMON_BIN index -t gentrome.fa -d decoys.txt -p 13 -i salmon_index
```

[ref_indexing.log](https://github.com/COMBINE-lab/salmon/files/8375551/ref_indexing.log)

**Comment by rob-p** [comment]
Hi @fweghorst,

  My guess is that a large fraction of this high number come from `N` bases in the underlying genome assembly (since you are making a gentrome index).  To test this hypothesis, you could also build an index with just the cdna (or edna + ncrna) and see what that number is.  At the end of the day, of course, it makes sense to use the gentrome index anyway, but this will at least give you an idea of what fraction of nucleotides are being replaced from the decoy (genome) versus the target transcript sequences.

Best,
Rob

**Comment by fweghorst** [comment]
Hi @rob-p 

Thank you for your insight. You were absolutely right; the gentromes of cDNA+genome and ncRNA+genome had "Replaced non-ATCG nucleotide" counts within a few thousand of the cDNA+ncRNA+genome count, so the vast majority of the 9.8 million must be coming from the genome. Thanks for your help.

**Comment by rob-p** [comment]
Happy to help!
