### ISSUE TITLE
Behavior when FASTQ read mates not in the correct order

### ISSUE THREAD

**Issue by tjbencomo** [COMBINE-lab/salmon#777]
Hi,

I recently used STAR and Salmon to quantify RNA expression from FASTQ files. When using Salmon, I was achieving good alignment rates of around 70%, but getting dismal STAR alignment rates of 1%-20% (both using GENCODE v38 references). Further inspection of my STAR log files shows most reads were being unmapped because they were too short. From STAR github issues I discovered that my FASTQ files were scrambled (confirmed with [validatefastq](https://github.com/biopet/validatefastq) tool), and the read headers were not properly sorted. This meant that the reads in the `R1` file did not necessarily correspond to the reads in the `R2` file (this was confirmed by BLASTing some of the reads and seeing they corresponded to different loci). 

After discovering my FASTQs were scrambled, I was surprised that Salmon still had such high alignment rates yet STAR did not. I was wondering how exactly Salmon handles input FASTQs with mismatched reads. Is there some fix that Salmon applies to match reads with their corresponding sequence ID, thus explaining the high alignment rate? Are the results from Salmon on my bad input FASTQs complete gibberish and should be discarded, or are they somehow still valid? Is there any defined behavior that Salmon should follow when it encounters improperly sorted input FASTQs?

**Comment by rob-p** [comment]
Hi @tjbencomo,

  Thanks for reaching out about this.  The main difference here is a difference in the default behavior of salmon and STAR.  STAR considers the alignable length of a fragment to be the sum of the length of read 1 and read 2 (call this length L), and then it discards alignments that cover less than the required fraction of this value.  By default, L > length read 1 and L > length read 2.  This means that, with default parameters, STAR will not report any orphan alignments; situations where only one of the two reads map or where the two reads map discordantly to the genome.  On the other hand, salmon *allows* orphan alignments by default (though they can be disabled with the `--discardOrphansQuasi` flag, and they are also discarded with the `--mimicBT2` flag).  In this case, _if there are no concordant alignments_, then salmon will consider orphaned alignments as evidence for the expression of a transcript.

  As for your second question, I would certainly re-run the quantification with the properly paired alignments.  While I don't think the pairing issue necessarily means your existing runs are meaningless, the quantification results are certainly less accurate than they could be since a tremendous amount of information is likely being discarded (e.g. the fragment length distribution is probably not being inferred properly, orphans are often more ambiguous than properly paired reads leading to a harder inference problem, etc.).  So, I would recommend re-quantifying using the fixed FASTQ files.  Let me know if you have any other questions.

Best,
Rob
