### ISSUE TITLE
meta_info.json counts

### ISSUE THREAD

**Issue by jonahcullen** [COMBINE-lab/salmon#782]
Hello, I am trying to understand how the counts from `meta_info.json` line up. For example,

```
    "num_processed": 20128545,
    "num_mapped": 17124379,
    "num_decoy_fragments": 819226, 
    "num_dovetail_fragments": 65378, 
    "num_fragments_filtered_vm": 1116098, 
    "num_alignments_below_threshold_for_mapped_fragments_vm": 4959713,
    "percent_mapped": 85.07509608866414
```

The difference between _num_processed_ and _num_mapped_ is 3004166 so ~3m fragments were not mapped. I believe I am under the mistaken impression that _num_decoy_fragmens_ + _num_dovetail_fragments_ + _num_fragments_filtered_vm_ (2000702) would equal that difference.

My question is, what happened to the other 1003464 (3004166-2000702) fragments? Apologies if I missed this explanation in the docs but I could not find it.

**Comment by rob-p** [comment]
Hi @jonahcullen,

  No need to apologize!  We should better document these numbers.  Basically, the elements you point out : `num_decoy_fragments`, `num_dovetail_fragments` and `num_fragments_filtered_vm` are the fragments where alignment was *attempted* but subsequently failed.  In these cases because (1) the read best mapped to a decoy, (2) the best alignment was dovetailed or (3) no alignment passed the alignment score threshold.

In addition to this, fragments can fail to align when no sufficiently good seed is found such that alignment is not even attempted.  This can happen e.g. if no 31-mer from the read matches the transcriptome/genome, or if the only matching 31-mers are degenerate in terms of their frequency (appear thousands of times and are therefore not useful for alignment).  So, the most likely occurrence here is that these ~1M fragments simply had no alignment attempted.  Let me know if this answers your question.

Best,
Rob

**Comment by jonahcullen** [comment]
Thank you very much @rob-p for the prompt and detailed answer! In cases where no good seed is found especially in high numbers (e.g. +10M fragments), in your experience, is that typically baked in upstream from poor library prep or sequencing?
