### ISSUE TITLE
"--libType A" doesn't work in alignment mode

### ISSUE THREAD

**Issue by DarwinAwardWinner** [COMBINE-lab/salmon#79]
It seems that `--libType A` only works when running on a fastq file, not on a bam file. This doesn't seem to be documented anywhere.

**Comment by rob-p** [comment]
Hi Ryan,

  You're right.  This fact is not documented and it should be.  I'll update the docs to address this.  Using the `A` library type with pre-computed alignments has one additional complication that doesn't arise in the quasi-mapping mode.  That is, many aligners offer the user the capability of aligning the reads with a prescribed library type (e.g. TopHat, HISAT, etc.), so that in this case the implied library type depends not only on how the reads map to the underlying transcriptome, but also on the parameters with which the reads were aligned with the upstream alignment tool.  

However, I don't suppose this needs to be a "blocking" technicality.  I'll add this feature to the list for the next minor release.

**Comment by DarwinAwardWinner** [comment]
Are you referring to the issue that if an unstranded library is aligned in stranded mode, then Salmon will infer that the library is stranded due to the lack of alignments on the reverse strand?

**Comment by rob-p** [comment]
Yes; precisely.  In the alignment-based case, Salmon will infer the library type from the alignments.  In the case you mention above (someone performs stranded alignment using an unstranded library), Salmon would incorrectly infer a stranded type, though it would actually be a byproduct of passing incorrect options to the aligner.  In the read-based mode, since we have control over both the mapping and quantification steps, we can avoid such an issue.  However, it seems to me _ok_ to incorrectly infer a library type if we were passed incorrect alignments in the first place, right?

**Comment by DarwinAwardWinner** [comment]
Yes, I'd say that's ok. Just document that there's no way for Salmon to verify that you chose the correct stranded mode during alignment, i.e. Salmon inferring a stranded library type is not an independent confirmation of the library type.

**Comment by rob-p** [comment]
I agree.  I'm working on this feature now, and there is one more (somewhat trivial) complication.  It is that, in read-based mode, the other options inform as to whether the sample is paired-end or single-end (based on whether the user passes in `-1` and `-2` or `-r`).  However, this is not the case in alignment-based mode, as the BAM file can contain either single or paired-end reads.  I propose having separate automatic library type flags for these `AS` (automatic single) and `AP` (automatic paired).  The `A` flag will continue to work in read-based mode, but these others will also be valid.  Does this seem reasonable?

**Comment by DarwinAwardWinner** [comment]
A BAM file can contain both paired and single-end reads. I haven't been using Salmon long enough to know whether it supports a mixture of paired and single reads. If it doesn't, then there's no issue, because you know immediately after reading the first mapped read whether it is paired. If Salmon does support a mixture of paired and single reads, then you have a problem, because you could have, for example, a BAM file with 10 million single-end reads and then one paired set of 2 reads. In other words, you can't conclude a BAM file is single-end only except by checking every read in the file. I think this means that in the worst case, `--libtype A` would require 2 passes through the BAM file, once to check for paired reads and then again to actually run the quantification.

Here's a strategy that might work without 2 passes, possibly at the cost of increased peak memory usage. The release notes say that `--libType A` uses the first 50k reads to infer the lib type. So, read from the BAM file until either enough read pairs (25k pairs?) have been read, and then infer the paired library type from those. If the first 100k reads don't contain 25k pairs, then just infer the orientation of the unpaired/first mate reads. In this case, now feed the input into 3 separate runs of the quantification at once, one for each possible paired library type. For example, if the first-read orientation is inferred as `SF`, then the 3 possible paired library types are `ISF`, `MSF`, and `OSF`. Run the entire file through each of these 3 quantifaction runs, and then decide afterward which one turned out to be correct (probably whichever one counted the most concordantly paired mates?). Then kill the other 2 runs and finish running the chosen one through the rest of the algorithm. That should avoid having to make multiple passes through the input, but you will triple some component of the memory usage up to the point where the two wrong runs are killed.

**Comment by rob-p** [comment]
Thanks for the thorough suggestions.  Actually, we fall into the easier case since Salmon does not support mixing single and paired-end reads in a single BAM file.  When performing quantification on a single sample, the reads for that sample must follow a uniform library type.  For paired-end reads, the BAM file can contain paired-end and single-end alignments (i.e. orphans), but the reads must all have been paired *in sequencing*.  Mixing different library types in the BAM file makes it difficult to assess the compatibility of a fragment with the expected library type, especially if fragments from the different library types are expected to exist in a specific ratio in the input.

Anyway, my main motivation for having the separate `AS` and `AP` types was to prevent the need to "peek" in the file, since, currently, there is not an easy way to peek the first read without opening the first file twice.  However, I've decided that the benefit of having the same uniform (and simpler) interface of `A` always representing automatic library type detection is probably worth it, so I've pushed this implementation (commit 6116b2a).  So, when the user provides the `A` library type, Salmon will peek into the first record in the BAM file to determine if the fragment was paired in sequencing or not, and will then set the single / paired-end status on that basis.  The only corollary to this is that, in alignment-based mode, the `A` flag is not compatible with an input stream (i.e. the input must be a regular file).  I will be sure to document this when I update the docs for the version bump.

**Comment by rob-p** [comment]
Given the alternatives, I think this is currently the best approach for implementing automatic library type detection in alignment-based mode.  I'll add an appropriate note to the documentation to specify that streaming input cannot be used with automatic library type detection when using the `A` library type --- otherwise it should work as in the read-based mode.
