### ISSUE TITLE
Salmon isoform quantification of ONT reads using non-default mapping parameters

### ISSUE THREAD

**Issue by matthew-valentine** [COMBINE-lab/salmon#796]
I am trying to do transcript isoform quantification after mapping ONT long reads to transcripts. I have a transcriptome made up of gencode and novel transcripts identified by following the TALON pipeline. Due to some strangeness when combining the two sets of transcripts, if I run minimap2 with default parameters I get a very large number of unmapped reads that would normally map well to either gencode or TALON transcripts when alone. To combat this, I was advised to change the -f parameter to 1000. In doing so I get a similar amount of mapped reads, but around 6 times as many non-primary alignments as when I map with default parameters to gencode transcripts alone.

Is it still okay to use salmon quantification with data that has been mapped in this way, or will the ONT model not give accurate quantification?

How I have been quantifying:
`salmon quant -p 1 --ont -t transcripts.fa -l SF -a transcriptome.bam -o salmon`

**Comment by rob-p** [comment]
Hi @matthew-valentine,

  In general, extra non-primary alignments are OK. This can, of course, slow down quantification somewhat because many more alignments are being evaluated.  However, salmon (with the `--ont` flag) is designed to consider the provided alignments and allocate the corresponding read proportionally according to all of the relevant probabilities (including alignment quality).  If, under this aligner setting, there are many *highly* sub-optimal alignments being reported, you may consider filtering them out, but that shouldn't be strictly necessary.

Best,
Rob
