### ISSUE TITLE
Bootstrapping output files

### ISSUE THREAD

**Issue by ryanpe13002** [COMBINE-lab/salmon#818]
To whom it may concern,

I am running Salmon with "--numBootstraps 100", but I am unsure where the bootstrapped estimates are doing. Are they incorporated directly into the *.quant.sf file, or is the only output from bootstrapping sent to the "bootstraps.gz" file? Thanks so much for any guidance you can provide!

Kindest regards,
Ryan Englander

**Comment by rob-p** [comment]
Hi @ryanpe13002,

  The bootstrap has no effect on the main `quant.sf` file (that is always the result of the main maximum likelihood estimate).  All bootstrap samples are written to the `bootstraps.gz` file.  If you load your data with the `fishpond` package in `R`, you can request to load the bootstraps to investigate them.  Otherwise, if you use an uncertainty aware tool like [`swish`](https://bioconductor.org/packages/release/bioc/vignettes/fishpond/inst/doc/swish.html) for differential testing, it will make use of the bootstraps automatically to account for inferential uncertainty when performing differential testing.

Best,
Rob
