### ISSUE TITLE
how to quantify reads in alignment-based mode in salmon?

### ISSUE THREAD

**Issue by MonaLiu421** [COMBINE-lab/salmon#822]
Hi, there. Thank you for developing such a useful tool. I have a question about the quantify reads in alignment-based mode.In my bam file, how many times does samlon count the identical read A00399:218:H3NGMDSXY:1:2142:25654:35869, once, twice or four times？I'm a little confused.
![image](https://user-images.githubusercontent.com/45484925/211316769-483e4880-652d-48e0-b56c-f0fd45dff04d.png)

**Comment by rob-p** [comment]
It will be counted once.  All of the _alignments_ that support a specific fragment (i.e. the same `QNAME`) are _potential_ locations that could have given rise to the observed fragment. Salmon will model the probability that each such location is the true origin of the fragment, and will _partially allocate_ (i.e. assign a probability) to each alignment location.  Then, the expected number of reads arising from a transcript in the final quantification result is the sum, over all fragments that align to a transcript, of the probability that this transcript gave rise to this fragment.  However, these are all probabilities, so that the total contribution from any given read is just 1.

**Comment by MonaLiu421** [comment]
Thank you for your reply, the four identical reads will be counted once,but if the four identical reads are aligned to different locations in the reference genome like this,how many times does samlon count?
![image](https://user-images.githubusercontent.com/45484925/211446425-8062d137-fbfd-4d80-aaf1-a310ff563330.png)

**Comment by rob-p** [comment]
It doesn't matter the number of places to which they align (or the number of different targets). All occurrences of the same fragment will have a total probability of 1. So, they will, overall, contribute a mass of 1 fragment in the output.  This is why, for example, if you look at the `NumReads` column in the output, it is not an integer.  This is because transcripts can be assigned part of a read — specifically, they will be assigned the fraction of each read that maximizes the overall likelihood of the observed data.

**Comment by MonaLiu421** [comment]
oh, Then can I rm duplicate identical reads in my bam file? Will this affect my results?
because i got the warning in log file: 
![image](https://user-images.githubusercontent.com/45484925/211450308-2c13c0c6-7a63-4a08-9658-d991c4bf285a.png)
and i check the bam file, actually, there are indeed three identical reads, its not paired,so got the warnings.(may be another read was filtered).
So I wonder if duplicate reads can be deleted?

**Comment by rob-p** [comment]
This is a different issue.  This means that your BAM-file is ill-formed for consumption by salmon.

Basically, the BAM input requirements for salmon are the same as those for RSEM.  Specifically,

* All alignments for a given read must appear contiguously in the BAM file.
* If you have paired-end data, then the alignments must be of the form:
```
alignment_1 for left read
alignment_1 for right read
alignment_2 for left read
alignment_2 for right read
...
alignment_k for left read
alignment_k for right read
```

* You cannot mix alignments for paired-end and single-end reads in the same BAM file.

These requirements must be satisfied or the BAM file cannot be properly parsed / interpreted.  Typically, this is done by passing the proper arguments to the aligner used upstream of salmon (for which we recommend Bowtie2 if you are aligning to a _de novo_ transcriptome or STAR if you are doing reference-based quantification against a genome assembly and annotation).

**Comment by MonaLiu421** [comment]
I got it. This is paired-end sequencing, but I have done some filtering on the results of the alignment, so it does not appear in pairs, so I would like to ask whether it is possible to delete the same readand then quantify?
