### ISSUE TITLE
Read tracking in Salmon (alignment mode)

### ISSUE THREAD

**Issue by apredeus** [COMBINE-lab/salmon#844]
Dear Salmon developers, 

I was wondering if someone can clarify an issue for me - namely, that of how exactly does Salmon track "a read" in an alignment mode. Example: if you have 5 single-end reads that map to 1 transcript, and 5 reads that map to 2 each, your BAM file will have 15 lines overall, but your quantification table should have read counts that sum to 10.

I'm trying to run a bit of a funky set-up when I quantify gene expression from a bunch of bacteria using RSEM or Salmon. However, I used each species as a "gene" and each chromosome/plasmid as a "transcript". What is surprising to me though is that a read that maps to e.g. 5 different places (16S from 5 similar operons) in the same _chromosome_ (== a transcript, in my setup) is counted as 5 reads, not one. This behaviour is the same in both RSEM and Salmon alignment-mode.

My question is, how do these tools track unique reads? I thought it would be via NH or HI tags, but it doesn't seem to be the case - in case of a normal "transcriptomic" human BAM file Salmon works perfectly correctly without any tags at all.

If anybody has any suggestions, I would be very grateful.

**Comment by rob-p** [comment]
Hi @apredeus,

  In short, what you explain in the first paragraph is right and is the expected behavior.  However, to simplify the parsing algorithm (i.e. to ensure that BAM input can be parsed in bounded memory), both `salmon` and `RSEM` require that all of the alignments for a given read are adjacent within the input BAM file.  If this is violated, they will be treated as different reads.

  In other words, if you have something like:

```
read1:aln1
read1:aln2
read1:aln3
read2:aln1
read2:aln2
read2:aln3
```

then in total, 2 "reads" worth of mass will be assigned (probabilistically across the targets). However, if you have

```
read1:aln1
read1:aln2
read2:aln1
read1:aln3
read2:aln2
read2:aln3
```

Then there will be *4* total reads assigned.  Each time the query name (read name modulo 1/2 of a paired-end read) changes in the BAM stream, it is assumed to be a new read, and its alignments are dealt with separately.

Both Bowtie2 and STAR (when projecting genomic alignments to the transcriptome) will follow this convention by default, but I'm not certain the same is true for other aligners.  Again, this restriction is present in both `RSEM` and `salmon`, and it's an optimization that is made because otherwise there can be unbounded distance in the worst case between the different alignments for a read and so the parser would either have to hold all alignments in memory (which is very bad), or make many passes over the input BAM (which is also very bad) to perform quantification.

Let me know if you think this may be the issue in your case.

Best,
Rob

**Comment by apredeus** [comment]
Thank you so much for answering so quickly. This is exactly what it was! I am in fact trying to quantify a genomic BAM (in the bizarre way described above), so it's coordinate-sorted, and it didn't even cross my mind that BAM sorting is what's causing this.
