### ISSUE TITLE
salmon quantify

### ISSUE THREAD

**Issue by SSaleem94** [COMBINE-lab/salmon#854]
Hi, 
I am having an issue with quantifying my salmon quantify using the following script:

#!/bin/bash
# get input data
F=$(cat file_names.txt)
for i in ${F}
do
F1=../processed_fastq/${i}_R1_001_val_1.fastq.gz
F2=../processed_fastq/${i}_R2_001_val_2.fastq.gz
echo "performing salmon quant on ${i}"
salmon quant -i gencode_v43_index -l A -1 ${F1} -2 ${F2} -p 64 /
--validateMappings --writeUnmappedNames -o ${i}
echo "finish quantifying ${i}"
done

 And I got this error message :
Version Info: ### PLEASE UPGRADE SALMON ###
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
Sign up for the salmon mailing list to hear about new versions, features and updates at:
https://oceangenomics.com/subscribe
###
(mapping-based mode) Exception : [the option '--output' is required but missing].
Please be sure you are passing correct options, and that you are running in the intended mode.
alignment-based mode is detected and enabled via the '-a' flag. Exiting.
quantify.sh: line 19: --validateMappings: command not found
finish quantifying 

could you please assist me with that

Thanks

**Comment by rob-p** [comment]
Hi @SSaleem94,

  As the message suggests, your command is missing the required `--output` argument.  Of course, it seems your command includes `-o`.  The rest of the errors suggest that the command line is not being properly parsed.  It looks like the part after the first line break is not being interpreted as a continuation of the same line.  I think this is because the line extension character in the shell is not `/`, but is `\`.  Maybe try the following:
  
```
F=$(cat file_names.txt)
for i in ${F}
do
F1=../processed_fastq/${i}_R1_001_val_1.fastq.gz
F2=../processed_fastq/${i}_R2_001_val_2.fastq.gz
echo "performing salmon quant on ${i}"
salmon quant -i gencode_v43_index -l A -1 ${F1} -2 ${F2} -p 64 \
--validateMappings --writeUnmappedNames -o ${i}
echo "finish quantifying ${i}"
done
```

**Also**, as is suggested by the `salmon` message itself, you may want to consider upgrading to the latest version of `salmon`.

Best,
Rob

**Comment by SSaleem94** [comment]
It worked perfectly.

Thanks a lot for your help
