### ISSUE TITLE
alevin handling of sublibrary BC in Parse data

### ISSUE THREAD

**Issue by davidaknowles** [COMBINE-lab/salmon#874]
Hi all - it seems Parse ("Split-seq V2") data sometimes includes a 4th "cell" barcode corresponding to the Illumina sublibrary. See (not very detailed) [info](https://support.parsebiosciences.com/hc/en-us/articles/360052394312-What-is-a-sublibrary-). 

Looking at some [data](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE189033) it seems collisions based on the first 3 BCs are more common that I would expect (about 8%) but these are resolved by that 4th barcode. Would it be possible to extract this with alevin? Presumably I would need to provide a custom BC geometry rather than using `--splitseqV2`. Is this something you've done previously (or are aware of others doing)? 

Possibly I could analyze the sublibs separately and then merge at the end, but that sounds more painful.

**Comment by rob-p** [comment]
Hi @davidaknowles,

  Assuming that the total size of all cell barcodes doesn't exceed 32 nucleotides, then it should be possible to simply specify them using a custom geometry string. Of course for that to work, we need to know where the 4th barcode is located, so that we can generate the correct custom geometry string to extract it.

  I'll ping @DongzeHE and @k3yavi here to see if either of them are familiar with this chemistry already.  As always, I'd also suggest running this through `alevin-fry` (or using the `simpleaf` wrapper).  While we continue to support `alevin`, `alevin-fry` (largely interfaced by `simpleaf`) is where most of our development effort is currently going, and hopefully we can make the user experience there as smooth and easy as possible!

--Rob

**Comment by davidaknowles** [comment]
Thanks Rob. The sublib BC seems to be 6nt for a total of 30nt so good on that front. If @DongzeHE or @k3yavi know the chemistry already that would be great, if not I can try to figure it out by inspecting the reads. 
I'm using `alevin-fry` downstream but I thought this step (barcode extraction) had to happen via `salmon alevin`?

**Comment by rob-p** [comment]
Hi @davidaknowles,

  Indeed — the barcode extraction will happen either in `salmon alevin` or, if you are using the new `piscem` module for mapping prior to quantification (both are exposed in the `simpleaf` wrapper tool to simplify single-cell processing with `alevin-fry`), then it will happen there.  We have a new very general and much more capable module in the works that will be able to handle all manners of single-cell geometry, but nothing about the Parse library seems beyond the capabilities of the current geometry processing code.  If you share some reads, we can also try and take a look and figure out where the last BC resides.

Best,
Rob

**Comment by davidaknowles** [comment]
So seems I misunderstood this a bit. The 4th "BC" is not in the read itself but corresponds to the Illumina index, so would be in read name in the raw fastq. Unfortunately it seems that gets stripped off in SRA. BUT each index/sublib should correspond to a different SRRid, so I should be able to just run alevin on each SRRid separately and then combine - feels more cumbersome but not terrible. I'll report back on whether this seems to work out in practice, I think we can close this for now.
