### ISSUE TITLE
missing flags for indropV2

### ISSUE THREAD

**Issue by mugpeng** [COMBINE-lab/salmon#878]
There is no flags for indropV2 in lastest version of salmon:
$ salmon -version
salmon 1.10.2

![image](https://github.com/COMBINE-lab/salmon/assets/52995448/cc8f07af-9ac8-431f-8dfa-e3fd3bcae51c)

nohup: 忽略输入
Version Info: This is the most recent version of salmon.
Exception : [unrecognised option '--inDropV2']. Exiting.

**Comment by rob-p** [comment]
Pinging @k3yavi / @DongzeHE  here in case they have an idea of what would be used for this protocol. If we know the fragment geometry, I imagine we could just use the custom geometry flag.

**Comment by k3yavi** [comment]
We have that here, right? https://salmon.readthedocs.io/en/latest/alevin.html#single-cell-protocol-specific-notes

**Comment by mugpeng** [comment]
Yes, I can say the relevant part in both the code and docs, but there is no flag to use it.

**Comment by rob-p** [comment]
Hi @mugpeng,

  This is because it is covered by the custom geometry specification (as laid out in the docs).  I agree it's nice to have a specific flag for each geometry, rather than to have to e.g. specify the custom geometry each time.  We are working on good solutions to that at a higher level (e.g. in our `simpleaf` tool where users can register their own custom geometry specifications and refer to them by name).  However, in `salmon`/`alevin` right now, the named geometries are hard-coded, and so to have a specific `--indropV2` flag, that would have to be added to the argument parser and then mapped to the specific underlying geometry in the code.  This isn't hard, but as the number of different chemistries proliferates, it's not ultimately a scalable solution.

Best,
Rob
