### ISSUE TITLE
Question: Running Salmon on multiplexed sample

### ISSUE THREAD

**Issue by PeteHaitch** [COMBINE-lab/salmon#88]
Hi Rob,
I'm going to be running Salmon on some samples that were multiplexed during sequencing, i.e. each replicate has > 1 pair of FASTQ files. My instinct is that I should concatenate each of R1 and R2 FASTQs at the replicate level and run Salmon on these concatenated files. That way I get one lot of Salmon output per replicate (there's no way to merge/combine Salmon output is there?) and the bias estimation and transcript quantification are done using all reads from that replicate. Is this correct?
Thanks,
Pete

**Comment by rob-p** [comment]
Hi Pete,

  Yup, this would be my recommended way to handle it.  Since salmon accepts streaming input, you could do something like:

```
salmon quant -i index -l A -1 <(gzcat rep1_muliplex1_1.fq.gz rep1_mutliplex2_1.fq.gz) -2 <(gzcat rep1_multiplex1_2.fq.gz rep1_multiplex2_2.fq.gz) [other options etc.]
```

to avoid creating the intermediate concatenated files on disk.  This will treat all the multiplexed samples from the same replicate as one giant input read stream (conceptually representing a single replicate).  As far as merging / combining Salmon output, if you're doing the downstream analysis in R, the tximport package is nice.  Otherwise, @vals has a python tool [readquant](https://github.com/Teichlab/readquant) that can also do some merging.

Best,
Rob

**Comment by PeteHaitch** [comment]
Excellent, I was hoping streaming input would 'just work'. Thanks, Rob!
