### ISSUE TITLE
--writeMappings=<file> fails

### ISSUE THREAD

**Issue by nskbe** [COMBINE-lab/salmon#90]
Running Salmon-0.7.2_linux_x86_64 with --writeMappings=map.out and it crashes with:

Exception : [boost::filesystem::create_directory: No such file or directory]

When I run without a file name, it outputs to stdout, but it also outputs messages such as:
ESC[1m[2016-09-14 11:06:07.550] [jointLog] [info] parsing read library format
ESC[00mESC[1m[2016-09-14 11:06:07.550] [jointLog] [info] There is 1 library.
ESC[00mESC[1m[2016-09-14 11:06:08.300] [jointLog] [info] Loading Quasi index
ESC[00mESC[1m[2016-09-14 11:06:08.300] [jointLog] [info] Loading 32-bit quasi index
So the output is not a clean .sam file.

~/programs/Salmon-0.7.2_linux_x86_64/bin/salmon quant -i /data/reference/salmon/gencode.grch37.v19/ -r test.fastq --seqBias --gcBias --posBias -p 12 --writeMappings=map.out --geneMap /data/reference/salmon/gencode.grch37.v19/geneMap.txt --libType U -o x

**Comment by rob-p** [comment]
Hi @nskbe,

  The issue you're seeing with the mapping file name is related to this note in the release notes:

> Note: In the 0.7.2 release, the file provided to --writeMappings must use a qualified path (e.g. --writeMappings=./out.sam rather than --writeMappings=out.sam), this constraint is already addressed on develop and will be fixed in the next release. 

Essentially, the code should internally qualify the filepath before checking if a directory exists, but it doesn't.  The fix for this is to pass the file name as a qualified path (i.e. adding `./` before the file name when you want it in the current directory).  This is already resolved in develop and the fix for this annoyance will make it into the next release.

Regarding the issue with writing the information to `stdout`; actually, all of the logging messages are written to `stderr`.  If you don't redirect `stdout`, then you'll see everything, but the intended usage for that mode is something like:

```
salmon quant -i idx [other options] --writeMappings > out.sam
```

This will redirect standard out to out.sam.  You'll still see the logging messages on the console, since they are written to `stderr`, but all of the mapping contents are redirected to the file.  Let me know if this resolves your issue.

Best,
Rob

**Comment by nskbe** [comment]
Hi, Rob, thanks for the quick reply! By the way, great job on salmon!

Using ./ did fix the issue.

About the stdout issue, I'm running:

~/programs/Salmon-0.7.2_linux_x86_64/bin/salmon quant -i /data/reference/salmon/gencode.grch37.v19/ -r test.fastq --seqBias --gcBias --posBias -p 12 --geneMap /data/reference/salmon/gencode.grch37.v19/geneMap.txt --libType U -o x --writeMappings > out.sam

and not all messages are output to stderr (I'm not using 2> ). The ones starting with ### do, but others end up in out.sam

out.sam starts with:

ESC[1m[2016-09-14 11:37:38.908] [jointLog] [info] parsing read library format
ESC[00mESC[1m[2016-09-14 11:37:38.908] [jointLog] [info] There is 1 library.
ESC[00mESC[1m[2016-09-14 11:37:43.996] [jointLog] [info] Loading Quasi index
ESC[00mESC[1m[2016-09-14 11:37:43.996] [jointLog] [info] Loading 32-bit quasi index
ESC[00mESC[1m[2016-09-14 11:37:43.996] [stderrLog] [info] Loading Suffix Array 
ESC[00mESC[1m[2016-09-14 11:38:06.669] [stderrLog] [info] Loading Transcript Info 
ESC[00mESC[1m[2016-09-14 11:38:12.374] [stderrLog] [info] Loading Rank-Select Bit Array
ESC[00mESC[1m[2016-09-14 11:38:12.444] [stderrLog] [info] There were 95309 set bits in the bit array
ESC[00mESC[1m[2016-09-14 11:38:12.700] [stderrLog] [info] Computing transcript lengths
ESC[00mESC[1m[2016-09-14 11:38:12.700] [stderrLog] [info] Waiting to finish loading hash
ESC[00mESC[1m[2016-09-14 11:39:49.792] [stderrLog] [info] Successfully loaded position hash
ESC[00mESC[1m[2016-09-14 11:39:49.792] [stderrLog] [info] Done loading index
ESC[00mESC[1m[2016-09-14 11:39:49.792] [jointLog] [info] done
ESC[00mESC[1m[2016-09-14 11:39:49.792] [jointLog] [info] Index contained 95309 targets
ESC[00mESC[33mESC[1m[2016-09-14 11:40:18.128] [jointLog] [warning] Fragment GC bias correction is currently only implemented for paired-end libraries.  Disabling fragment GC bias correction for this run
ESC[00m@HD      VN:1.0  SO:unknown

**Comment by rob-p** [comment]
Hrmm, that shouldn't happen (i.e. that's why the log is called `stderrLog`).  So something is strange there.  I'll take a look.

--Rob

**Comment by rob-p** [comment]
Ahh --- I see what's happening.  This is the offending line:

https://github.com/COMBINE-lab/salmon/blob/develop/src/SalmonUtils.cpp#L1346

I must have changed it and forgotten to change back at some point.  That should be stderr, not stdout.  I'll fix this in develop and build a new release.

--Rob
