### ISSUE TITLE
Incorrect flags for unmapped reads with --writeMappings

### ISSUE THREAD

**Issue by vasisht** [COMBINE-lab/salmon#94]
The not primary alignment flag is set for unmapped reads in the SAM file.  The RNAME, POS and CIGAR are also set. I'm not sure if this is additional information for a read, since it did not map to any transcript.  It's not a major issue, since the checks for some of these can be turned off.

example:
`
NB501336:15:H3KVTBGXY:1:11103:9432:10865  373     ENST00000536438 1314    0       151S    =       1314    0       CTTGGTAACTTTGTGTTTGACTTCTATAGTTTAGGTAACTTTGTGTTTGAGTAGGGGTGAAGCCCAGCTGCTCATGAAAAAGTTTGAGTCAGCCAAGCGTGACTTTGATAAAGTGCTGGAAGTAAACCCCATAGATCGGAATAGCAAACGT  *       NH:i:3
`

**Comment by rob-p** [comment]
Hi @vasisht,

  Actually, the settings of these flags aren't incorrect according to the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf):

> Bit 0x4 is the only reliable place to tell whether the read is unmapped. If 0x4 is set, no assumptions can be made about RNAME, POS, CIGAR, MAPQ, and bits 0x2, 0x100, and 0x800.

That is, if the unmapped flag is set, then there is not a specific "correct" setting for these other fields, since they should most likely be ignored anyway.  That being said, concordant with some small changes in the [most-recent RapMap](https://github.com/COMBINE-lab/RapMap/releases/tag/v0.4.0), the CIGAR string will be set to `*` for unmapped reads in future versions of Salmon.  We may consider setting other fields to `*` for unmapped reads to simplify the output, but, as the SAM spec suggests, these fields offer quite a bit of freedom in terms of "legal" values if the unmapped flag is set anyway.

**Comment by vasisht** [comment]
@rob-p That's a good point. I have been relying on Picard for validating the files and this was flagged as an error. Incorrectly so as you point out. Is there any validation for the CIGAR strings that are generated?  In some cases with some of the shorter transcripts, the operator falls of the end of the reference. ENST00000424567 is 135 bp long. 

```
NB501336:15:H3KVTBGXY:1:13202:16266:9834	99	ENST00000424567	1	1	1S150M	=	1	-135	GTAGTCGAAACTGAAGAAGACAGAGACGCAAGAGAAATTCGATAAGTCGAAACTGAAGAAGACAGAGACGCAAGAGAAAAATCCACTGCCCGAGATCGGAAGAGCACACGTCAGAACTCCAGTCACCGTAGAAGCTCGTATGCCGTCTTCG	*	NH:i:7
```
