### ISSUE TITLE
Memory Limits for Very Large Transcriptomes

### ISSUE THREAD

**Issue by rhlampe** [COMBINE-lab/salmon#97]
I'm looking at using Salmon on metatranscriptomes (environmental de novo assemblies). Our assemblies are typically very large, i.e. many millions of sequences. When scheduling jobs on my university's cluster (LSF), I'm required to set a memory limit. When salmon exceeds this limit, the job is killed, and I must restart the process. Is there a recommendation for predicting how much memory salmon will use to index/quant based on the size of the transcriptome? Could it be possible to set a memory limit for salmon so that it doesn't attempt to call more than is allocated?

Thank you!

**Comment by rob-p** [comment]
Hi @rhlampe,

  Currently, there is no way to prevent the salmon indexer from using more memory if it is needed ot build the index.  However, if there is a limit placed by the cluster, it will likely just result in a `bad_alloc` exception from the indexer.  The number of sequences alone can tell you a bit about scaling, but the total number of nuclotides being indexed is actually a better predictor of resource usage.  How many nucleotides, total, are the references you're considering?  While we are working on ways to make the indexing scheme highly scalable, it's worth noting that, to achieve some of it's speed, salmon pre-computes a lot of information it its index (so that the index can become fairly large).

  One thing I might suggest, if you want to attempt to index and quantify on a very large reference, is to use the `--perfectHash` index in the newest development version of Salmon (pre-release tarball attached below).  The latest version (for which the official version should appear soon) represents a number of improvements to index construction.  The default indexer has reduced memory usage by ~40%, and the new `--perfectHash` indexer, while somewhat slower, reduces the memory usage even more (by an additional 40-50%).  With a fixed memory budget, then, it should allow you to index ever larger references.

--Rob

[Salmon-v0.7.3-pre_linux_x86_64.tar.gz](https://github.com/COMBINE-lab/salmon/files/512019/Salmon-v0.7.3-pre_linux_x86_64.tar.gz)

**Comment by rob-p** [comment]
After some conversation on Gitter, it seems like this is resolved (positively :)), so I'm going to close the issue.
